<?php
$this->headTitle($this->title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin-opta-uploader'));
$form->prepare();
echo $this->form()->openTag($form);
$elements = $form->getElements();
?>
<div class="container-fluid">
    <div class="form">
        <div class="row-fluid">
            <?php
            foreach ($elements as $element) :
                $type = $element->getAttribute('type');
                $hint = $element->getAttribute('hint');
                if ($type != 'submit') : ?>
                    <div class="control-group form-horizontal">
                        <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                        <div class="controls">
                            <?php if ($type == 'file') : ?>
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="input-append">
                                    <div class="uneditable-input">
                                        <i class="icon-file fileupload-exists"></i>
                                        <span class="fileupload-preview">
                                        </span>
                                    </div>
                                    <span class="btn btn-file">
                                        <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                        <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                        <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                    </span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                </div>
                            </div>
                            <?php elseif ($type == 'select'): ?>
                                <?php echo $this->formSelect($element);?>
                            <?php endif; ?>
                            <?php if (!empty($hint)) : ?>
                                <span class="help-inline"><?=$hint?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endif; endforeach; ?>
            <div class="form-actions">
                <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->