<?php
$title = 'Pre-Match Content';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i><?php echo $this->translate('Pre-Match Report Default Content');?></h4>
            </div>
            <div class="portlet-body">
                <div class="form">
                    <div class="row-fluid">
                        <?php
                        $form = $this->reportContentForm;
                        $params = array('action' => 'saveDefaultContent');
                        $form->setAttribute('action', $this->url('admin-pre-match-content', $params));
                        $elements = $form->getElements();
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $this->renderLanguageFieldsets($form->getFieldsets(), false); ?>
                        <div class="form-actions">
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                            <button type="button" class="btn">Cancel</button>
                        </div>
                        <?php echo $this->form()->closeTag();?>
                    </div>
                </div>
            </div>
        </div>
        <div class="portlet box blue">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i><?php echo $this->translate('Pre-Match Share Copy');?></h4>
            </div>
            <div class="portlet-body">
                <div class="form">
                    <div class="row-fluid">
                        <?php
                        $form = $this->preMatchReportCopyForm;
                        $form->setAttribute('action', $this->url('admin-pre-match-content'));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $elements = $form->getElements();
                        ?>
                        <?php foreach ($elements as $element) :
                            $type = $element->getAttribute('type');
                            $hint = $element->getAttribute('hint');
                            if ($type != 'submit') : ?>
                                <div class="control-group form-horizontal">
                                    <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                                    <div class="controls">
                                        <?=$this->formElement($element);?>
                                        <?php if (!empty($hint)) : ?>
                                            <span class="help-inline"><?=$hint?></span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; endforeach; ?>
                        <div class="form-actions">
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                            <button type="button" class="btn" onclick="this.form.reset();">Cancel</button>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/ckeditor/ckeditor.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    CKEDITOR.config.language = 'en';
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->