<?php
$this->headTitle($this->title);
?>
<?php if (!is_null($this->form)):?>
<div class="container-fluid">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin-users', $this->params));
    $elements = $form->getElements();
    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    ?>
    <div class="form">
        <div class="row-fluid">
            <?php foreach($elements as $element):?>
                <?php
                $type = $element->getAttribute('type');
                $hint = $element->getAttribute('hint');
                ?>
                <?php if ($element->getAttribute('name') != 'submit'):?>
                        <div class="control-group form-horizontal">
                            <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                            <div class="controls">
                            <?php if ($type == 'text'):?>
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?> value="<?=$element->getValue();?>"/>
                                </div>
                            <?php elseif($type == 'select'):?>
                                <?php echo $this->formSelect($element);?>
                            <?php endif;?>
                            <?php if (!empty($hint)) : ?>
                                <span class="help-inline"><?=$hint?></span>
                            <?php endif; ?>
                            </div>
                        </div>

                <?php else:?>
                    <div class="form-actions">
                        <?php if ($this->params['action'] == 'addAdmin'):?>
                            <a href="#confirmModal" role="button" class="btn blue"  data-toggle="modal">
                                <i class="icon-ok"></i> <?=$this->translate($element->getValue());?>
                            </a>
                            <div id="confirmModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                    <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm')?></h3>
                                </div>
                                <div class="modal-body">
                                    <p><?php echo $this->translate("If you wish to create a new admin for the platform an email will be sent to the admin with log in details.");?></p>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close');?></button>
                                    <button data-dismiss="modal" class="btn blue"
                                            onclick="$('#admin-form').submit();">
                                        <?php echo $this->translate('Confirm');?>
                                    </button>
                                </div>
                            </div>
                        <?php else: ?>
                            <button type="submit" class="btn blue"><?=$this->translate($element->getValue());?></button>
                            <a href="#deleteModal<?=$this->params['id'];?>" role="button" class="btn btn-warning red" data-toggle="modal">
                                <i class="icon-trash"></i>
                                <?=$this->translate('Delete')?>
                            </a>
                            <div id="deleteModal<?=$this->params['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                    <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm');?></h3>
                                </div>
                                <div class="modal-body">
                                    <p><?php echo $this->translate('Are you sure you want to delete this admin?');?></p>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                    <button data-dismiss="modal" class="btn blue"
                                            onclick="window.location.href = '<?=$this->url('admin-users', array('action' => 'deleteAdmin', 'id' => $this->params['id']))?>';"><?php echo $this->translate('Confirm');?></button>
                                </div>
                            </div>
                            </td>
                        <?php endif;?>

                        <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>
<?php endif;?>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function(){
        App.init(); // initlayout and core plugins
        $('button.reset').click(function(e){
            e.preventDefault();
            this.form.reset();
        });
    });
</script>