<?php
$title = $this->translate('Admins');
$this->headTitle($title);
?>
<div>
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <h4><i class="icon-user"></i><?=$this->translate('Admins')?></h4>
                    <div class="actions">
                        <a href="<?=$this->url('admin-users', array('action' => 'addAdmin'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('New admin')?></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php if (!empty($this->admins)) : ?>
                        <table class="table table-striped table-bordered table-hover" id="admins-table">
                            <thead>
                            <tr>
                                <th><?=$this->translate('First Name')?></th>
                                <th><?=$this->translate('Last Name')?></th>
                                <th><?=$this->translate('Email')?></th>
                                <th><?=$this->translate('Type')?></th>
                                <th><?=$this->translate('Last logged in')?></th>
                                <th style="width:124px;"><?=$this->translate('Action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->admins as $admin) : ?>
                                <tr class="odd gradeX">
                                    <td><?=$admin['firstName'];?></td>
                                    <td><?=$admin['lastName'];?></td>
                                    <td><a href="mailto:<?=$admin['email'];?>"><?=$admin['email'];?></a></td>
                                    <td><?=$admin['role']['name'];?></td>
                                    <td>
                                        <?php echo (!is_null($admin['lastLoggedIn']) ? $admin['lastLoggedIn']->format('D, d M Y H:i') : $this->translate('Never'));?>
                                    </td>
                                    <td>
                                        <a href="<?=$this->url('admin-users', array('action' => 'editAdmin', 'id' => $admin['id']))?>" class="btn mini blue">
                                            <i class="icon-edit"></i>
                                            <?=$this->translate('Edit')?>
                                        </a>
                                        <a href="#deleteModal<?=$admin['id'];?>" role="button" class="btn btn-warning mini red" data-toggle="modal">
                                            <i class="icon-trash"></i>
                                            <?=$this->translate('Delete')?>
                                        </a>
                                        <div id="deleteModal<?=$admin['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm');?></h3>
                                            </div>
                                            <div class="modal-body">
                                                <p><?php echo $this->translate('Are you sure you want to delete this admin?');?></p>
                                            </div>
                                            <div class="modal-footer">
                                                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                                <button data-dismiss="modal" class="btn blue"
                                                        onclick="window.location.href = '<?=$this->url('admin-users', array('action' => 'deleteAdmin', 'id' => $admin['id']))?>';"><?php echo $this->translate('Confirm');?></button>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <?=$this->translate('There is no admins')?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('admins per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ admins')?>"};
        var oTable = $('#admins-table').dataTable({
            "aoColumns": [null, null,null,null,{"sType" : "date"},{bSortable: false}],
            "bStateSave" : true,
            "aLengthMenu": [[5, 10, 15, 25, 50, 100 , -1], [5, 10, 15, 25, 50, 100, "All"]],
            "iDisplayLength" : App.getDefaultItemsPerPage(),

            "iCookieDuration": 60 * 60 * 24 * 365 * 100,
            "fnStateLoadParams" : function(oSettings, oData){
                oData.oSearch.sSearch = '';
                oData.aaSorting = [];
            },
            // "bFilter": false,
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
        oTable.fnSort( [ [0,'asc'] ] );
    });
</script>
<!-- END JAVASCRIPTS -->