<?php
$title = 'Users';
$this->headTitle($title);
?>
<div>
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <h4><i class="icon-user"></i><?=$this->translate('All Users')?></h4>
                    <div class="actions">
                        <a href="<?=$this->url('admin-users', array('action' => 'export'))?>" class="btn green"><i class="icon-share"></i> <?=$this->translate('Export')?></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php if (!empty($this->users)) : ?>
                        <table class="table table-striped table-bordered table-hover" id="users-table">
                            <thead>
                                <tr>
                                    <th><?=$this->translate('Name')?></th>
                                    <th><?=$this->translate('Email')?></th>
                                    <th><?=$this->translate('Joined')?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->users as $user) : ?>
                                    <tr class="odd gradeX">
                                        <td><?=$user['displayName']?></td>
                                        <td><a href="mailto:<?=$user['email']?>"><?=$user['email']?></a></td>
                                        <td>
                                            <?=$user['date']->format("j F H:i")?>
                                        </td>
                                        <td>
                                            <a href="<?=$this->url('admin-users', array('action' => 'view', 'id' => $user['id']))?>" class="btn mini blue">
                                                <i class="icon-eye-open"></i>
                                                <?=$this->translate('View')?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <?=$this->translate('There is no registered users')?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('users per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ users')?>"};
        TableManaged.init(messages, [
            null,
            null,
            null,
            { "bSortable": false }
        ],
        [[ 2, "desc" ]]);
    });
</script>
<!-- END JAVASCRIPTS -->