<?php
$title = $this->user['displayName'];
$this->headTitle($title);
$active = $this->navigation('navigation')->breadcrumbs()->findActive($this->navigation('navigation')->breadcrumbs()->getContainer());
if ($active != null) {
    if (is_array($active))
        $active = array_shift($active);
    $active->setTitle($title);
}
?>
<!-- BEGIN PAGE CONTENT-->
<div class="row-fluid profile-classic">
    <div class="span2"><img src="<?=$this->user['avatar']['mediumImagePath']?>" alt=""></div>
    <ul class="unstyled span10">
        <li><span><?=$this->translate('Display Name')?>:</span> <?=$this->user['displayName']?></li>
        <li><span><?=$this->translate('First Name')?>:</span> <?=$this->user['firstName']?></li>
        <li><span><?=$this->translate('Last Name')?>:</span> <?=$this->user['lastName']?></li>
        <li><span><?=$this->translate('Birthday')?>:</span> <?=$this->user['birthday']->format('j F Y')?></li>
        <li><span><?=$this->translate('Email')?>:</span> <a href="mailto:<?=$this->user['email']?>"><?=$this->user['email']?></a></li>
        <li><span><?=$this->translate('Role')?>:</span> <?=$this->user['role']['name']?></li>
        <li><span><?=$this->translate('Registration Date')?>:</span> <?=$this->user['date']->format('j F Y')?></li>
    </ul>
</div>
<!-- END PAGE CONTENT-->
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/pages/profile.css" />
<!-- END PAGE LEVEL STYLES -->
