<?php if (!$this->onlyRows) : ?>
    <div role="main" class="two-column-section clearfix">
        <div class="first-column league-tables">
            <h1><?=$this->translate('League Table')?></h1>
            <div class="league">
                <header class="clearfix">
                    <h2>December</h2>
                    <form id="season-filter">
                        <div>
                            <select>
                                <option value="default">&ndash; Select season &ndash;</option>
                                <option value="">1</option>
                            </select>
                        </div>
                    </form>
                </header>

                <section>
                    <div class="block">
                        <table id='league-table'>
                            <tr>
                                <th colspan="3">
                                </th>
                                <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                            </tr>
                            <?php endif; ?>
                            <?php foreach ($this->leagueUsers as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                            <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                <td class="position">
                                    <?php if ($isActive) : ?><span><?php endif;?>
                                    <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                    <?php if ($isActive) : ?></span><?php endif;?>
                                </td>
                                <td class="player"><?=$user['displayName']?></td>
                                <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                <td class="points"><?=$user['points'] !== null ? $user['points'] : '-'?></td>
                            </tr>
                            <?php endforeach; ?>
                            <?php if (!$this->onlyRows) : ?>
                        </table>
                        <input type="hidden" id="users-count" value="<?=$this->leagueUsersCount?>"/>
                    </div>
                </section>
                <?php if ($this->leagueUsersCount > $this->perPage) : ?>
                    <p class="align-center">
                        <a href="#" class="show-more" id='show-more'><?=$this->translate('Show more')?></a>
                    </p>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->partial('partials/right-column'); ?>
    </div>
    <script type="text/javascript" src="/js/league-table.js"></script>
<?php endif; ?>