<?php
$this->headTitle($this->leagueName . ' - ' . $this->seasonName);
?>
<?php if (!$this->onlyRows) : ?>
    <div role="main" class="two-column-section clearfix">
        <div class="first-column league-tables">
            <?php if ($this->league->getType() == \Application\Model\Entities\League::PRIVATE_TYPE) : ?>
                <link rel="stylesheet" href="/css/private-league.css">
                <?php if ($this->league->getCreator()->getId() == $this->getCurrentUser()->getId()) : ?>
                    <a href="" id="league-code-button" class="more-info private-league-button"><?=$this->translate('League Code')?></a>
                    <a href="" id="league-edit-button" class="more-info private-league-button"><?=$this->translate('Edit')?></a>
                <?php else : ?>
                    <a href="" id="league-leave-button" class="more-info private-league-button"><?=$this->translate('Leave')?></a>
                <?php endif; ?>
            <?php endif; ?>
            <h1><?=$this->translate('League Table')?></h1>
            <div class="league">
                <header class="clearfix">
                    <h2><?=$this->seasonName?></h2>
                    <form id="season-filter">
                        <div>
                            <select name='league-filter' id='league-filter'>
                                <option value="everyone" selected="selected"><?=$this->translate('Everyone')?></option>
                                <?php if ($this->getCurrentUser()->getFacebookId() !== null) : ?>
                                    <option value="your-friends"><?=$this->translate('Your friends')?></option>
                                <?php endif; ?>
                                <option value="you-and-around"><?=$this->translate('You and around you')?></option>
                            </select>
                        </div>
                    </form>
                </header>

                <section>
                    <div class="block">
                        <table id='league-table'>
                            <tr>
                                <th colspan="3">
                                    <h3><?=$this->leagueName?></h3>
                                </th>
                                <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                            </tr>
                            <?php endif; ?>
                            <?php foreach ($this->leagueUsers as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                            <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                <td class="position">
                                    <?php if ($isActive) : ?><span><?php endif;?>
                                    <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                    <?php if ($isActive) : ?></span><?php endif;?>
                                </td>
                                <td class="player">
                                    <?=$user['displayName']?>
<!--                                    &nbsp;<a class="remove-player">X</a>-->
                                </td>
                                <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                <td class="points">
                                    <?php if ($isActive) : ?><span><?php endif;?>
                                    <?=$user['points'] !== null ? $user['points'] : '-'?>
                                    <?php if ($isActive) : ?></span><?php endif;?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            <?php if (!$this->onlyRows) : ?>
                        </table>
                        <input type="hidden" id="users-count" value="<?=$this->leagueUsersCount?>"/>
                    </div>
                </section>
                <?php if ($this->leagueUsersCount > $this->perPage) : ?>
                    <p class="align-center">
                        <a href="#" class="show-more" id='show-more'><?=$this->translate('Show more')?></a>
                    </p>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->partial('partials/right-column'); ?>
    </div>
    <script type="text/javascript" src="/js/league-table.js"></script>
<?php endif; ?>