<?php $this->headTitle($this->translate($this->title));?>
<?php if (!is_null($this->form) && $this->form instanceof \Zend\Form\Form ):?>
            <?php
            $this->form->prepare();
            $this->form->setAttribute('action', $this->url('admin-content-footer-pages', $this->params));
            echo $this->form()->openTag($this->form);
            ?>
            <?php echo $this->renderLanguageFieldsets($this->form->getFieldsets(), false);?>
            <div class="form-actions">
                <button type="submit" class="btn blue"><?=$this->translate($this->form->get('submit')->getValue());?></button>
            </div>
            <?php echo $this->form()->closeTag();?>
    <!--TERMS PAGE ENDS-->
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<!-- END PAGE LEVEL STYLES -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/ckeditor/ckeditor.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

<script type="text/javascript">
    CKEDITOR.config.language = 'en';
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->