<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Avatar extends \Application\Model\Entities\Avatar implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setOriginalImagePath($originalImagePath)
    {
        $this->__load();
        return parent::setOriginalImagePath($originalImagePath);
    }

    public function getOriginalImagePath()
    {
        $this->__load();
        return parent::getOriginalImagePath();
    }

    public function setBigImagePath($bigImagePath)
    {
        $this->__load();
        return parent::setBigImagePath($bigImagePath);
    }

    public function getBigImagePath()
    {
        $this->__load();
        return parent::getBigImagePath();
    }

    public function setMediumImagePath($mediumImagePath)
    {
        $this->__load();
        return parent::setMediumImagePath($mediumImagePath);
    }

    public function getMediumImagePath()
    {
        $this->__load();
        return parent::getMediumImagePath();
    }

    public function setSmallImagePath($smallImagePath)
    {
        $this->__load();
        return parent::setSmallImagePath($smallImagePath);
    }

    public function getSmallImagePath()
    {
        $this->__load();
        return parent::getSmallImagePath();
    }

    public function setTinyImagePath($tinyImagePath)
    {
        $this->__load();
        return parent::setTinyImagePath($tinyImagePath);
    }

    public function getTinyImagePath()
    {
        $this->__load();
        return parent::getTinyImagePath();
    }

    public function setIsDefault($isDefault)
    {
        $this->__load();
        return parent::setIsDefault($isDefault);
    }

    public function getIsDefault()
    {
        $this->__load();
        return parent::getIsDefault();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getArrayCopy()
    {
        $this->__load();
        return parent::getArrayCopy();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'originalImagePath', 'bigImagePath', 'mediumImagePath', 'smallImagePath', 'tinyImagePath', 'isDefault', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}