<?php
$title = $this->translate($this->title);
$this->headTitle($title);
?>
<?php if (!is_null($this->form)):?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url($this->route, $this->params));
        $form->prepare();
        echo $this->form()->openTag($form);
        $elements = $form->getElements();
        ?>
        <div class="form">
            <div class="row-fluid">
                <?php
                foreach ($elements as $element) :
                    $type = $element->getAttribute('type');
                    $hint = $element->getAttribute('hint');
                    $maxlength = $element->getAttribute('maxlength');
                    if ($type != 'submit') : ?>
                        <div class="control-group form-horizontal">
                            <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                            <div class="controls">
                                <?php if ($type == 'text') : ?>
                                    <div class="input-prepend">
                                        <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$type?>" name="<?=$element->getName()?>" <?php echo (!empty($maxlength) ? 'maxlength="'.$maxlength.'"' : '');?> value="<?=$element->getValue()?>"/>
                                    </div>
                                <?php elseif($type == 'number'): $currentOrder = $element->getValue();?>
                                    <select class="span2 m-wrap" name="<?=$element->getName()?>" data-placeholder="Select Order">
                                        <?php for ($i = 0; $i < $this->order; $i++) : ?>
                                            <option <?=$i + 1 == (empty($currentOrder) ? $this->order : $currentOrder) ? 'selected="selected"' : ''?> value="<?=$i + 1?>"><?=$i + 1?></option>
                                        <?php endfor; ?>
                                    </select>
                                <?php elseif($type == 'textarea'): ?>
                                    <div class="input-prepend">
                                        <textarea class="span12 ckeditor m-wrap" name="<?=$element->getAttribute('name')?>" rows="10"><?=$element->getValue()?></textarea>
                                    </div>
                                <?php elseif($type == 'file'): $image = $element->getValue() instanceof \Application\Model\Entities\ContentImage ? $element->getValue()->getWidth1280() : false;?>
                                    <div class="fileupload fileupload-<?=(!empty($image) ? 'exists' : 'new')?>" data-provides="fileupload">
                                        <div class="input-append">
                                            <div class="uneditable-input">
                                                <i class="icon-file fileupload-exists"></i>
                                                <span class="fileupload-preview"><?=(!empty($image) ? '<input type="hidden" name="' . $element->getAttribute('name') . '[stored]" value="1"/><a href="' . $image . '" target="_blank">' . $this->translate('Open') . '</a>' : '')?></span>
                                            </div>
                                    <span class="btn btn-file">
                                        <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                        <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                        <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                    </span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if (!empty($hint)) : ?>
                                    <span class="help-inline"><?=$hint?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; endforeach; ?>
                <div class="form-actions">
                    <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                    <button type="button" class="btn" onclick="this.form.reset();">Cancel</button>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/ckeditor/ckeditor.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    CKEDITOR.config.language = 'en';
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->