<?php
$title = $this->translate('How to play');
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="tabbable tabbable-custom boxless">
            <?php if (!empty($this->languages)):?>
            <ul class="nav nav-tabs">
                <?php foreach ($this->languages as $i => $language) : ?>
                    <li <?= ($language['id'] == $this->currentLanguage->getId() ? ' class="active"' : '')?>>
                        <a href="<?=$this->url($this->route, array('language' => $language['id']));?>"><?php echo $language['displayName'];?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <div class="tab-content">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <h4><?=$this->translate('How to Play Blocks')?></h4>
                        <div class="actions">
                            <?php if (count($this->blocks) < $this->maxBlocksNumber): ?>
                                <a href="<?=$this->url($this->route, array('language' => $this->currentLanguage->getId(),'action' => 'add'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Add')?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <?php if (!empty($this->blocks)) : ?>
                            <table class="table table-striped table-bordered table-hover" id="how-to-play-table">
                                <thead>
                                <tr>
                                    <th><?=$this->translate('Order')?></th>
                                    <th style="width: 200px"><?=$this->translate('Heading')?></th>
                                    <th><?=$this->translate('Description')?></th>
                                    <th style="width: 145px"><?=$this->translate('Foreground Image')?></th>
                                    <th style="width: 125px"><?php echo $this->translate('Action');?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($this->blocks as $block) : ?>
                                    <tr class="odd gradeX">
                                        <td><?=$block['order']?></td>
                                        <td><?=$block['heading']?></td>
                                        <td><?=$block['description']?></td>
                                        <td>
                                            <?php if (!empty($block['foregroundImage']['width1280'])):?>
                                                <a href="<?php echo $block['foregroundImage']['width1280'];?>" target="_blank"><?php echo $this->translate('Open');?></a>
                                            <?php endif;?>
                                        </td>
                                        <td>
                                            <a href="<?=$this->url($this->route, array('action' => 'edit', 'block' => $block['id'], 'language' => $this->currentLanguage->getId()))?>" class="btn mini blue">
                                                <i class="icon-edit"></i>
                                                <?=$this->translate('Edit')?>
                                            </a>
                                            <a href="#deleteModal<?php echo $block['id'];?>" role="button" class="btn btn-warning mini red" data-toggle="modal">
                                                <i class="icon-trash"></i>
                                                <?=$this->translate('Delete')?>
                                            </a>
                                            <div id="deleteModal<?php echo $block['id'];?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm');?></h3>
                                                </div>
                                                <div class="modal-body">
                                                    <p><?php echo $this->translate('Are you sure you want to delete this block?');?></p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                                    <button data-dismiss="modal" class="btn blue"
                                                            onclick="window.location.href = '<?=$this->url($this->route, array('action' => 'delete', 'block' => $block['id'], 'language' => $this->currentLanguage->getId()))?>';"><?php echo $this->translate('Confirm');?></button>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                            <?=$this->translate('There is no blocks created')?>
                        <?php endif; ?>
                    </div>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>