<?php echo $this->doctype(); ?>
<!--[if IE 8]><html lang="en" class="ie8"><![endif]-->
<!--[if IE 9]><html lang="en" class="ie9"><![endif]-->
<!--[if !IE]><!--><html lang="en"><!--<![endif]-->
<!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->translate('Admin Dashboard'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))?>

        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style-metro.css" rel="stylesheet" />
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/pages/login.css" rel="stylesheet" type="text/css"/>
        <!-- END PAGE LEVEL STYLES -->

    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <body class="login">
        <!-- BEGIN LOGO -->
        <div class="logo">
<!--            <img src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/img/logo-big.png" alt="" />-->
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <?php echo $this->content; ?>
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
        <div class="copyright">
            2013 &copy; Neoco. Admin Dashboard.
        </div>
        <!-- END COPYRIGHT -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-1.8.3.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!--[if lt IE 9]>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/excanvas.js"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/respond.js"></script>
        <![endif]-->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/breakpoints/breakpoints.js" type="text/javascript"></script>
        <!-- IMPORTANT! jquery.slimscroll.min.js depends on jquery-ui-1.10.1.custom.min.js -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery.blockui.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery.cookie.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/login.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <script>
            jQuery(document).ready(function() {
                App.init();
                var messages = {emailR: "<?=$this->translate("Email is required.")?>", pwdR: "<?=$this->translate('Password is required.')?>",
                    pwd2R: "<?=$this->translate('Password confirmation is required.')?>", pwdV: "<?=$this->translate('Please repeat the password you entered above.')?>",
                    pwdV1: "<?=$this->translate('Input at least {0} symbols.')?>", pwdV2: "<?=$this->translate('Input up to {0} symbols.')?>",
                    emailV: "<?=$this->translate('Please enter a valid email address.')?>"};
                Login.init(messages);
            });
        </script>
        <!-- END JAVASCRIPTS -->
    </body>
<!-- END BODY -->
</html>