<?php echo $this->doctype(); ?>
<!--[if IE 8]><html lang="en" class="ie8"><![endif]-->
<!--[if IE 9]><html lang="en" class="ie9"><![endif]-->
<!--[if !IE]><!--><html lang="en"><!--<![endif]-->
<!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle($this->translate('Admin Dashboard') .' - '.$this->getAppClub()->getDisplayName())->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . $this->getConstant('favicon_path') . "?" . rand(0, 1)))?>

        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-1.8.3.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!--[if lt IE 9]>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/excanvas.js"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/respond.js"></script>
        <![endif]-->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/breakpoints/breakpoints.js" type="text/javascript"></script>
        <!-- IMPORTANT! jquery.slimscroll.min.js depends on jquery-ui-1.10.1.custom.min.js -->
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery.blockui.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery.cookie.js" type="text/javascript"></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
        <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/custom.js" type="text/javascript" ></script>
        <!-- END CORE PLUGINS -->

        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style-metro.css" rel="stylesheet" />
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->

    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <body class="fixed-top">
        <!-- BEGIN HEADER -->
        <div class="header navbar navbar-inverse navbar-fixed-top">
            <!-- BEGIN TOP NAVIGATION BAR -->
            <div class="navbar-inner">
                <div class="container-fluid">
                    <!-- BEGIN LOGO -->
                    <a class="brand" href="<?=$this->url('admin-home')?>">
                        <img src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/img/TF-CMS-header-logo.png" alt="logo" />
                    </a>
                    <!-- END LOGO -->
                    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                    <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                        <img src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/img/menu-toggler.png" alt="" />
                    </a>
                    <!-- END RESPONSIVE MENU TOGGLER -->
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <ul class="nav pull-right">
                        <!-- BEGIN USER LOGIN DROPDOWN -->
                        <li class="dropdown user">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img alt="" src="<?=$this->getCurrentUser()->getAvatar()->getTinyImagePath()?>" />
                                <span class="username"><?=$this->getCurrentUser()->getDisplayName()?></span>
                                <i class="icon-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?=$this->url('admin-account')?>"><i class="icon-user"></i><?=$this->translate('My Account')?></a></li>
                                <li class="divider"></li>
                                <li><a href="<?=$this->url('admin-login/process', array('action'=>'logout'))?>"><i class="icon-key"></i><?=$this->translate('Log Out')?></a></li>
                            </ul>
                        </li>
                        <!-- END USER LOGIN DROPDOWN -->
                    </ul>
                    <!-- END TOP NAVIGATION MENU -->
                </div>
            </div>
            <!-- END TOP NAVIGATION BAR -->
        </div>
        <!-- END HEADER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container row-fluid">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar nav-collapse collapse">
                <!-- BEGIN SIDEBAR MENU -->
                <?php echo $this->navigation('navigation')->menu()
                    ->setPartial('admin/partials/menu'); ?>
                <!-- END SIDEBAR MENU -->
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN PAGE -->
            <div class="page-content">
                <!-- BEGIN PAGE CONTAINER-->
                <div class="container-fluid">
                    <!-- BEGIN PAGE HEADER-->
                    <div class="row-fluid">
                        <div class="span12">
                            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                            <h3 class="page-title">
                                <?php
                                $active = $this->navigation('navigation')->breadcrumbs()->findActive($this->navigation('navigation')->breadcrumbs()->getContainer());
                                if ($active != null) {
                                    if (is_array($active))
                                        $active = array_shift($active);
                                    echo $active->getTitle();
                                }
                                ?>
                            </h3>
                            <?php echo $this->navigation('navigation')->breadcrumbs()->setPartial('admin/partials/breadcrumbs'); ?>
                            <!-- END PAGE TITLE & BREADCRUMB-->
                        </div>
                    </div>
                    <?php print $this->renderMessages(true); ?>
                    <!-- END PAGE HEADER-->
                    <?php echo $this->content; ?>
                </div>
                <!-- END PAGE CONTAINER-->
            </div>
        <!-- END PAGE -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="footer">
            2013 &copy; TrueFan Ltd.
            <div class="span pull-right">
                <span class="go-top"><i class="icon-angle-up"></i></span>
            </div>
        </div>
        <!-- END FOOTER -->
    </body>
<!-- END BODY -->
</html>