<?php echo $this->headTitle('Competition');?>
<?php if (!is_null($this->form) && $this->form instanceof \Zend\Form\Form ):?>
    <?php
    $this->form->prepare();
    $this->form->setAttribute('action', $this->url('admin-competitions', array('action' => 'edit', 'id' => $this->id)));
    echo $this->form()->openTag($this->form);
    ?>
    <label class="control-label"><?=$this->translate($this->form->get('name')->getLabel())?></label>
    <?=$this->formElement($this->form->get('name'));?>
    <?php
    $logoElement = $this->form->get('logo');
    $image = is_string($logoElement->getValue()) ? $logoElement->getValue() : '';
    ?>
    <label class="control-label"><?=$this->translate($logoElement->getLabel())?></label>
    <div class="fileupload fileupload-<?=(!empty($image) ? 'exists' : 'new')?>" data-provides="fileupload">
        <div class="input-append">
            <div class="uneditable-input">
                <i class="icon-file fileupload-exists"></i>
                <span class="fileupload-preview"><?=(!empty($image) ? '<input type="hidden" name="' . $logoElement->getAttribute('name') . '[stored]" value="1"/><a target="_blank" href="' . $image . '">Open</a>' : '')?></span>
            </div>
                <span class="btn btn-file">
                    <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                    <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                    <input type="file" value="" class="default" name="<?=$logoElement->getAttribute('name')?>"/>
                </span>
            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn blue"><?=$this->translate($this->form->get('submit')->getValue());?></button>
        <button type="button" class="btn reset"><?php echo $this->translate('Reset');?></button>
    </div>
    <?php echo $this->form()->closeTag();?>
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        $('button.reset').click(function(e){
            e.preventDefault();
            this.form.reset();
        });
    });
</script>
<!-- END JAVASCRIPTS -->