<?php
$title = 'Competition';
$this->headTitle($title);
?>
<div>
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <h4><?=$this->translate('All Competitions')?></h4>
                    <div class="actions">
                    </div>
                </div>
                <div class="portlet-body">
                    <?php if (!empty($this->competitions)) : ?>
                        <table class="table table-striped table-bordered table-hover" id="competitions-table">
                            <thead>
                                <tr>
                                    <th><?=$this->translate('Name')?></th>
                                    <th><?=$this->translate('Logo')?></th>
                                    <th style="width: 150px"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->competitions as $competition) : ?>
                                    <tr class="odd gradeX<?=$competition->getLogoPath() == null ? ' new-item' : ''?>">
                                        <td><?=$competition->getDisplayName()?></td>
                                        <td>
                                            <?php if ($competition->getLogoPath() != null) : ?>
                                                <a href="<?=$competition->getLogoPath()?>" target="_blank">Open</a>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <a href="<?=$this->url('admin-competitions', array('action' => 'edit', 'id' => $competition->getId()))?>" class="btn mini blue">
                                                <i class="icon-edit"></i>
                                                <?=$this->translate('Edit')?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <?=$this->translate('There is no competitions created')?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('competitions per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ competitions')?>"};
        var oTable = $('#competitions-table').dataTable({
            "aoColumns": [null, null, {bSortable: false}],
            "aaSorting": [[0,"asc"]],
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
    });
</script>
<!-- END JAVASCRIPTS -->