<?php
    $title = $this->translate('Fixtures');
    $this->headTitle($title);
?>
<div role="main" class="two-column-section clearfix">
    <div class="first-column fixtures">
        <hgroup>
            <h1><?=$title;?></h1>
            <h2><?=$this->seasonRegion != null ? $this->seasonRegion->getDisplayName() : ''?></h2>
        </hgroup>
        <table>
            <?php
                $predictableCount = 0;
                foreach ($this->fixtures as $i => $fixture) :
                    if ($fixture['isLive'])
                        $predictable = false;
                    else
                        $predictable = $predictableCount++ < $this->maxAhead;
                    ?>
                <tr <?= $predictable ? 'class="flag-predictable"' : ''?>>
                    <td class="home-team">
                        <figure>
                            <div>
                                <img src="<?=$this->clubLogo($fixture['homeLogo']);?>"  alt="<?=$fixture['homeName']?>"/>
                            </div>
                            <figcaption>
                                <span><?=$fixture['homeName']?></span>
                                <abbr title="<?=$fixture['homeName']?>"><?=$fixture['homeShortName']?></abbr>
                                <time>
                                    <?php print $fixture['localStartTime']->format('D d M h.i a');?>
                                    <?php //print strftime('%a %e %b %I.%M %P', $fixture['localStartTime']->getTimestamp()); ?>
                                </time>
                            </figcaption>
                        </figure>
                    </td>
                    <td class="action-block">
                        <div>
                            <span><?=$fixture['competitionName']?></span>
                            <em><?=$this->translate('VS')?></em>
                            <?php if ($predictable) : ?>
                                <a href="<?=$this->url('predict', array('ahead' => $i > 0 ? $i : null))?>"><?=$this->translate('Predict the score')?></a>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td class="away-team">
                        <figure>
                            <div>
                                <img src="<?=$this->clubLogo($fixture['awayLogo']);?>" alt="<?=$fixture['awayName']?>"/>
                            </div>
                            <figcaption>
                                <span><?=$fixture['awayName']?></span>
                                <abbr title="<?=$fixture['awayName']?>"><?=$fixture['awayShortName']?></abbr>
                            </figcaption>
                        </figure>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <?php echo $this->partial('partials/right-column'); ?>
</div>