<div class="container-fluid">
<?php

$form = $this->form;
$params = array('action' => $this->action);
if ($this->action == 'edit') $params['id'] = $this->id;
$form->setAttribute('action', $this->url('admin-seasons', $params));
$form->prepare();

echo $this->form()->openTag($form);
$elements = $form->getElements();
$inputs = array($elements['displayName'], $elements['dates'], $elements['feederId']);
?>
    <div class="form">
        <div class="row-fluid">
<?php foreach ($inputs as $input) :
    $type = $input->getAttribute('type');
    $name = $input->getAttribute('name');
    ?>
<div class="control-group form-horizontal">
    <label class="control-label"><?=$this->translate($input->getLabel())?></label>
    <div class="controls">
        <div class="input-prepend">
            <?php if ($name == 'dates') : ?>
                <span class="add-on"><i class="icon-calendar"></i></span><input type="text" class="m-wrap m-ctrl-medium date-range" name="<?=$name?>" value="<?=$input->getValue()?>"/>
            <?php else: ?>
                <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$type?>" name="<?=$name?>" value="<?=$input->getValue()?>"/>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endforeach; ?>
</div>
<?php echo $this->renderRegionFieldsets($form->getFieldsets(), $this->action == 'add'); ?>
<div class="form-actions">
    <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
    <button type="button" class="btn">Cancel</button>
</div>
<?php echo $this->form()->closeTag();?>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.css" />
<link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/date.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var dates = $('input[name="dates"]');
        var currentDates = dates.val();
        var datePickerOptions = {format: 'dd/MM/yyyy'};
        if (currentDates == '')
            datePickerOptions.endDate = Date.today().add({days: 365});
        else {
            var startDate = $.trim(currentDates.split("-")[0]);
            var endDate = $.trim(currentDates.split("-")[1]);
            datePickerOptions.startDate = parseDate(startDate);
            datePickerOptions.endDate = parseDate(endDate);
        }
        if (jQuery().daterangepicker)
            $('.date-range').daterangepicker(datePickerOptions);
        $('.form-actions button[type=button]').click(function(e) {
            e.preventDefault();
            this.form.reset();
        });
        if (jQuery().wysihtml5) {
            if ($('.wysihtml5').size() > 0) {
                $('.wysihtml5').each(function(i, el) {
                    $(el).wysihtml5('bypassDefaults', {
                        "stylesheets": ["<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysiwyg-color.css"]
                    });
                });
            }
        }
    });
    function parseDate(date) {
        var dateParts = date.split("/");
        return new Date(dateParts[2], (dateParts[1] - 1), dateParts[0]);
    }
</script>
<!-- END JAVASCRIPTS -->