<div class="container-fluid">
<?php

$form = $this->form;
$params = array('action' => $this->action);
if ($this->action == 'edit') $params['id'] = $this->id;
$form->setAttribute('action', $this->url('admin-seasons', $params));
$form->prepare();

echo $this->form()->openTag($form);
$elements = $form->getElements();
$inputs = array($elements['displayName'], $elements['dates'], $elements['feederId']);
?>
    <div class="form">
        <div class="row-fluid">
<?php foreach ($inputs as $input) :
    $type = $input->getAttribute('type');
    $name = $input->getAttribute('name');
    $maxlength = $input->getAttribute('maxlength');
    ?>
<div class="control-group form-horizontal">
    <label class="control-label"><?=$this->translate($input->getLabel())?></label>
    <div class="controls">
        <div class="input-prepend">
            <?php if ($name == 'dates') : ?>
                <?php if ($this->editableDates) : ?>
                    <div id="form-date-range" class="date-range btn">
                        <i class="icon-calendar"></i>
                        &nbsp;<span></span>
                        <b class="caret"></b>
                    </div>
                    <input id="form-date-range-value" type="hidden" name="<?=$name?>" value="<?=$input->getValue()?>"/>
                <?php else : ?>
                    <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" disabled="disabled" type="text" value="<?=$input->getValue()?>"/>
                <?php endif; ?>
            <?php else: ?>
                <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$type?>" name="<?=$name?>" <?php echo (!empty($maxlength) ? 'maxlength="'.$maxlength.'"' : '');?> value="<?=$input->getValue()?>"/>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endforeach; ?>
</div>
<?php echo $this->renderRegionFieldsets($form->getFieldsets(), $this->action == 'add'); ?>
<div class="form-actions">
    <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
    <button type="button" class="btn">Cancel</button>
</div>
<?php echo $this->form()->closeTag();?>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.css" />
<link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/date.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/ckeditor/ckeditor.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    CKEDITOR.config.language = 'en';
    jQuery(document).ready(function() {
        initDatePicker();
        App.init(); // initlayout and core plugins
        $('.form-actions button[type=button]').click(function(e) {
            e.preventDefault();
            this.form.reset();
        });
    });
    function parseDate(date) {
        var dateParts = date.split("/");
        return new Date(dateParts[2], (dateParts[1] - 1), dateParts[0]);
    }

    function initDatePicker() {
        var dates = $('input[name="dates"]');
        if (dates.size() > 0) {
            var currentDates = dates.val();
            var datePickerOptions = {format: 'dd/MM/yyyy'};
            if (currentDates == '') {
                var fromDate = Date.today();
                var toDate = Date.today().add({days: 30});
//                var fromDate = Date.today().add({days: 1});
//                var toDate = Date.today().add({days: 31});
            } else {
                var fromDate = parseDate($.trim(currentDates.split("-")[0]));
                var toDate = parseDate($.trim(currentDates.split("-")[1]));
            }

            var tomorrow = Date.today().add({days: 1});

            $('.date-range').daterangepicker({
                    ranges: {
                        'Tomorrow': ['tomorrow', 'tomorrow'],
                        'Next 7 Days': ['tomorrow', Date.today().add({
                            days: 7
                        })],
                        'Next 30 Days': ['tomorrow', Date.today().add({
                            days: 30
                        })],
                        'This Month': [tomorrow.clone().moveToFirstDayOfMonth(), tomorrow.clone().moveToLastDayOfMonth()],
                        'Next Month': [tomorrow.clone().moveToFirstDayOfMonth().add({
                            months: 1
                        }).moveToFirstDayOfMonth(), Date.today().moveToFirstDayOfMonth().add({
                            months: 1
                        }).moveToLastDayOfMonth()]
                    },
                    opens: 'right',
                    format: 'dd/MM/yyyy',
                    separator: ' - ',
                    startDate: fromDate,
                    endDate: toDate,
                    minDate: Date.today(),
//                    minDate: tomorrow.clone(),
                    maxDate: tomorrow.clone().add({years: 2}),
                    locale: {
                        applyLabel: 'Submit',
                        fromLabel: 'From',
                        toLabel: 'To',
                        customRangeLabel: 'Custom Range',
                        daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                        monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                        firstDay: 1
                    },
                    showWeekNumbers: true,
                    buttonClasses: ['btn-danger']
                },

                function (start, end) {
                    $('#form-date-range span').text(start.toString('dd MMMM, yyyy') + ' - ' + end.toString('dd MMMM, yyyy'));
                    $('#form-date-range-value').val(start.toString('dd/MM/yyyy') + ' - ' + end.toString('dd/MM/yyyy'));
                });

            $('#form-date-range span').html(fromDate.toString('dd MMMM, yyyy') + " - " + toDate.toString('dd MMMM, yyyy'));
            $('#form-date-range-value').val(fromDate.toString('dd/MM/yyyy') + ' - ' + toDate.toString('dd/MM/yyyy'));

            if (!jQuery().datepicker || !jQuery().timepicker) {
                return;
            }
        }
    }
</script>
<!-- END JAVASCRIPTS -->