<?php
$title = 'Delete Season';
$this->headTitle($title);
?>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->season['displayName']); ?>' season?
</p>
<?php
$url = $this->url('admin-seasons', array(
    'action' => 'delete',
    'id'     => $this->season['id'],
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div class="form-actions">
        <input type="hidden" name="id" value="<?php echo (int) $this->season['id']; ?>" />
        <input type="submit" class="btn red" name="del" value="Yes" />
        <input type="submit" class="btn blue" name="del" value="No" />
    </div>
    <div>
    </div>
</form>