<?php
$title = 'Season';
$this->headTitle($title);
?>
<div>
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <h4><?=$this->translate('All Seasons')?></h4>
                    <div class="actions">
                        <a href="<?=$this->url('admin-seasons', array('action' => 'add'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Create')?></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php if (!empty($this->seasons)) : ?>
                        <table class="table table-striped table-bordered table-hover" id="seasons-table">
                            <thead>
                                <tr>
                                    <th><?=$this->translate('Name')?></th>
                                    <th><?=$this->translate('Start')?></th>
                                    <th><?=$this->translate('End')?></th>
                                    <th style="width: 150px"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->seasons as $season) : ?>
                                    <tr class="odd gradeX">
                                        <td><?=$season->getDisplayName()?></td>
                                        <td>
                                            <?=$season->getStartDate()->format("j F Y")?>
                                        </td>
                                        <td>
                                            <?=$season->getEndDate()->format("j F Y")?>
                                        </td>
                                        <td>
                                            <a href="<?=$this->url('admin-seasons', array('action' => 'edit', 'id' => $season->getId()))?>" class="btn mini blue">
                                                <i class="icon-edit"></i>
                                                <?=$this->translate('Edit')?>
                                            </a>
                                            <a href="<?=$this->url('admin-seasons', array('action' => 'delete', 'id' => $season->getId()))?>" class="btn mini red">
                                                <i class="icon-trash"></i>
                                                <?=$this->translate('Delete')?>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <?=$this->translate('There is no seasons created')?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('seasons per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ seasons')?>"};
        TableManaged.init(messages, [
            null,
            null,
            null,
            { "bSortable": false }
        ],
        [[ 2, "desc" ]]);
    });
</script>
<!-- END JAVASCRIPTS -->