<?php
    $title = $this->translate('League Tables');
    $this->headTitle($title . ' - ' . $this->seasonName);
?>
<link rel="stylesheet" href="/css/private-league.css">
<div role="main" class="two-column-section clearfix">
    <div class="first-column league-tables">
        <a href="" class="more-info private-league-button"><?=$this->translate('Create a private league')?></a>
        <h1><?=$title;?></h1>

        <div class="league">
            <header class="clearfix">
                <h2><?=$this->globalLeagueName?></h2>
            </header>

            <section>
                <div class="block">
                    <table>
                        <tr>
                            <th colspan="3">
                                <h3><?=$this->translate('Top 4')?></h3>
                            </th>
                            <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                        </tr>
                        <?php foreach ($this->globalTopUsers as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                            <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                <td class="position">
                                    <?php if ($isActive) : ?><span><?php endif;?>
                                    <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                    <?php if ($isActive) : ?></span><?php endif;?>
                                </td>
                                <td class="player"><?=$user['displayName']?>&nbsp;<a class="remove-player">X</a></td>
                                <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                <td class="points">
                                    <?php if ($isActive) : ?><span><?php endif;?>
                                    <?=$user['points'] !== null ? $user['points'] : '-'?>
                                    <?php if ($isActive) : ?></span><?php endif;?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <footer class="clearfix">
                    <a href="<?=$this->url('full-table', array('table' => $this->globalLeague->getId()))?>" class="more-info"><?=$this->translate('View full table')?></a>
                </footer>
            </section>

            <?php if ($this->regionalLeague !== null) : ?>
                <header class="clearfix">
                    <h2><?=$this->regionalLeagueName?></h2>
                </header>

                <section>
                    <div class="block">
                        <table>
                            <tr>
                                <th colspan="3">
                                    <h3><?=$this->translate('Top 4')?></h3>
                                </th>
                                <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                            </tr>
                            <?php foreach ($this->regionalTopUsers as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                                <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                    <td class="position">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                            <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                    <td class="player"><?=$user['displayName']?></td>
                                    <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                    <td class="points">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                            <?=$user['points'] !== null ? $user['points'] : '-'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                    <footer class="clearfix">
                        <a href="<?=$this->url('full-table', array('table' => $this->regionalLeague->getId()))?>" class="more-info"><?=$this->translate('View full table')?></a>
                    </footer>
                </section>
            <?php endif; ?>
            <?php foreach($this->temporalLeagues as $temporalLeague) : ?>
                <?php //if (!empty($temporalLeague['leagueUsers'])) : ?>
                    <header class="clearfix">
                        <h2><?=$temporalLeague['displayName']?></h2>
                    </header>
                    <section>
                        <div class="block">
                            <table>
                                <tr>
                                    <th colspan="3">
                                        <h3><?=$this->translate('Top 4')?></h3>
                                    </th>
                                    <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                                </tr>
                                <?php foreach ($temporalLeague['leagueUsers'] as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                                <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                    <td class="position">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                        <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                    <td class="player"><?=$user['displayName']?></td>
                                    <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                    <td class="points">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                        <?=$user['points'] !== null ? $user['points'] : '-'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                        <footer class="clearfix">
                            <a href="<?=$this->url('full-table', array('table' => $temporalLeague['id']))?>" class="more-info"><?=$this->translate('View full table')?></a>
                        </footer>
                    </section>
                <?php //endif; ?>
            <?php endforeach;?>
            <?php foreach($this->privateLeagues as $privateLeague) : ?>
                <?php //if (!empty($privateLeague['leagueUsers'])) : ?>
                    <header class="clearfix">
                        <h2><?=$privateLeague['displayName']?></h2>
                    </header>
                    <section>
                        <div class="block">
                            <table>
                                <tr>
                                    <th colspan="3">
                                        <h3><?=$this->translate('Top 4')?></h3>
                                    </th>
                                    <th><abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                                </tr>
                                <?php foreach ($privateLeague['leagueUsers'] as $user) : $isActive = $user['userId'] == $this->getCurrentUser()->getId(); ?>
                                <tr<?=$isActive ? ' class="your-table-position"' : ''?>>
                                    <td class="position">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                        <?=$user['place'] !== null ? $user['place'] : '&ndash;'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                    <td class="player"><?=$user['displayName']?></td>
                                    <td class="nationality"><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                    <td class="points">
                                        <?php if ($isActive) : ?><span><?php endif;?>
                                        <?=$user['points'] !== null ? $user['points'] : '-'?>
                                        <?php if ($isActive) : ?></span><?php endif;?>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                        <footer class="clearfix">
                            <a href="<?=$this->url('full-table', array('table' => $privateLeague['id']))?>" class="more-info"><?=$this->translate('View full table')?></a>
                        </footer>
                    </section>
                <?php //endif; ?>
            <?php endforeach;?>
        </div>
    </div>
    <?php echo $this->partial('partials/right-column'); ?>
</div>