<?php
    $title = $this->translate('Prizes');
    $this->headTitle($title );
?>
<div role="main" class="two-column-section clearfix">
    <div class="first-column prizes">
        <h1><?php echo $title;?></h1>
        <figure class="prizes-banner">
            <img src="<?php echo $this->grandPrize['prizeImage'];?>" alt="">
            <figcaption>
                <article>
                    <hgroup>
                        <h1><?php echo $this->grandPrize['prizeTitle'];?></h1>
                    </hgroup>
                    <p>
                        <?php echo $this->grandPrize['prizeDescription'];?>
                    </p>
<!--                    <h2>Visit Chelsea’s training ground</h2>-->
<!--                    <p>Win the chance to visit Chelsea’s exclusive Training Ground in Cobham to see the players in a training session, an amazing prize for any Chelsea fan, as well as a bounty of CFC merchandise and products from our sponsors.</p>-->
<!--                    <footer>-->
<!--                        <p>Winners announced <time>19 May 2013</time></p>-->
<!--                    </footer>-->
                </article>
            </figcaption>
        </figure>
    </div>
    <?php echo $this->partial('partials/right-column'); ?>
</div>