<?php
$title = $this->translate('Forgot Password?');
$this->headTitle($title);
?>
<?php echo $this->partial('partials/header');?>
<div role="main" class="registration-section">
    <h1><?php echo $this->escapeHtml($title);?></h1>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('forgot'));
    echo $this->form()->openTag($form);?>
    <?php $errors = $this->renderMessages();?>
    <?php if ($form->getInputFilter()->getMessages() || $errors):?>
        <div class="form-errors">
            <?php if (!empty($errors)):?>
                <p><?php echo $errors;?></p>
            <?php endif;?>
            <?php echo $this->formElementerrors($form->get('email'));?>
        </div>
    <?php endif;?>
    <section>
        <div>
            <?php  echo $this->formLabel($form->get('email'));?>
            <?php  echo $this->formElement($form->get('email'));?>
        </div>

    </section>
    <section class="buttons-block signIn-buttons-block clearfix">
        <div>
            <button type="submit"><?php echo $this->translate('Submit');?></button>
        </div>
    </section>
  <?php
    echo $this->formHidden($form->get('csrf'));
    echo $this->form()->closeTag();
?>
<div>
<script src="/js/forgot.js"></script>
<?php echo $this->partial('partials/footer');?>