<?php
$title = $this->translate('Sign In');
$this->headTitle($title);
?>
<?php echo $this->partial('partials/header');?>
<div role="main">
    <div class="one-column registration sign-in">
        <h1><?php echo $this->escapeHtml($title);?></h1>
        <aside class="connect-facebook clearfix">
            <div>
                <h2><?php echo $this->translate('Connect your account for a one click login');?></h2>
                <p><?=$this->translate(\Application\Model\Helpers\MessagesConstants::INFO_FACEBOOK_CONNECT_BUTTON)?></p>
            </div>
            <?php echo $this->renderFacebookButton($this->translate('Login with Facebook'));?>
        </aside>

        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('login', array('action' => 'authenticate'))); ?>
        <?php    echo $this->form()->openTag($form);?>
        <?php echo $this->partial('partials/flash-messages');?>
        <section>
            <div>
                <h2><?php echo $this->translate('Enter Your Credentials');?></h2>
            </div>
            <div>
                <?php  echo $this->formLabel($form->get('email'));?>
                <?php  echo $this->formElement($form->get('email'));?>
            </div>
            <div>
                <?php  echo $this->formLabel($form->get('password'));?>
                <?php  echo $this->formElement($form->get('password'));?>
            </div>
            <div class="keeplogin">
                <label>&nbsp;</label>
                <label for="loginkeeping"><input id="loginkeeping" type="checkbox" name="rememberme" value="1"><?php echo $this->translate('Remember me');?></label>
            </div>
        </section>
        <section class="buttons-block clearfix">
            <div>
                <button type="submit"><?php echo $this->translate('Sign In');?></button>
            </div>
            <p>
                <a href="<?php echo $this->url('forgot');?>"><?php echo $this->translate('Forgotten password');?></a>
            </p>
            <p>
                <?php echo $this->translate('Not a member?');?>
                <a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register');?></a>
            </p>
        </section>
       <?php echo $this->form()->closeTag();?>
    </div>
</div>
<script src="/js/login.js"></script>
<?php echo $this->partial('partials/footer');?>
