<?php
$title = $this->translate('Reset Password');
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<?php $this->renderMessages();?>
<?php
if ($this->isValid){
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '');
    echo $this->formElementerrors($form->get('password'));
    echo $this->formElementerrors($form->get('confirm_password'));
    echo $this->form()->openTag($form);
    echo $this->formLabel($form->get('password'));
    echo $this->formElement($form->get('password'));
    echo $this->formLabel($form->get('confirm_password'));
    echo $this->formElement($form->get('confirm_password'));
    echo $this->formHidden($form->get('csrf'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
}
if ($this->displayLinkToResetPage):?>
   <a href="<?php echo $this->url('forgot')?>"><?php echo $this->translate('Reset Password Page');?></a>
<?php endif;?>


