<?php
    $title = $this->translate('Info Page');
    $this->headTitle($title);
?>
<div role="main">
    <div class="one-column message information">
        <h1><?=$this->translate(!empty($this->title) ? $this->title : 'Info Page')?></h1>
        <article class="user-content">
            <h2><?=$this->translate($this->content)?></h2>
<!--            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla metus ligula, facilisis id scelerisque in, eleifend ut elit. Aenean a facilisis augue <a href="">lorem ipsum</a>.</p>-->
<!--            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, commodi velit deserunt dolorem labore quae est odit atque voluptate quasi in rem voluptates minima nesciunt iure quas ipsum autem explicabo.</p>-->
<!--            <ul>-->
<!--                <li>Lorem ipsum dolor sit amet, consectetur adipisicing e</li>-->
<!--                <li>Lorem ipsum dolor</li>-->
<!--                <li>Lorem ipsum dolor sit amet, consectetur</li>-->
<!--                <li>Lorem ipsum dolor</li>-->
<!--                <li>Lorem ipsum dolor</li>-->
<!--            </ul>-->
        </article>
    </div>
</div>