<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9 ie8"> <![endif]-->
<!--[if IE 9]>         <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?php $this->headTitle($this->getConstant('club_name'))->setSeparator(' - ');?>
    <?php echo $this->headTitle() ?>
    <meta property="og:title" content="<?php echo $this->headTitle()->renderTitle() ?>">
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . $this->getConstant('favicon_path') . "?" . rand(0, 1)))?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <link rel="stylesheet" href="/css/normalize.min.css">
    <link rel="stylesheet" href="/css/jquery.idealforms.min.css">

    <link rel="stylesheet" href="/css/styles.css">
    <link rel="stylesheet" href="/css/styles-v2.1.css">

    <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="/css/ie.css">
    <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
    <script src="/js/vendor/excanvas.min.js"></script>
    <![endif]-->

    <!-- to exclude from master branch -->
    <link rel="stylesheet" href="/css/chelsea-styles.css">
    <!-- exclusion end -->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
    <script src="/js/jquery.cookie.js"></script>
    <script src="/js/vendor/picturefill.js"></script>
    <script src="/js/vendor/jquery.idealforms.min.js"></script>
    <script src="/js/login-popup.js"></script>
    <script src="/js/main.js"></script>
</head>
<body class="inner-page" style="background: #01002a">
<div id="fb-root"></div>
<script src="//connect.facebook.net/en_US/all.js"></script>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
<div id="wrapper">
    <header role="banner">
        <div class="head">

        </div>
        <div  class="banner">
            <figure>
                <div data-alt="" data-picture="">
                    <div data-src="/img/banner-innerpage-480.jpg"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/banner-innerpage-480.jpg"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/banner-innerpage-600.jpg"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/banner-innerpage-1024.jpg"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/banner-innerpage-1280.jpg"></div>
                    <noscript><img src="/img/banner-innerpage-1024.jpg" alt="" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/banner-innerpage-1280.jpg"></div>
                    <![endif]-->
                </div>
            </figure>
        </div>
    </header>
<div role="main">
    <div class="one-column errors-page">
        <h1>Server Error</h1>
        <div class="clearfix">
            <article class="error">
                <h2>Message:</h2>
                <p>Sorry, you can't see the page. We are aware of it and doing all our best to fix the problem.</p>
                <figure>
                    <div>5<img src="/img/ball.png" alt=""><img src="/img/ball.png" alt=""></div>
                </figure>
            </article>
        </div>
    </div>
</div>
    <footer role="contentinfo" class="clearfix" style="background: #021228;">
        <article>
            <figure>
                </figure>
            <h2>Stay up to date with Chelsea Football Club</h2>
            <p>With breaking news, match updates,  competitions and <br>exclusive interviews from the first team.</p>
            </article>
        <div>
            <p><a href="http://www.truefan.tv" target="_blank"><img src="/img/truefan.png" alt="TRUEFAN">MADE BY TRUEFAN</a></p>
        </div>
    </footer>
</div>
</body>
</html>