<div class="cookie-dialog" style="display: none;">
    <section>
        <p><?=$this->translate(sprintf("We use cookies to ensure that we gave you the best experience on our website. If you continue without changing your settings, we'll assume that you are happy to receive all cookies on the Score Predictor website. Learn more about our %scookie usage%s and how to change your cookie settings.", '<a href="'.$this->url("cookies").'">', '</a>'))?></p>
        <button><?=$this->translate('Accept and close')?></button>
    </section>
</div>