<footer role="contentinfo" class="clearfix" style="background: <?=$this->settingsHelper()->getFooterColor()?>;">
    <article>
        <figure>
            <?php echo $this->footerImage(); ?>
        </figure>
        <h2><?=$this->translate('Stay up to date with FC Barcelona')?></h2>
        <p><?=$this->translate('See behind the scenes, match updates <br>and exclusive content')?></p>
        <?php echo $this->footerSocials(); ?>
    </article>
    <div>
        <nav class="clearfix">
            <ul>
                <li>
                    <a href="<?php echo $this->url('terms');?>"><?=$this->translate('Terms')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('contact');?>"><?=$this->translate('Contact us')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('privacy')?>"><?=$this->translate('Privacy')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('help');?>"><?=$this->translate('Help & Support')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->settingsHelper()->get('main-site-link')?>"><?=$this->translate('Visit our main site')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cookies');?>"><?=$this->translate('Cookies policy')?></a>
                </li>
                <li>
                    <p>&copy; FC Barcelona 2012</p>
                </li>
            </ul>
        </nav>
        <p>v.2.0 Produced by Neoco</p>
    </div>
</footer>
</div>
</body>
</html>