<footer role="contentinfo" class="clearfix" style="background: <?=$this->settingsHelper()->getFooterColor()?>;">
    <article>
        <figure>
            <?php echo $this->footerImage(); ?>
        </figure>
        <h2><?=$this->translate('Stay up to date with Truefan United')?></h2>
        <p><?=$this->translate('See behind the scenes, match updates <br>and exclusive content')?></p>
        <?php echo $this->footerSocials(); ?>
    </article>
    <div>
        <nav class="clearfix">
            <ul>
                <li>
                    <a href="<?php echo $this->url('terms');?>"><?=$this->translate('Terms')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('contact');?>"><?=$this->translate('Contact us')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('privacy')?>"><?=$this->translate('Privacy')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('help');?>"><?=$this->translate('Help & Support')?></a>
                </li>
                <li>
                    <a target="_blank" href="<?php echo $this->settingsHelper()->get(\Application\Manager\SettingsManager::MAIN_SITE_LINK)?>"><?=$this->translate('Visit our main site')?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url('cookies');?>"><?=$this->translate('Cookies policy')?></a>
                </li>
            </ul>
        </nav>
        <p><a href="http://www.truefan.tv" target="_blank"><img src="/img/truefan.png" alt="TRUEFAN" ><?php echo $this->translate('MADE BY');?> TRUEFAN</a></p>
    </div>
</footer>
</div>
<?php echo $this->partial('partials/google-analytics');?>
</body>
</html>