<style type="text/css">
    .social-link {
        margin: 0 0 0.5em;
        padding: 0 0 0 32px;
        height: 18px;
        color: #fff;
        line-height: 28px;
    }
</style>
<footer role="contentinfo" class="clearfix" style="background: #350616;">
    <article>
        <?php echo $this->footerImage(); ?>
        <h2>Stay up to date with FC Barcelona</h2>
        <p>See behind the scenes, match updates <br>and exclusive content</p>
        <?php echo $this->footerSocials(); ?>
    </article>
    <div>
        <nav class="clearfix">
            <ul>
                <li>
                    <a href="">Terms</a>
                </li>
                <li>
                    <a href="">Contact us</a>
                </li>
                <li>
                    <a href="">Privacy</a>
                </li>
                <li>
                    <a href="">Visit our main site</a>
                </li>
                <li>
                    <a href="">Cookies policy</a>
                </li>
                <li>
                    <p>&copy; FC Barcelona 2012</p>
                </li>
            </ul>
        </nav>
        <p>v.2.0 Produced by Neoco</p>
    </div>
</footer>
</div>
</body>
</html>
