<div id="fb-root"></div>
<script src="//connect.facebook.net/en_US/all.js"></script>
<script>window.FB || document.write('<script src="/js/vendor/facebook.js"><\/script>')</script>
<script type="text/javascript">
   FB.init({
       appId:'<?php echo $this->getConstant('facebook_api_key');?>', // App ID
       frictionlessRequests:true
   });
    function inviteFriends() {
            FB.ui({method: 'apprequests',
                message: '<?php echo $this->translate('Invite friends to Score Predictor');?>'
            });
    }
</script>
