<!--HEADER STARTS-->
<section class="match-banner">
    <div class="clearfix">
        <img src="<?php echo (!empty($this->report['headerImage']) ? $this->report['headerImage'] : $this->getConstant('default_post_match_report_header_image'));?>" alt="">
        <article>
            <h1><?php echo $this->escapeHtml(!empty($this->report['title']) ? $this->report['title'] : $this->getConstant('default_post_match_report_title'));?></h1>
            <p><?php echo (!empty($this->report['intro']) ? $this->report['intro'] : $this->getConstant('default_post_match_report_intro'));?></p>
            <footer class="clearfix">
                <h3><?php echo $this->translate('Share this');?></h3>
                <ul class="social-links">
                    <li><a href="">like</a></li>
                    <li><a href="">tweet</a></li>
                    <li><a href="">Pin it</a></li>
                </ul>
            </footer>
        </article>
    </div>
</section>
<!--HEADER ENDS-->
<section class="grid-layout">
    <div id="container" class="clearfix masonry centered fluid">
        <!--MOST POPULAR SCORE STARTS-->
        <?php if (!empty($this->report['topScore']['home_team_score']) && !empty($this->report['topScore']['away_team_score'])):?>
            <div class="item col1 summary">
                <section>
                    <p>
                        <strong> <?php echo (int)$this->report['topScore']['home_team_score'];?>-<?php echo (int)$this->report['topScore']['away_team_score'];?></strong>
                        <?php echo $this->translate('Was the most popular prediction this match');?>
                    </p>
                </section>
            </div>
        <?php endif;?>
        <!--MOST POPULAR SCORE ENDS-->
        <!--CORRECT SCORERS BLOCK STARTS-->
            <?php if (!empty($this->report['correctScorers'])):?>
            <?php $correctScorers = $this->report['correctScorers'];?>
            <div class="item col2 top-predicted-scorers">
                <section class="clearfix">
                    <img src="<?php echo !empty($correctScorers['backgroundImage']) ? $correctScorers['backgroundImage'] : $this->getConstant('default_player_background');?>" alt="" class="bg">
                    <img src="<?php echo !empty($correctScorers['avatarImage']) ? $correctScorers['avatarImage'] : $this->getConstant('default_player_avatar');?>" alt="Top scorer" class="player"/>
                    <div>
                        <h1><?php echo $this->translate('Correct scorer predictions');?></h1>
                        <?php
                        $classes = array('big', 'middle', 'small');
                        $index = 0;
                        ?>
                        <ol class="clearfix">
                            <?php foreach($correctScorers['scorers'] as $name => $percentage):?>
                            <li class="<?php echo (isset($classes[$index]) ? $classes[$index] : 'small');?>">
                                <strong><?php echo $percentage;?><sup>%</sup></strong>
                                <span><?php echo $name;?></span>
                            </li>
                            <?php $index++;?>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </section>
            </div>
            <?php endif;?>
        <!--CORRECT SCORERS BLOCK ENDS-->
        <!--CORRECT SCORE BLOCK STARTS-->
        <?php if (isset($this->report['correctScore'])):?>
            <div class="item col1 summary left">
                <section>
                    <figure class="clearfix">
                        <div id="community-predicted-results"></div>
                        <figcaption>Community correctly predicted the results</figcaption>
                    </figure>
                </section>
            </div>
            <script type="text/javascript">
                var communityPredictedData = [
                    {color : '#144a9b', data: <?php echo $this->report['correctScore'];?>, label:  '<?php echo $this->report['correctScore'] . '%';?>'},
                    {color : '#90b1d4', data: <?php echo (100 - $this->report['correctScore']);?>, label: ''}

                ];
            </script>
        <?php endif;?>
        <!--CORRECT SCORE BLOCK ENDS-->
        <!--REGIONAL LEAGUE MOVEMENT STARTS-->
        <?php if (!empty($this->report['leaguesMovement'])):?>
            <?php $leaguesMovement = $this->report['leaguesMovement'];?>
            <?php if (!empty($leaguesMovement['global'])):?>
                  <?php echo $this->renderUserLeagueMovement($leaguesMovement['global']);?>
            <?php endif;?>
            <?php if (!empty($leaguesMovement['regional'])):?>
                <?php echo $this->renderUserLeagueMovement($leaguesMovement['regional']);?>
                <?php endif;?>
            <?php endif;?>
        <!--REGIONAL LEAGUE MOVEMENT ENDS-->
    </div>
</section>
<script src="/js/vendor/jquery.masonry.min.js"></script>
<script src="/js/vendor/jquery.flot.js"></script>
<script src="/js/vendor/jquery.flot.pie.js"></script>
<script src="/js/post-match-report.js"></script>