<!--HEADER STARTS-->
<section class="match-banner">
    <div class="clearfix">
        <img src="<?php echo (!empty($this->report['headerImage']) ? $this->report['headerImage'] : $this->getConstant('default_post_match_report_header_image'));?>" alt="">
        <article>
            <h1><?php echo $this->escapeHtml(!empty($this->report['title']) ? $this->report['title'] : $this->getConstant('default_post_match_report_title'));?></h1>
            <p><?php echo (!empty($this->report['intro']) ? $this->report['intro'] : $this->getConstant('default_post_match_report_intro'));?></p>
            <footer class="clearfix">
                <h3><?php echo $this->translate('Share this');?></h3>
                <ul class="social-links">
                    <li><a href="">like</a></li>
                    <li><a href="">tweet</a></li>
                    <li><a href="">Pin it</a></li>
                </ul>
            </footer>
        </article>
    </div>
</section>
<!--HEADER ENDS-->
<section class="grid-layout">
</section>