<!--HEADER STARTS-->
<section class="match-banner">
    <div class="clearfix">
        <?php if (!empty($this->report['headerImage'])): ?>
            <img src="<?php echo $this->report['headerImage'];?>" alt="">
        <?php endif; ?>
        <article>
            <h1><?php echo $this->escapeHtml($this->report['title']);?></h1>
            <p><?php echo $this->report['intro'];?></p>
            <footer class="clearfix">
                <ul class="social-links">
                    <li>
                        <script type="text/javascript" src="/js/facebook.js"></script>
                        <a summary="<?=$this->facebookShareCopy?>" href="<?=$this->url('match', array('code' => $this->code), array('force_canonical' => true))?>" class="like">Like</a>
                    </li>
                    <li>
                        <a href="https://twitter.com/share" class="twitter-share-button" data-text="<?=$this->twitterShareCopy?>" data-url="<?=$this->url('match', array('code' => $this->code), array('force_canonical' => true))?>" data-count="none">Tweet</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </li>
                    <!--                        <li><a href="">Pin it</a></li>-->
                </ul>
            </footer>
        </article>
    </div>
</section>
<!--HEADER ENDS-->
<section class="grid-layout">
    <div id="container" class="clearfix masonry centered fluid">
        <!--MOST POPULAR SCORE STARTS-->
        <?php if (!empty($this->report['topScore']['home_team_score']) && !empty($this->report['topScore']['away_team_score'])):?>
            <div class="item col1 summary">
                <section>
                    <p>
                        <strong> <?php echo (int)$this->report['topScore']['home_team_score'];?>-<?php echo (int)$this->report['topScore']['away_team_score'];?></strong>
                        <?php echo $this->translate('Was the most popular prediction this match');?>
                    </p>
                </section>
            </div>
        <?php endif;?>
        <!--MOST POPULAR SCORE ENDS-->
        <!--CORRECT SCORERS BLOCK STARTS-->
            <?php if (!empty($this->report['correctScorers'])):?>
            <?php $correctScorers = $this->report['correctScorers'];?>
            <div class="item col2 top-predicted-scorers">
                <section class="clearfix">
                    <img src="<?php echo !empty($correctScorers['backgroundImage']) ? $correctScorers['backgroundImage'] : $this->getConstant('default_player_background');?>" alt="" class="bg">
                    <div>
                        <h1><?php echo $this->translate('Correct scorer predictions');?></h1>
                        <?php
                        $classes = array('big', 'middle', 'small');
                        $index = 0;
                        ?>
                        <ol class="clearfix">
                            <?php foreach($correctScorers['scorers'] as $scorer):?>
                            <li class="<?php echo (isset($classes[$index]) ? $classes[$index] : 'small');?>">
                                <strong><?php echo $scorer['percentage'];?><sup>%</sup></strong>
                                <span><?php echo $scorer['playerName'];?></span>
                            </li>
                            <?php $index++;?>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </section>
            </div>
            <?php endif;?>
        <!--CORRECT SCORERS BLOCK ENDS-->
        <!--CORRECT SCORE BLOCK STARTS-->
        <?php if (isset($this->report['correctResult'])):?>
            <div class="item col1 summary left">
                <section>
                    <figure class="clearfix">
                        <div id="community-predicted-results"></div>
                        <figcaption><?php echo $this->translate('Community correctly predicted the results');?></figcaption>
                    </figure>
                </section>
            </div>
            <script type="text/javascript">
                var communityPredictedData = [
                    {color : '#144a9b', data: <?php echo (!empty($this->report['correctResult']) ? $this->report['correctResult'] : 0.00001);?>, label:  '<?php echo (int)$this->report['correctResult'] . '%';?>'},
                    {color : '#90b1d4', data: <?php echo (100 - $this->report['correctResult']);?>, label: ''}

                ];
            </script>
        <?php endif;?>
        <!--CORRECT SCORE BLOCK ENDS-->
        <!--REGIONAL LEAGUE MOVEMENT STARTS-->
        <?php if (!empty($this->report['leaguesMovement'])):?>
            <?php $leaguesMovement = $this->report['leaguesMovement'];?>
            <?php if (!empty($leaguesMovement['global'])):?>
                  <?php echo $this->renderUserLeagueMovement($leaguesMovement['global']);?>
            <?php endif;?>
            <?php if (/*todo remove*/false && !empty($leaguesMovement['regional'])):?>
                <?php echo $this->renderUserLeagueMovement($leaguesMovement['regional']);?>
                <?php endif;?>
            <?php endif;?>
        <!--REGIONAL LEAGUE MOVEMENT ENDS-->
    </div>
</section>
<script src="/js/vendor/jquery.masonry.min.js"></script>
<script src="/js/vendor/jquery.flot.js"></script>
<script src="/js/vendor/jquery.flot.pie.js"></script>
<script src="/js/post-match-report.js"></script>