<?php echo $this->partial('partials/invite-friends');?>
<aside role="complementary" class="second-column">
    <ul class="social-links clearfix">
        <li>&nbsp;</li>
    </ul>

    <?php if ($this->getCurrentUser() != null) : ?>
        <div class="wrap">

            <section class="user-profile clearfix" itemtype="http://schema.org/Person" itemscope="">
                <img src="<?=$this->getUserAvatar($this->getCurrentUser()->getAvatar()->getMediumImagePath(), $this->getCurrentUser()->getFacebookId())?>" itemprop="photo" title="<?=$this->getCurrentUser()->getDisplayName()?>" alt="<?=$this->getCurrentUser()->getDisplayName()?>" >
                <img src="<?=$this->getCurrentUser()->getCountry()->getFlagImage()?>" itemprop="nationality" alt="<?=$this->getCurrentUser()->getCountry()->getName()?>" >
                <h1 itemprop="name"><?=$this->getCurrentUser()->getDisplayName()?></h1>
            </section>

            <?php if ($this->getCurrentUser()->getIsActive() && $this->getLeagueStats()->getCurrentSeason() !== null) : ?>
                <section class="block total-points">
                    <table>
                        <thead>
                        <tr><th class="pts"><?=$this->translate('Total')?> <abbr title="Points"><?=$this->translate('pts')?></abbr></th>
                            <th class="acy"><abbr title="Accuracy"><?=$this->translate('Acy')?></abbr></th>
                        </tr></thead>
                        <tbody>
                        <tr>
                            <td class="pts"><?=$this->getLeagueStats()->getGlobalPoints()?></td>
                            <td class="acy">+<?=$this->getLeagueStats()->getGlobalAccuracy()?></td>
                        </tr>
                        </tbody>
                    </table>
                </section>

                <?php
                    $overallLeagueUsers = $this->getLeagueStats()->getOverallLeagueUsers();
                    if (!empty($overallLeagueUsers)) :
                ?>
                    <section class="league">
                        <h1><?=$this->translate('Overall League')?></h1>
                        <div class="block">
                            <table>
                                <tbody>
                                <?php foreach($overallLeagueUsers as $leagueUser) : ?>
                                    <tr>
                                        <th>
                                            <?=$leagueUser['type'] == \Application\Model\Entities\League::GLOBAL_TYPE ? 'Global' : 'Local'?>
                                        </th>
                                        <td class="movement">
                                            <?php if ($leagueUser['previousPlace'] != null) : ?>
                                                <?php if ($leagueUser['previousPlace'] > $leagueUser['place']) : ?>
                                                    <img title="Moved Up" alt="Moved Up" src="/img/up.png" class="up">
                                                <?php elseif ($leagueUser['previousPlace'] < $leagueUser['place']) : ?>
                                                    <img title="Moved Down" alt="Moved Down" src="/img/down.png" class="down">
                                                <?php endif;?>
                                            <?php endif;?>
                                        </td>
                                        <td class="score"><?=$leagueUser['place']?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </section>
                <?php endif;?>

                <?php
                    $temporalLeagueUsers = $this->getLeagueStats()->getTemporalLeagueUsers();
                    if (!empty($temporalLeagueUsers)) :
                ?>
                    <section class="league">
                        <h1><?=$this->translate('Temporal Leagues')?></h1>
                        <div class="block">
                            <table>
                                <tbody>
                                <?php foreach($temporalLeagueUsers as $leagueUser) : ?>
                                    <tr>
                                        <th>
                                            <?=$leagueUser['displayName']?>
                                        </th>
                                        <td class="movement">
                                            <?php if ($leagueUser['previousPlace'] != null) : ?>
                                                <?php if ($leagueUser['previousPlace'] < $leagueUser['place']) : ?>
                                                    <img alt="Moved Up" src="/img/up.png" class="up">
                                                <?php elseif ($leagueUser['previousPlace'] > $leagueUser['place']) : ?>
                                                    <img alt="Moved Down" src="/img/down.png" class="down">
                                                <?php endif;?>
                                            <?php endif;?>
                                        </td>
                                        <td class="score"><?=$leagueUser['place'] != null ? $leagueUser['place'] : '-'?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </section>
                <?php endif; ?>

            <?php endif; ?>
            <?php if ($this->getCurrentUser()->getIsActive() && $this->getLeagueStats()->getCurrentSeason() !== null) : ?>
                <p class="full"><a href="<?=$this->url('tables')?>"><?=$this->translate('View full league tables')?></a></p>
            <?php endif;?>
        </div>
    <?php endif; ?>

    <?php if ($this->getCurrentUser() == null) : ?>
        <div class="login">
            <section>
                <?php $content = $this->getContent(); ?>
                <p><?=$content['headlineCopy']?></p>
                <a href="<?=$this->url("registration")?>" class="cta"><?=$content['registerButtonCopy']?></a>
            </section>
        </div>
    <?php endif; ?>

<!--    <div class="facebook-invite">-->
<!--        <h1>--><?//=$this->translate('Play against your mates')?><!--</h1>-->
<!--        <p>--><?//=$this->translate("Create your own social league against your Facebook friends to find out who's top of the league")?><!--</p>-->
<!--        <a href="javascript:void(0);" onclick="inviteFriends();" class="facebook">--><?php //echo $this->translate('+ Invite your friends');?><!--</a>-->
<!--    </div>-->
</aside>