<?php
$title = 'Active VS Inactive Users';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span3 responsive" data-tablet="span6" data-desktop="span3">
        <div class="dashboard-stat blue">
            <div class="visual">
                <i class="icon-unlock"></i>
            </div>
            <div class="details">
                <div class="number">
                    <?=$this->data['active']?>
                </div>
                <div class="desc">
                    Active
                </div>
            </div>
        </div>
    </div>
    <div class="span3 responsive" data-tablet="span6  fix-offset" data-desktop="span3">
        <div class="dashboard-stat purple">
            <div class="visual">
                <i class="icon-lock"></i>
            </div>
            <div class="details">
                <div class="number">
                    <?=$this->data['inactive']?>
                </div>
                <div class="desc">
                    Inactive
                </div>
            </div>
        </div>
    </div>
</div>
<a href="<?=$this->url('admin-stats-users', array('action' => 'exportActiveVsInactive'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Active vs inactive users')?></a>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->