<?php
$title = 'Number Of Incomplete Registrations';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span3 responsive" data-tablet="span6" data-desktop="span3">
        <div class="dashboard-stat blue">
            <div class="visual">
                <i class="icon-lock"></i>
            </div>
            <div class="details">
                <div class="number"><?=$this->data['incomplete']?></div>
                <div class="desc">Incomplete</div>
            </div>
        </div>
    </div>
</div>
<a href="<?=$this->url('admin-stats-users', array('action' => 'exportIncompleteRegistrations'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Number of incomplete registrations')?></a>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->