<?php
$title = 'Lowest Predicted Match';
$this->headTitle($title);
?>
<div class="row-fluid">
    <?php foreach ($this->data as $match) : ?>
    <div class="span6">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$match['home_team'];?> VS <?=$match['away_team'];?></h4>
            </div>
            <div class="portlet-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Start Time</td>
                            <td><?=$match['start_time']->format('j F Y');?></td>
                        </tr>
                        <tr>
                            <td>League</td>
                            <td><?=$match['competition'];?></td>
                        </tr>
                        <tr>
                            <td>Home Team</td>
                            <td><?=$match['home_team'];?></td>
                        </tr>
                        <tr>
                            <td>Away Team</td>
                            <td><?=$match['away_team'];?></td>
                        </tr>
                        <tr>
                            <td>Predictions</td>
                            <td><?=$match['predictions'];?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
    <?php endforeach; ?>
</div>
<a href="<?=$this->url('admin-stats-users', array('action' => 'exportLowestPredictedMatch'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Lowest predicted match')?></a>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->