<?php
$title = 'Registrations Per Week';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span6">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4>Registrations Per Week</h4>
            </div>
            <div class="portlet-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>First Week Day</th>
                        <th>Last Week Day</th>
                        <th>Registrations</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->data as $week) : ?>
                        <tr>
                            <td><?=$week['first_week_day']->format('j F Y');?></td>
                            <td><?=$week['last_week_day']->format('j F Y');?></td>
                            <td><?=$week['registrations'];?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>
<a href="<?=$this->url('admin-stats-users', array('action' => 'exportRegistrationsPerWeek'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Registrations overtime per week')?></a>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->