<?php
$title = 'Usres By Region';
$this->headTitle($title);
?>
<div class="row-fluid">
    <div class="span6">
        <!-- BEGIN SAMPLE TABLE PORTLET-->
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4>Usres By Region</h4>
            </div>
            <div class="portlet-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Region</th>
                        <th>Users Count</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->data as $regionData) : ?>
                        <tr>
                            <td><?=$regionData['region'];?></td>
                            <td><?=$regionData['users'];?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END SAMPLE TABLE PORTLET-->
    </div>
</div>
<a href="<?=$this->url('admin-stats-users', array('action' => 'exportUsersByRegion'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Users by region')?></a>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->