<?php
$title = 'Users';
$this->headTitle($title);
?>
<div>
    <div class="row-fluid">
        <ul class="unstyled span10 vertical-margined">
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportFacebookVsDirect'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Registered users - Facebook vs direct')?></a>
            </li>
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportRegistrationsPerWeek'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Registrations overtime per week')?></a>
            </li>
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportActiveVsInactive'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Active vs inactive users')?></a>
            </li>
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportIncompleteRegistrations'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Number of incomplete registrations')?></a>
            </li>
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportAccountDeletions'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Facebook vs email account deletions')?></a>
            </li>
            <li>
                <a href="<?=$this->url('admin-stats-users', array('action' => 'exportUsersByRegion'))?>" class="btn green"><i class="icon-download-alt"></i> <?=$this->translate('Users by region')?></a>
            </li>
        </ul>
    </div>
</div>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->