<?php
    $title = $this->translate($this->title);
    $this->headTitle($title );
?>
<div role="main" class="<?php echo ((!$this->getCurrentUser()) ? 'one-column-section' : 'two-column-section')?> clearfix">
    <div class="first-column privacy">
        <h1><?php echo $title;?></h1>
        <div class="user-content privacy-content">
            <?php echo $this->content;?>
        </div>
    </div>
    <?php if ($this->getCurrentUser()):?>
        <?php echo $this->partial('partials/right-column');?>
    <?php endif;?>
</div>

