<?php $this->headTitle($this->translate('Help & Support'));?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('help'));
?>
<?php $errors = $this->renderMessages();?>
<?php if ($errors):?>
<div class="form-errors">
    <?php if (!empty($errors)):?>
    <p><?php echo $errors;?></p>
    <?php endif;?>
</div>
<?php endif;?>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formLabel($form->get('name'));?>
<?php echo $this->formElement($form->get('name'));?>
<?php echo $this->formLabel($form->get('email'));?>
<?php echo $this->formElement($form->get('email'));?>
<?php echo $this->formLabel($form->get('query'));?>
<?php echo $this->formElement($form->get('query'));?>
<?php echo $this->formElement($form->get('submit'));?>
<?php echo $this->form()->closeTag();?>