
<?php
$title = $this->translate($this->title);
$this->headTitle($title );
?>
<div role="main" class="<?php echo ((!$this->getCurrentUser()) ? 'one-column-section' : 'two-column-section')?> clearfix">
    <div class="first-column registration support">
        <h1><?php echo $title;?></h1>
        <p class="intro"><?php echo $this->translate('We would like to hear from you - any comments or suggestions or any questions you may have. Just use the form below.');?></p>
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('help'));
        ?>
        <?php echo $this->partial('partials/flash-messages');?>
        <?php echo $this->form()->openTag($form);?>
        <section>
            <div>
                <h2><?php echo $this->translate('Enter Your Contact Info and Message');?></h2>
            </div>
            <div>
                <?php echo $this->formLabel($form->get('name'));?>
                <?php echo $this->formElement($form->get('name'));?>
            </div>
            <div>
                <?php echo $this->formLabel($form->get('email'));?>
                <?php echo $this->formElement($form->get('email'));?>
            </div>
            <div>
                <?php echo $this->formLabel($form->get('query'));?>
                <?php echo $this->formElement($form->get('query'));?>
            </div>
        </section>
        <section class="buttons-block clearfix">
            <div>
                <button type="submit" name="submit"><?php echo $this->translate('Send');?></button>
            </div>
        </section>
        <?php echo $this->form()->closeTag();?>
        <section class="faqs">
            <h1><?php echo $this->translate('FAQs');?></h1>
            <?php echo $this->content;?>
        </section>
    </div>
    <?php if ($this->getCurrentUser()):?>
        <?php echo $this->partial('partials/right-column');?>
    <?php endif;?>
</div>
<script type="text/javascript">
   var turnOffCustomStylePoint = 767;

    var supportOptions = {

        responsiveAt: turnOffCustomStylePoint,

        onFail: function() {},
        onSuccess: function(){},
        inputs: {
            'name': {
                filters: 'required'
            },
            'email': {
                filters: 'required email max',
                data: { max: 50 }
            },
            'query': {
                filters: 'required'
            }

        }
    };

    try{
        var $support = $('#feedback').idealforms(supportOptions).data('idealforms');
    }catch(e){}
</script>
