<?php
    $title = $this->translate('How to play');
    $this->headTitle($title);
?>
<div role="main" class="two-column-section clearfix">
    <div class="first-column registration support">
        <h1><?php echo $this->translate('How to play');?></h1>
        <article class="article-image article-image-right user-content clearfix">
            <div>
                <h2>Home or away, log on to predict the score for the upcoming match</h2>
                <p>Use your computer or <a href="">mobile consectetur adipiscing elit</a>. Aenean consectetur interdum suscipit. Curabitur massa magna, sollicitudin ut pharetra ac, ultrices in ipsum. Nullam sit amet nunc et neque interdum.</p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-left-1-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-left-1-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-left-1-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-left-1-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-left-1-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-left-1-1024.png" alt="howtoplay or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-left-1-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>

        <article class="article-image article-image-left user-content clearfix">
            <div>
                <h2>Play against your friends to become top of your league</h2>
                <p>Use your computer or mobile consectetur adipiscing elit. Aenean consectetur interdum suscipit. Curabitur massa magna, sollicitudin ut pharetra ac, ultrices in ipsum. Nullam sit amet nunc et neque interdum.</p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-right-1-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-right-1-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-right-1-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-right-1-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-right-1-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-right-1-1024.png" alt="Home or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-right-1-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>

        <article class="article-image article-image-right user-content clearfix">
            <div>
                <h2>Score big and win epic montly prizes</h2>
                <p>Use your computer or mobile consectetur adipiscing elit. Aenean consectetur interdum suscipit. Curabitur massa magna, sollicitudin ut pharetra ac, ultrices in ipsum. Nullam sit amet nunc et neque interdum.</p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-left-2-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-left-2-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-left-2-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-left-2-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-left-2-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-left-2-1024.png" alt="Home or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-left-2-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>
    </div>
    <?php echo $this->partial('partials/right-column');?>
</div>