<?php
    $title = $this->translate('How to play');
    $this->headTitle($title);
?>
<div role="main" class="one-column-section clearfix">
    <div class="first-column registration support">
        <h1><?php echo $this->translate('How to play');?></h1>
        <?php if (!empty($this->blocks)):?>
            <?php foreach ($this->blocks as $index => $block) : ?>
                <article class="article-image article-image-<?= ($index + 1)  % 2 == 0 ? 'left' : 'right'?> clearfix user-content">
                    <div>
                        <h2><?=$block['heading']?></h2>
                        <p><?=$block['description']?></p>
                    </div>
                    <figure>
                        <div data-alt="<?=$block['heading']?>" data-picture="">
                            <div data-src="<?=$block['foregroundImage']['width480']?>"></div>
                            <div data-media="(min-width: 480px)" data-src="<?=$block['foregroundImage']['width480']?>"></div>
                            <div data-media="(min-width: 600px)" data-src="<?=$block['foregroundImage']['width600']?>"></div>
                            <div data-media="(min-width: 768px)" data-src="<?=$block['foregroundImage']['width1024']?>"></div>
                            <div data-media="(min-width: 1025px)" data-src="<?=$block['foregroundImage']['width1280']?>"></div>
                            <noscript><img src="<?=$block['foregroundImage']['width1024']?>" alt="<?=$block['heading']?>" /></noscript>
                            <!--[if (lt IE 9) & (!IEMobile)]>
                            <div data-src="<?=$block['foregroundImage']['width1280']?>"></div>
                            <![endif]-->
                        </div>
                    </figure>
                </article>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
</div>