<?php
    $title = $this->translate('How to play');
    $this->headTitle($title);
?>
<div role="main" class="one-column-section clearfix">
    <div class="first-column registration support">
        <h1><?php echo $this->translate('How to play');?></h1>
        <article class="article-image article-image-right user-content clearfix">
            <div>
                <h2>Predict scores to earn points</h2>
                <p>Predict the scores and scorers of all Chelsea games to earn points. The closer the prediction, the more points you earn. The all-new match report section will provide facts and stats to assist you in making more informed predictions, helping you climb the table on your way to glory.&nbsp;</p>
                <p><strong>Score Predictor is now available across desktop, mobile and tablets, allowing you to guess the scores on the move.</strong></p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-left-1-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-left-1-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-left-1-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-left-1-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-left-1-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-left-1-1024.png" alt="howtoplay or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-left-1-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>

        <article class="article-image article-image-left user-content clearfix">
            <div>
                <h2>Take part in the leagues</h2>
                <p><p><span style="line-height: 1.6em;">Enter the global league to see how you fare against fans around the world, and be in with a chance of winning monthly and seasonal prizes.</span></p>
                <p><span style="line-height: 1.6em;">Looking for something more competitive, for the first time fans will also be able to take part in private leagues among friends, allowing you to compete for those important bragging rights. Set up your own league and compete with friends to determine who comes out top as the prediction champion.</span></p>
                </p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-right-1-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-right-1-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-right-1-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-right-1-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-right-1-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-right-1-1024.png" alt="Home or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-right-1-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>

        <article class="article-image article-image-right user-content clearfix">
            <div>
                <h2>What do points win? Prizes</h2>
                <p><p>The more points you earn the closer you get to winning monthly and seasonal prizes. Each month the winner and three runners-up will all receive a selection of Chelsea prizes, so check back regularly to find out what is on offer each month.</p>
                <p>Last year we gave away signed shirts, laptops and tablets among other rewards and this season there will be plenty more, so make sure you sign up now to be in with a chance of winning.</p>
                </p>
            </div>
            <figure>
                <div data-alt="Home or away, log on to predict the score for the upcoming match" data-picture="">
                    <div data-src="/img/howtoplay/article-image-left-2-480.png"></div>
                    <div data-media="(min-width: 480px)" data-src="/img/howtoplay/article-image-left-2-480.png"></div>
                    <div data-media="(min-width: 600px)" data-src="/img/howtoplay/article-image-left-2-600.png"></div>
                    <div data-media="(min-width: 768px)" data-src="/img/howtoplay/article-image-left-2-1024.png"></div>
                    <div data-media="(min-width: 1025px)" data-src="/img/howtoplay/article-image-left-2-1280.png"></div>
                    <noscript><img src="/img/howtoplay/article-image-left-2-1024.png" alt="Home or away, log on to predict the score for the upcoming match" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="/img/howtoplay/article-image-left-2-1280.png"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>
    </div>
</div>