<?php
$title = $this->translate('Forgot Password');
$this->headTitle($title);
?>
<h3 class="form-title"><?= $this->escapeHtml($title); ?></h3>
<?php
$this->renderMessages(true, true);
if ($this->isValid) :
?>
<form action="" method="POST" id="new-pwd">
    <div class="control-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9"><?=$this->translate("Password")?></label>
        <div class="controls">
            <div class="input-icon left">
                <i class="icon-lock"></i>
                <input class="m-wrap placeholder-no-fix" type="password" placeholder="<?=$this->translate('Password')?>" name="pwd" id="pwd"/>
            </div>
        </div>
    </div>
    <div class="control-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9"><?=$this->translate('Confirm Password')?></label>
        <div class="controls">
            <div class="input-icon left">
                <i class="icon-lock"></i>
                <input class="m-wrap placeholder-no-fix" type="password" placeholder="<?=$this->translate('Confirm Password')?>" name="pwd2" id="pwd2"/>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn green pull-right">
            <?=$this->translate('Save')?> <i class="m-icon-swapright m-icon-white"></i>
        </button>
    </div>
</form>
<?php endif; ?>