<?php
$title = $this->translate('Score Predictor Login');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('admin-login/process',
    array('action'     => 'authenticate',)));

if ($this->active !== false && $this->active != 'login')
    $form->setAttribute('style', 'display: none');
$form->prepare();

echo $this->form()->openTag($form);
$elements = $form->getElements();
$inputs = array($elements['email'], $elements['password']);
?>
<h3 class="form-title"><?php echo $this->escapeHtml($title); ?></h3>
<?php if ($this->active === false || $this->active == 'login') print $this->renderMessages(true, $this->active === false); ?>
<?php foreach ($inputs as $input) : ?>
    <div class="control-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9"><?=$this->translate($input->getLabel())?></label>
        <div class="controls">
            <div class="input-icon left">
                <i class="<?=$input->getAttribute('icon')?>"></i>
                <input class="m-wrap placeholder-no-fix" type="<?=$input->getAttribute('type')?>" placeholder="<?=$this->translate($input->getAttribute('placeholder'))?>" name="<?=$input->getAttribute('name')?>"/>
            </div>
        </div>
    </div>
<?php endforeach; ?>

<div class="form-actions">
    <label class="checkbox">
        <input type="<?=$elements['rememberme']->getAttribute('type')?>" name="<?=$elements['rememberme']->getAttribute('name')?>" value="1"/> <?=$this->translate($elements['rememberme']->getLabel())?>
    </label>
    <button type="submit" class="btn green pull-right">
        <?=$this->translate($elements['submit']->getValue())?> <i class="m-icon-swapright m-icon-white"></i>
    </button>
</div>
<div class="forget-password">
    <h4><?=$this->translate('Forgot your password ?')?></h4>
    <p>
        <?=$this->translate('no worries, click')?> <a href="javascript:;" class="" id="forget-password"><?=$this->translate('here')?></a> <?=$this->translate('to reset your password.')?>
    </p>
</div>
<?php
echo $this->form()->closeTag();
$forgotAction = $this->url('admin-login/process', array('action' => 'resetPassword'));
?>
<!-- BEGIN FORGOT PASSWORD FORM -->
<form class="form-vertical forget-form" action="<?=$forgotAction?>" method="POST" <?=$this->active == 'reset' ? 'style="display:block"' : ''?>>
    <h3 class=""><?=$this->translate('Forget Password ?')?></h3>
    <?php if ($this->active == 'reset') print $this->renderMessages(true); ?>
    <p><?=$this->translate('Enter your e-mail address below to reset your password.')?></p>
    <div class="control-group">
        <label class="control-label visible-ie8 visible-ie9"><?=$this->translate('Email')?></label>
        <div class="controls">
            <div class="input-icon left">
                <i class="icon-envelope"></i>
                <input class="m-wrap placeholder-no-fix" type="text" placeholder="<?=$this->translate('Email')?>" name="email" />
            </div>
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="back-btn" class="btn">
            <i class="m-icon-swapleft"></i> <?=$this->translate('Back')?>
        </button>
        <button type="submit" class="btn green pull-right">
            <?=$this->translate('Submit')?> <i class="m-icon-swapright m-icon-white"></i>
        </button>
    </div>
</form>
<!-- END FORGOT PASSWORD FORM -->