<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
<?php //echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
//                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/css/common.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
<?php //echo $this->headScript()->prependFile($this->basePath() . '/js/main.js')
//                                      ->prependFile($this->basePath() . '/js/jquery.cookie.js')
//                                      ->prependFile($this->basePath() . '/js/jquery.validate.password.js')
//                                      ->prependFile($this->basePath() . '/js/jquery.validate.js')
//                                      ->prependFile($this->basePath() . '/js/vendor/jquery-1.9.1.min.js');
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
