<?php
$this->headTitle($this->title);
?>
<div class="container-fluid">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
    $elements = $form->getElements();
    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    $inputElements = array($elements['homeTeam'], $elements['awayTeam'], $elements['date'], $elements['kick_off_time'], $elements['isDoublePoints']);
    ?>
    <div class="form">
        <div class="row-fluid">
            <?php if ($this->params['action'] == 'add'):?>
                <?php if (!empty($this->seasons)):?>
                <div class="control-group form-horizontal">
                    <label class="control-label"><?=$this->translate('Seasons')?></label>
                    <div class="controls">
                        <select class="seasons-select form-select" name="season">
                            <option value=""><?php echo $this->translate('- Select Season -');?></option>
                            <?php foreach($this->seasons as $season):?>
                                <option value="<?php echo $season['id']?>" <?php echo ($season['id'] == $this->currentSeasonId) ? 'selected="selected"' : '';?>><?php echo $season['displayName'];?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="control-group form-horizontal competitions-wrapper" style="display:none;">
                    <label class="control-label"><?=$this->translate('Competition')?></label>
                    <div class="controls">
                        <select class="competitions-select form-select" name="competition">
                        </select>
                    </div>
                </div>
                <?php endif;?>
            <?php endif;?>
            <?php foreach($inputElements as $element):
                $type = $element->getAttribute('type');
                $hint = $element->getAttribute('hint');
                $class = $element->getAttribute('class');
            ?>

            <div class="control-group form-horizontal clearfix">
                <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                <div class="controls">
                    <?php if ($type == 'text') : ?>
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-time"></i></span><input class="m-wrap medium check-values <?php echo $class;?>" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?>  data-original_value="<?=$element->getValue();?>" value="<?=$element->getValue();?>"/>
                    </div>
                    <?php elseif ($type == 'select'): ?>
                        <?php echo $this->formSelect($element);?>
                    <?php elseif ($type == 'checkbox'): ?>
                        <?php echo $this->formCheckbox($element);?>
                    <?php endif; ?>
                    <?php if (!empty($hint)) : ?>
                        <span class="help-inline"><?=$hint?></span>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach;?>
            <?php echo $this->formHidden($form->get('type'));?>
            <?php if (!$this->isFullTime) : ?>
            <div class="form-actions">
                <a href="#deleteModal" role="button" class="btn blue update-fixture" data-blocked="<?php echo (!empty($this->isBlocked) ? 1 : 0);?>" data-toggle="modal">
                    <i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue());?>
                </a>
                <?php if ($this->isBlocked && $this->params['action'] != 'add'):?>
                <a href="<?php echo $this->url('admin-fixtures', array('action'=> 'syncwithfeed', 'fixture'=>(!empty($this->params['fixture']) ? $this->params['fixture'] : null )))?>" role="button" class="btn blue">
                    <i class="icon-ok"></i> <?=$this->translate('Sync with feed');?>
                </a>
                <?php endif;?>
                <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>

            </div>
            <?php endif;?>
        </div>
     </div>
     <?php echo $this->form()->closeTag();?>
</div>
<?php if ($this->params['action'] == 'edit'):?>
<!--REGIONALISED DATA START-->
    <?php if (!empty($this->featuredPlayerForm)):?>
        <!--FEATURED PLAYER STARTS-->
            <div class="portlet box red">
                <div class="portlet-title">
                    <h4><i class="icon-reorder"></i><?php echo $this->translate('Featured Player');?></h4>
                    <div class="tools">
                        <a class="collapse" href="javascript:;"></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <?php
                    $this->featuredPlayerForm->prepare();
                    $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
                        echo $this->form()->openTag($this->featuredPlayerForm);
                    ?>
                        <?php echo $this->renderRegionFieldsets($this->featuredPlayerForm->getFieldsets(), $this->params['action'] == 'add', 'player');?>
                    <?php echo $this->formHidden($this->featuredPlayerForm->get('type'));?>
                    <div class="form-actions">
                        <button type="submit" class="btn blue"><?=$this->translate($this->featuredPlayerForm->get('submit')->getValue());?></button>
                        <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                    </div>
                    <?php echo $this->form()->closeTag();?>
                </div>
            </div>
        <!--FEATURED PLAYER ENDS-->
    <?php endif;?>
    <?php if (!empty($this->featuredGoalkeeperForm)):?>
    <!--FEATURED GOALKEEPER STARTS-->
        <div class="portlet box green">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i><?php echo $this->translate('Featured Goalkeeper');?></h4>
                <div class="tools">
                    <a class="collapse" href="javascript:;"></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                $this->featuredGoalkeeperForm->prepare();
                $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
                echo $this->form()->openTag($this->featuredGoalkeeperForm);
                ?>
                <?php echo $this->renderRegionFieldsets($this->featuredGoalkeeperForm->getFieldsets(), $this->params['action'] == 'add', 'goalkeeper');?>
                <?php echo $this->formHidden($this->featuredGoalkeeperForm->get('type'));?>
                <div class="form-actions">
                    <button type="submit" class="btn blue"><?=$this->translate($this->featuredGoalkeeperForm->get('submit')->getValue());?></button>
                    <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                </div>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
    <!--FEATURED GOALKEEPER ENDS-->
    <?php endif;?>
    <?php if (!empty($this->featuredPredictionForm)):?>
        <!--FEATURED PREDICTION STARTS-->
        <div class="portlet box purple">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i><?php echo $this->translate('Featured Prediction');?></h4>
                <div class="tools">
                    <a class="collapse" href="javascript:;"></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                $this->featuredPredictionForm->prepare();
                $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
                echo $this->form()->openTag($this->featuredPredictionForm);
                ?>
                <?php echo $this->renderRegionFieldsets($this->featuredPredictionForm->getFieldsets(), $this->params['action'] == 'add', 'prediction');?>
                <?php echo $this->formHidden($this->featuredPredictionForm->get('type'));?>
                <div class="form-actions">
                    <button type="submit" class="btn blue"><?=$this->translate($this->featuredPredictionForm->get('submit')->getValue());?></button>
                    <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                </div>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
        <!--FEATURED PREDICTION ENDS-->
    <?php endif;?>
    <?php if (!empty($this->matchReportForm)):?>
        <!--MATCH REPORT STARTS-->
        <div class="portlet box yellow">
            <div class="portlet-title">
                <h4><i class="icon-reorder"></i><?php echo $this->translate('Match Report');?></h4>
                <div class="tools">
                    <a class="collapse" href="javascript:;"></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php
                $this->matchReportForm->prepare();
                $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
                echo $this->form()->openTag($this->matchReportForm);
                ?>
                <?php echo $this->renderRegionFieldsets($this->matchReportForm->getFieldsets(), $this->params['action'] == 'add', 'report');?>
                <?php echo $this->formHidden($this->matchReportForm->get('type'));?>
                <div class="form-actions">
                    <button type="submit" class="btn blue"><?=$this->translate($this->matchReportForm->get('submit')->getValue());?></button>
                    <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                </div>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
        <!--MATCH REPORT ENDS-->
    <?php endif;?>
<!--REGIONALISED DATA ENDS-->

    <!--ANALYTICS START-->
        <div class="portlet box grey">
        <div class="portlet-title">
            <h4><i class="icon-reorder"></i><?php echo $this->translate('Prediction Analytics');?></h4>
            <div class="tools">
                <a class="collapse" href="javascript:;"></a>
            </div>
        </div>
        <div class="portlet-body">
            <dl>
                <dt><?php echo $this->translate('Total number of predictions');?></dt>
                <dd><?php echo (!empty($this->analytics['predictions_number']) ? $this->analytics['predictions_number'] : 0);?></dd>
                <dt><?php echo $this->translate('Number of predictions each hour over time');?></dt>
                <dd>
                    <?php if (!empty($this->analytics['number_of_predictions_per_hour'])):?>
                    <ul>
                        <?php foreach($this->analytics['number_of_predictions_per_hour'] as $analytics):?>
                        <li><?php echo date('h a', strtotime($analytics['date']));?> - <?php echo $analytics['number'];?></li>
                        <?php endforeach;?>
                    </ul>
                    <?php else :?>
                    <?php echo $this->translate('Empty');?>
                    <?php endif;?>
                </dd>
                <dt><?php echo $this->translate('Percentage of registered users that made a prediction');?></dt>
                <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['made_prediction']) ? $this->analytics['made_prediction'] : 0);?>"><?php echo (!empty($this->analytics['made_prediction']) ? $this->analytics['made_prediction'] : 0);?>%</div></dd>
                <dt><?php echo $this->translate('Top 5 most popular scores');?></dt>
                <dd>
                    <?php if (!empty($this->analytics['top_scores'])):?>
                    <ul>
                        <?php foreach($this->analytics['top_scores'] as $score):?>
                        <li><?php echo $score['home_team_score'];?> : <?php echo $score['away_team_score'];?></li>
                        <?php endforeach;?>
                    </ul>
                    <?php else :?>
                    <?php echo $this->translate('Empty');?>
                    <?php endif;?>
                </dd>
                <dt><?php echo $this->translate('Top 5 most popular scorers');?></dt>
                <dd>
                    <?php if (!empty($this->analytics['top_scorers'])):?>
                    <ul>
                        <?php foreach($this->analytics['top_scorers'] as $scorer):?>
                        <li><?php echo $scorer['player_name'];?> (<?php echo $scorer['team_name'];?>)</li>
                        <?php endforeach;?>
                    </ul>
                    <?php else :?>
                    <?php echo $this->translate('Empty');?>
                    <?php endif;?>
                </dd>
                <?php if (!empty($this->isFullTime)):?>
                <dt><?php echo $this->translate('Percentage of registered users with correct result');?></dt>
                <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['correct_result']) ? $this->analytics['correct_result'] : 0);?>"><?php echo (!empty($this->analytics['correct_result']) ? $this->analytics['correct_result'] : 0);?>%</div></dd>
                <dt><?php echo $this->translate('Percentage of registered users with correct score');?></dt>
                <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['correct_score']) ? $this->analytics['correct_score'] : 0);?>"><?php echo (!empty($this->analytics['correct_score']) ? $this->analytics['correct_score'] : 0);?>%</div></dd>
                <dt><?php echo $this->translate('Percentage of registered users with correct scorers');?></dt>
                <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['correct_scorers']) ? $this->analytics['correct_scorers'] : 0);?>"><?php echo (!empty($this->analytics['correct_scorers']) ? $this->analytics['correct_scorers'] : 0);?>%</div></dd>
                <dt><?php echo $this->translate('Percentage of registered users with correct scores order');?></dt>
                <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['correct_scorers_order']) ? $this->analytics['correct_scorers_order'] : 0);?>"><?php echo (!empty($this->analytics['correct_scorers_order']) ? $this->analytics['correct_scorers_order'] : 0);?>%</div></dd>
                <dt><?php echo $this->translate('Percentage of registered users with perfect result');?></dt>
                <?php if (!empty($this->analytics['perfect_result']['users'])):?>
                    <dd><div class="custom-chart" data-percent="<?php echo (!empty($this->analytics['perfect_result']['percentage']) ? $this->analytics['perfect_result']['percentage'] : 0);?>"><?php echo (!empty($this->analytics['perfect_result']['percentage']) ? $this->analytics['perfect_result']['percentage'] : 0);?>%</div></dd>
                    <ul>
                        <?php foreach($this->analytics['perfect_result']['users'] as $user):?>
                        <li><a href="<?php echo $this->url('admin-fixtures',array('action'=>'getuserdata', 'fixture'=>$user['id']))?>"><?php echo $user['displayName'];?></a></li>
                        <?php endforeach;?>
                    </ul>
                    <?php else :?>
                    <?php echo $this->translate('Empty');?>
                    <?php endif;?>
                <?php endif;?>
            </dl>
        </div>
    </div>
    <!--ANALYTICS END-->
<?php endif;?>
<?php if (!$this->isBlocked):?>
    <div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm')?></h3>
        </div>
        <div class="modal-body">
            <p><?php echo $this->translate("If you'd like to change home team, away team, date or kick-off time  you have to be aware that it will override the data feed permanently.");?></p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close');?></button>
            <button data-dismiss="modal" class="btn blue"
                    onclick="$('#fixture').submit();">
                <?php echo $this->translate('Confirm');?>
            </button>
        </div>
    </div>
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-timepicker/compiled/timepicker.css" />
<link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>

<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

<script type="text/javascript">
    <?php if ($this->params['action'] == 'add' && !empty($this->seasons)):?>
        var seasons = [];
        <?php foreach($this->seasons as $season):?>
            var competitions = [];

            <?php if (!empty($season['competitions'])):?>
                <?php foreach($season['competitions'] as $competition):?>
                    competitions.push({id : "<?php echo $competition['id']?>",name : "<?php echo $competition['displayName'];?>"});
                <?php endforeach;?>
            <?php endif;?>

            seasons["<?php echo $season['id'];?>_"] = competitions;
        <?php endforeach;?>
    <?php endif;?>
    jQuery(document).ready(function() {
        $('.custom-chart').easyPieChart({
            animate : 1000
        });
        $('.my-picker').datepicker().on('changeDate', function(){
              $(this).change();
        });
        $('.kick-off-time').timepicker({
            defaultTime : false
        });
        var form = $('#fixture');
        $('.update-fixture').click(function(e){
              if (!$(this).data('blocked')){
                  var changed = false;
                  $('.check-values').each(function(){
                      var val = $(this).val();
                      if (val != $(this).data('original_value')){
                            changed = true;
                      }
                  });
                  if (changed){
                      return true;
                  }else{
                      form.submit();
                      return false;
                  }
              }else{
                  form.submit();
                  return false;
              }
        });


        $('button.reset').click(function(e){
            e.preventDefault();
            this.form.reset();
            $('.chosen').trigger('liszt:updated');
            var checkbox = $('.double-points-checkbox');
            if (checkbox.is(':checked')){
                checkbox.closest('span').addClass('checked');
            }else{
                checkbox.closest('span').removeClass('checked');
            }
        });

        //Select seasons
        $('.seasons-select').change(function(){
            var competitions_select = $('.competitions-select');
            var competitions_wrapper = competitions_select.closest('.competitions-wrapper');
            var val = $(this).val();
            if (val == "" || seasons[val + "_"] === undefined){
                competitions_select.empty();
                competitions_wrapper.hide();
            }else{
                var competitions = seasons[val + "_"];
                if (competitions.length){
                    competitions_select.empty();
                    competitions_select.append("<option value=''>- Select Competition -</option>");
                    for (var i = 0; i < competitions.length; i++){
                        competitions_select.append('<option value="'+competitions[i].id+'">'+competitions[i].name+'</option>');
                    }
                    competitions_wrapper.show();
                }
            }
        }).change();
        if (jQuery().wysihtml5) {
            if ($('.wysihtml5').size() > 0) {
                $('.wysihtml5').each(function(i, el) {
                    $(el).wysihtml5('bypassDefaults', {
                        "stylesheets": ["<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysiwyg-color.css"]
                    });
                });
            }
        }
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->