<?php
$this->headTitle($this->title);
?>
<div class="container-fluid">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin-fixtures', $this->params));
    $elements = $form->getElements();
    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    $elements = array($elements['homeTeam'], $elements['awayTeam'], $elements['date'], $elements['kick_off_time'], $elements['isDoublePoints'], $elements['submit']);
    ?>
    <div class="form">
        <div class="row-fluid">
            <?php if ($this->params['action'] == 'add'):?>
                <?php if (!empty($this->seasons)):?>
                <div class="control-group form-horizontal">
                    <label class="control-label"><?=$this->translate('Seasons')?></label>
                    <div class="controls">
                        <select class="seasons-select" name="season">
                            <option value=""><?php echo $this->translate('- Select Season -');?></option>
                            <?php foreach($this->seasons as $season):?>
                                <option value="<?php echo $season['id']?>" <?php echo ($season['id'] == $this->currentSeasonId) ? 'selected="selected"' : '';?>><?php echo $season['displayName'];?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="control-group form-horizontal competitions-wrapper" style="display:none;">
                    <label class="control-label"><?=$this->translate('Competition')?></label>
                    <div class="controls">
                        <select class="competitions-select" name="competition">
                        </select>
                    </div>
                </div>
                <?php endif;?>
            <?php endif;?>
            <?php foreach($elements as $element):
                $type = $element->getAttribute('type');
                $hint = $element->getAttribute('hint');
                $class = $element->getAttribute('class');
            ?>
            <?php if ($element->getAttribute('name') != 'submit'):?>
            <div class="control-group form-horizontal">
                <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                <div class="controls">
                    <?php if ($type == 'text') : ?>
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-time"></i></span><input class="m-wrap medium check-values <?php echo $class;?>" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?>  data-changed="0" data-original_value="<?=$element->getValue();?>" value="<?=$element->getValue();?>"/>
                    </div>
                    <?php elseif ($type == 'select'): ?>
                        <?php echo $this->formSelect($element);?>
                    <?php elseif ($type == 'checkbox'): ?>
                        <?php echo $this->formCheckbox($element);?>
                    <?php endif; ?>
                    <?php if (!empty($hint)) : ?>
                        <span class="help-inline"><?=$hint?></span>
                    <?php endif; ?>
                </div>
            </div>
            <?php else:?>
                <div class="form-actions">
                    <a href="#deleteModal" role="button" class="btn blue update-fixture" data-blocked="<?php echo (!empty($this->isBlocked) ? 1 : 0);?>" data-toggle="modal">
                        <i class="icon-ok"></i> <?=$this->translate($element->getValue());?>
                    </a>
                    <?php if ($this->isBlocked && $this->params['action'] != 'add'):?>
                        <a href="<?php echo $this->url('admin-fixtures', array('action'=> 'syncwithfeed', 'fixture'=>(!empty($this->params['fixture']) ? $this->params['fixture'] : null )))?>" role="button" class="btn blue">
                            <i class="icon-ok"></i> <?=$this->translate('Sync with feed');?>
                        </a>
                    <?php endif;?>
                    <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>

                </div>
            <?php endif;?>
            <?php endforeach;?>
        </div>
     <div>
     <?php echo $this->form()->closeTag();?>
</div>
</div>
<?php if (!$this->isBlocked):?>
    <div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm')?></h3>
        </div>
        <div class="modal-body">
            <?php //TODO change?>
            <p><?php echo $this->translate("If you'd like to change home team, away team, date or kick-off time  you have to be aware that it will override the data feed permanently.");?></p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close');?></button>
            <button data-dismiss="modal" class="btn blue"
                    onclick="$('#fixture').submit();">
                <?php echo $this->translate('Confirm');?>
            </button>
        </div>
    </div>
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-timepicker/compiled/timepicker.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

<script type="text/javascript">
    <?php if ($this->params['action'] == 'add' && !empty($this->seasons)):?>
        var seasons = [];
        <?php foreach($this->seasons as $season):?>
            var competitions = [];

            <?php if (!empty($season['competitions'])):?>
                <?php foreach($season['competitions'] as $competition):?>
                    competitions.push({id : "<?php echo $competition['id']?>",name : "<?php echo $competition['displayName'];?>"});
                <?php endforeach;?>
            <?php endif;?>

            seasons["<?php echo $season['id'];?>_"] = competitions;
        <?php endforeach;?>
    <?php endif;?>
    jQuery(document).ready(function() {
        $('.my-picker').datepicker().on('changeDate', function(){
              $(this).change();
        });
        $('.kick-off-time').timepicker({
            defaultTime : false
        });
        var form = $('#fixture');
        $('.update-fixture').click(function(e){
              if (!$(this).data('blocked')){
                  var changed = false;
                  $('.check-values').each(function(){
                        if ($(this).data('changed')){
                            changed = true;
                        }
                  });
                  if (changed){
                      return true;
                  }else{
                      form.submit();
                      return false;
                  }
              }else{
                  form.submit();
                  return false;
              }
        });

        $('.check-values').change(function(){
           var val = $(this).val();
           if (val != $(this).data('original_value')){
               $(this).data('changed', 1);
           }else{
               $(this).data('changed', 0);
           }
        });
        $('button.reset').click(function(e){
            e.preventDefault();

            this.form.reset();
            $('.check-values').each(function(){
                $(this).data('changed', 0);
            });
        });

        //Select seasons
        $('.seasons-select').change(function(){
            var competitions_select = $('.competitions-select');
            var competitions_wrapper = competitions_select.closest('.competitions-wrapper');
            var val = $(this).val();
            if (val == "" || seasons[val + "_"] === undefined){
                competitions_select.empty();
                competitions_wrapper.hide();
            }else{
                
                var competitions = seasons[val + "_"];
                if (competitions.length){
                    competitions_select.empty();
                    competitions_select.append("<option value=''>- Select Competition -</option>");
                    for (var i = 0; i < competitions.length; i++){
                        competitions_select.append('<option value="'+competitions[i].id+'">'+competitions[i].name+'</option>');
                    }
                    competitions_wrapper.show();
                }
            }
        }).change();
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->