<?php
$title = $this->translate('Fixtures');
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$title;?></h4>
                <div class="actions">
                    <a href="<?=$this->url('admin-fixtures', array('action' => 'add'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('New')?></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->fixtures)) : ?>
                    <div class="datatable-filter">
                        <?php if (!empty($this->seasons)):?>
                            <label>
                                <select class="seasons-filter">
                                    <?php foreach($this->seasons as $season):?>
                                        <option value="<?php echo $season['displayName'];?>" <?php echo ($season['id'] == $this->currentSeasonId) ? 'selected="selected"' : '';?>><?php echo $season['displayName'];?></option>
                                    <?php endforeach;?>
                                </select>
                                <?php echo $this->translate('filter by season');?>
                            </label>
                        <?php endif;?>
                        <label>
                            <select class="competitions-filter">
                                <option value="-1"><?php echo $this->translate('All');?></option>
                                <?php if (!empty($this->competitions)):?>
                                    <?php foreach($this->competitions as $competition):?>
                                        <option value="<?php echo $competition['displayName'];?>"><?php echo $competition['displayName'];?></option>
                                    <?php endforeach;?>
                                <?php endif;?>
                            </select>
                            <?php echo $this->translate('filter by competition');?>
                        </label>
                        <label>
                            <select class="type-filter">
                                  <option value="1"><?=$this->translate('Upcoming');?></option>
                                  <option value="0"><?=$this->translate('Past');?></option>
                            </select>
                            <?php echo $this->translate('filter by type');?>
                        </label>
                    </div>
                    <table class="table table-striped table-bordered table-hover" id="fixtures-table">
                        <thead>
                        <tr>
                            <th><?=$this->translate('Home Team');?></th>
                            <th><?=$this->translate('Away Team');?></th>
                            <th><?=$this->translate('Date And Time');?></th>
                            <th><?=$this->translate('Competition');?></th>
                            <th><?=$this->translate('Season');?></th>
                            <th style="display:none;"><?=$this->translate('Status');?></th>
                            <th style="width: 60px"><?php echo $this->translate('Action');?></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->fixtures as $fixture) : ?>
                        <tr class="odd gradeX">
                            <td><?=$fixture['home_team'];?></td>
                            <td><?=$fixture['away_team'];?></td>
                            <td><?=$fixture['date_and_time']->format('D, d M Y H:i');?></td>
                            <td><?=$fixture['competition_name'];?></td>
                            <td><?=$fixture['season_name'];?></td>
                            <td style="display:none;"><?=$fixture['status'];?></td>
                            <td>
                                <a href="<?=$this->url('admin-fixtures', array('action' => 'edit', 'fixture' => $fixture['id']))?>" class="btn mini blue">
                                    <i class="icon-edit"></i>
                                    <?=$this->translate('Edit')?>
                                </a>
                            </td>
                        </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                <?=$this->translate('There is no fixtures')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
     var PRE_MATCH_STATUS = '<?php echo \Application\Model\Entities\Match::PRE_MATCH_STATUS;?>'
    //Filter by season
    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            var season= jQuery('.seasons-filter').val();
            var value = aData[4];
            if (season != value){
                return false;
            }
            return true;
        }
    );

    //Filter by competition
    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            var competition= jQuery('.competitions-filter').val();
            var value = aData[3];
            if (competition != value && competition != "-1"){
                return false;
            }
            return true;
        }
    );

    //Filter by type
    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            var isUpcoming = parseInt(jQuery('.type-filter').val());
            var value = aData[5];
            return (isUpcoming && value == PRE_MATCH_STATUS) || (!isUpcoming && value != PRE_MATCH_STATUS);
        }
    );

    //Date sorting
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        /* Custom filtering function which will filter data in column four between two values */


       var messages = {perPage: "_MENU_ " + "<?=$this->translate('fixtures per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ fixtures')?>"};
       var oTable = $('#fixtures-table').dataTable({
            "aoColumns": [null, null,{"sType" : "date"},null,null,null,{bSortable: false}],
            "aLengthMenu": [[5, 10, 15, 25, 50, 100 , -1], [5, 10, 15, 25, 50, 100, "All"]],
            "bStateSave" : true,
            "iCookieDuration": 60 * 60 * 24 * 365 * 100,
            "fnStateLoadParams" : function(oSettings, oData){
               oData.oSearch.sSearch = '';
               oData.aaSorting = [];
            },
           // "bFilter": false,
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
        oTable.fnSort( [ [2,'desc'] ] );
        //Filter by season
        $('.seasons-filter, .competitions-filter, .type-filter').change(function(){
            oTable.fnDraw();
        })
    });
</script>
<!-- END JAVASCRIPTS -->