<?php
    $this->title = 'Add Mini League';
    $this->headTitle($this->title);
?>

<div class="container-fluid">
<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin-leagues', array('action' => $this->action . 'MiniLeague', 'id' => $this->leagueId)));
    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    $inputs = array($elements['displayName'], $elements['dates']);
    if ($this->action == 'add')
        $inputs [] = $elements['season'];
?>
    <div class="form">
        <div class="row-fluid" style="margin-bottom: 10px;">
            <?php foreach ($inputs as $input) :
            $type = $input->getAttribute('type');
            $name = $input->getAttribute('name');
            ?>
            <div class="control-group form-horizontal">
                <label class="control-label"><?=$this->translate($input->getLabel())?></label>
                <div class="controls">
                    <div class="input-prepend">
                        <?php if ($name == 'dates') : ?>
                            <div id="form-date-range" class="date-range btn">
                                <i class="icon-calendar"></i>
                                &nbsp;<span></span>
                                <b class="caret"></b>
                            </div>
                            <input id="form-date-range-value" type="hidden" name="<?=$name?>" value="<?=$input->getValue()?>"/>
                        <?php elseif($name == 'season'): ?>
                            <?php echo $this->formSelect($input);?>
                        <?php else: ?>
                        <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$type?>" name="<?=$name?>" value="<?=$input->getValue()?>"/>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <input type="hidden" name="regions" id="regions" value="<?=$form->get('regions')->getValue()?>"/>
            <div class="control-group form-horizontal">
                <label class="control-label"><?=$this->translate('You have to choose at least one region')?></label>
                <div class="controls">
                    <?php foreach ($this->regions as $region) : ?>
                        <div>
                            <label class="inline" for="region-<?=$region['id']?>"><input type="checkbox" id="region-<?=$region['id']?>" value="<?=$region['id']?>" > <?=$region['displayName']?></label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <?php echo $this->renderRegionFieldsets($form->getFieldsets(), $this->action == 'add'); ?>
        <div class="form-actions">
            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
            <button type="button" class="btn">Cancel</button>
        </div>
        <?php echo $this->form()->closeTag();?>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.css" />
<link href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/date.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        initDatePicker();
        $('.form-actions button[type=button]').click(function(e) {
            e.preventDefault();
            this.form.reset();
        });
        if (jQuery().wysihtml5) {
            if ($('.wysihtml5').size() > 0) {
                $('.wysihtml5').each(function(i, el) {
                    $(el).wysihtml5('bypassDefaults', {
                        "stylesheets": ["<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-wysihtml5/wysiwyg-color.css"]
                    });
                });
            }
        }
        $('div.form').children('div.row-fluid:last').find('ul.nav-tabs li').hide();
        $('div.form').children('div.row-fluid:last').find('div.tab-pane').addClass('hidden');
        $("input[type='checkbox']").change(function() {
            var regionId = $(this).val();
            var tabsContainer = $('div.form').children('div.row-fluid:last');
            var tab = tabsContainer.find('ul.nav-tabs li:has(a[href="#tab_' + regionId + '"])');
            var tabContainer = tabsContainer.find('div.tab-pane[id="tab_' + regionId + '"]');
            var regions = $("#regions").val().split(',');
            if (regions.length == 1 && regions[0] == '') regions = [];
            if ($(this).attr('checked')) {
                if (regions.indexOf(regionId) == -1)
                    regions[regions.length] = regionId;
                tab.show();
                tabContainer.removeClass('hidden');
                tab.find('a').click();
            } else {
                if (regions.indexOf(regionId) != -1)
                    regions.splice(regions.indexOf(regionId), 1);
                tab.hide();
                tabsContainer.find('ul.nav-tabs li:visible:first a').click();
                tabContainer.addClass('hidden');
            }
            $("#regions").val(regions.join(","));
        });
        $("input[type='checkbox']").each(function() {
            var regions = $("#regions").val().split(',');
            if (regions.indexOf($(this).val()) != -1) {
                $(this).attr('checked', 'checked');
                $(this).trigger('change');
            }
        });
        App.init(); // initlayout and core plugins
    });
    function parseDate(date) {
        var dateParts = date.split("/");
        return new Date(dateParts[2], (dateParts[1] - 1), dateParts[0]);
    }

    function initDatePicker() {
        var dates = $('input[name="dates"]');
        var currentDates = dates.val();
        var datePickerOptions = {format: 'dd/MM/yyyy'};
        if (currentDates == '') {
            var fromDate = Date.today().add({days: 1});
            var toDate = Date.today().add({days: 31});
        } else {
            var fromDate = parseDate($.trim(currentDates.split("-")[0]));
            var toDate = parseDate($.trim(currentDates.split("-")[1]));
        }

        var tomorrow = Date.today().add({days: 1});

        $('.date-range').daterangepicker({
                ranges: {
                    'Tomorrow': ['tomorrow', 'tomorrow'],
                    'Next 7 Days': ['tomorrow', Date.today().add({
                        days: 7
                    })],
                    'Next 30 Days': ['tomorrow', Date.today().add({
                        days: 30
                    })],
                    'This Month': [tomorrow.clone().moveToFirstDayOfMonth(), tomorrow.clone().moveToLastDayOfMonth()],
                    'Next Month': [tomorrow.clone().moveToFirstDayOfMonth().add({
                        months: 1
                    }).moveToFirstDayOfMonth(), Date.today().moveToFirstDayOfMonth().add({
                        months: 1
                    }).moveToLastDayOfMonth()]
                },
                opens: 'right',
                format: 'dd/MM/yyyy',
                separator: ' - ',
                startDate: fromDate,
                endDate: toDate,
                minDate: tomorrow.clone(),
                maxDate: tomorrow.clone().add({years: 2}),
                locale: {
                    applyLabel: 'Submit',
                    fromLabel: 'From',
                    toLabel: 'To',
                    customRangeLabel: 'Custom Range',
                    daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    firstDay: 1
                },
                showWeekNumbers: true,
                buttonClasses: ['btn-danger']
            },

            function (start, end) {
                $('#form-date-range span').text(start.toString('dd MMMM, yyyy') + ' - ' + end.toString('dd MMMM, yyyy'));
                $('#form-date-range-value').val(start.toString('dd/MM/yyyy') + ' - ' + end.toString('dd/MM/yyyy'));
            });

        $('#form-date-range span').html(fromDate.toString('dd MMMM, yyyy') + " - " + toDate.toString('dd MMMM, yyyy'));
        $('#form-date-range-value').val(fromDate.toString('dd/MM/yyyy') + ' - ' + toDate.toString('dd/MM/yyyy'));

        if (!jQuery().datepicker || !jQuery().timepicker) {
            return;
        }
    }
</script>
<!-- END JAVASCRIPTS -->