<?php
$title = $this->translate('Leagues');
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$title;?></h4>
                <div class="actions">
                    <a href="<?=$this->url('admin-leagues', array('action' => 'addMiniLeague'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Add Mini League')?></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->leagues)) : ?>
                <div class="datatable-filter">
                    <label for='leagues-type-filter'>
                        <select id="leagues-type-filter">
                            <option selected="selected" value="-1"><?php echo $this->translate('All');?></option>
                            <?php foreach (\Application\Model\Entities\League::getAvailableTypes() as $i => $type) : ?>
                                <option value="<?=$i?>"><?php echo $this->translate($type);?></option>
                            <?php endforeach; ?>
                        </select>
                        <?php echo $this->translate('filter by type')?>
                    </label>
                    <label for='leagues-season-filter'>
                        <select id="leagues-season-filter">
                            <option selected="selected" value="-1"><?php echo $this->translate('All');?></option>
                            <?php foreach ($this->seasons as $i => $season) : ?>
                                <option value="<?=$i?>"><?php echo $season['displayName'];?></option>
                            <?php endforeach; ?>
                        </select>
                        <?php echo $this->translate('filter by season')?>
                    </label>
                    <label for='leagues-time-filter'>
                        <select id="leagues-time-filter">
                            <option selected="selected" value="-1"><?php echo $this->translate('All');?></option>
                            <option value="1"><?php echo $this->translate('Current');?></option>
                            <option value="2"><?php echo $this->translate('Future');?></option>
                            <option value="3"><?php echo $this->translate('Past');?></option>
                        </select>
                        <?php echo $this->translate('filter by time')?>
                    </label>
                </div>
                <table class="table table-striped table-bordered table-hover" id="leagues-table">
                    <thead>
                    <tr>
                        <th><?=$this->translate('Name');?></th>
                        <th><?=$this->translate('Type');?></th>
                        <th><?=$this->translate('Season');?></th>
                        <th><?=$this->translate('Start Date');?></th>
                        <th><?=$this->translate('End Date');?></th>
                        <th style="width: 210px"><?php echo $this->translate('Action');?></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->leagues as $league) : ?>
                        <tr>
                            <td><?=$league['displayName'];?></td>
                            <td><?=$league['type'];?></td>
                            <td><?=$league['seasonName'];?></td>
                            <td><?=$league['startDate']->format("j F Y");?></td>
                            <td><?=$league['endDate']->format("j F Y");?></td>
                            <td>
                                <?php
                                    $url = $league['type'] == \Application\Model\Entities\League::MINI_TYPE  ?
                                        $this->url('admin-leagues', array('action' => 'editMiniLeague', 'id' => $league['id'])) :
                                        $this->url('admin-seasons', array('action' => 'edit', 'id' => $league['seasonId']));
                                ?>
                                <a href="<?=$url?>" class="btn mini blue">
                                    <i class="icon-edit"></i>
                                    <?=$this->translate('Edit')?>
                                </a>
                                <a href="<?=$this->url('admin-leagues', array('action' => 'viewTable', 'id' => $league['id']))?>" class="btn mini green">
                                    <i class="icon-eye-open"></i>
                                    <?=$this->translate('Table')?>
                                </a>
                                <?php if ($league['type'] == \Application\Model\Entities\League::MINI_TYPE) : ?>
                                    <a href="#deleteModal<?=$league['id']?>" role="button" class="btn btn-warning mini red" data-toggle="modal">
                                        <i class="icon-trash"></i>
                                        <?=$this->translate('Delete')?>
                                    </a>
                                    <div id="deleteModal<?=$league['id']?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                            <h3 id="myModalLabel3">Please Confirm</h3>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete this mini league?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                            <button data-dismiss="modal" class="btn blue"
                                                    onclick="window.location.href = '<?=$this->url('admin-leagues', array('action' => 'deleteMiniLeague', 'id' => $league['id']))?>';">Confirm</button>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <?=$this->translate('There is no leagues')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    var types = [<?="'" . implode("','", \Application\Model\Entities\League::getAvailableTypes()) . "'" ?>];
    var seasons = [];
    <?php foreach ($this->seasons as $i => $season) : ?>
        seasons['<?=$i?>'] = '<?=$season['displayName']?>';
    <?php endforeach; ?>

    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            return tableTimeFilter(jQuery('#leagues-time-filter').val(), aData[3], aData[4]) &&
                tableFilter(jQuery('#leagues-season-filter').val(), aData[2], seasons) &&
                tableFilter(jQuery('#leagues-type-filter').val(), aData[1], types);
        }
    );
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        /* Custom filtering function which will filter data in column four between two values */


        var messages = {perPage: "_MENU_ " + "<?=$this->translate('leagues per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ leagues')?>"};
       var oTable = $('#leagues-table').dataTable({
            "aoColumns": [null, null, null, null, null, {bSortable: false}],
            "aaSorting": [[3,"desc"]],
           // "bFilter": false,
           "bStateSave" : true,
           "iCookieDuration": 60 * 60 * 24 * 365 * 100,
           "aLengthMenu": [[5, 10, 15, 25, 50, 100 , -1], [5, 10, 15, 25, 50, 100, "All"]],
           "iDisplayLength" : App.getDefaultItemsPerPage(),
           "fnStateLoadParams" : function(oSettings, oData){
               oData.oSearch.sSearch = '';
               oData.aaSorting = [];
           },
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
        $('#leagues-type-filter, #leagues-season-filter, #leagues-time-filter').change(function(){
            oTable.fnDraw();
        });
    });
    function tableFilter(index, value, data) {
        if (index == -1) return true;
        return value == data[index];
    }
    function tableTimeFilter(index, startDate, endDate) {
        if (index == -1) return true;
        var startDateTime = Date.parse(startDate);
        var endDateTime = Date.parse(endDate);
        var now = new Date();
        switch (index) {
            case '1':
                return now.getTime() > startDateTime && now.getTime() < endDateTime;
            case '2':
                return now.getTime() < startDateTime;
            case '3':
                return now.getTime() > endDateTime;
        }
        return true;
    }
</script>
<!-- END JAVASCRIPTS -->