<?php
    $title = $this->translate('League Table');
    $this->headTitle($title);
    ?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4>"<?=$this->league->getDisplayName()?>" <?=$title;?></h4>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->leagueUsers)) : ?>
                    <table class="table table-striped table-bordered table-hover" id="leagues-table">
                        <thead>
                        <tr>
                            <th><?=$this->translate('Place');?></th>
                            <th><?=$this->translate('User');?></th>
                            <th><?=$this->translate('Country');?></th>
                            <th><?=$this->translate('Accuracy');?></th>
                            <th><?=$this->translate('Points');?></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->leagueUsers as $user) : ?>
                                <tr>
                                    <td><?=$user['place']?></td>
                                    <td><?=$user['displayName']?></td>
                                    <td><img src="<?=$user['flagImage']?>" itemprop="nationality" alt="<?=$user['country']?>"></td>
                                    <td><?=$user['accuracy']?></td>
                                    <td><?=$user['points']?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <?=$this->translate('There is no participants or played matches in the league')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('participants per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ participants')?>"};
        var oTable = $('#leagues-table').dataTable({
            "aoColumns": [null, null, {bSortable: false}, null, null],
            "aaSorting": [[0,"asc"]],
            "bStateSave" : true,
            "iCookieDuration": 60 * 60 * 24 * 365 * 100,
            "fnStateLoadParams" : function(oSettings, oData){
                oData.oSearch.sSearch = '';
                oData.aaSorting = [];
            },
            // "bFilter": false,
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
    });
</script>
<!-- END JAVASCRIPTS -->