<?php $this->headTitle($this->translate('Predict'));?>
<div role="main" class="two-column-section clearfix">

    <div class="first-column predict">
        <?php if (!empty($this->current)) : ?>
            <section class="carousel-wrap make-prediction">
                <header>
                    <?php if ($this->current['status'] == \Application\Model\Entities\Match::PRE_MATCH_STATUS &&
                                empty($this->current['prediction'])) : ?>
                        <strong class="flag-new-prediction"><span><?=$this->translate('New')?></span></strong>
                    <?php endif; ?>
                    <time class="game-date">
                        <?php print $this->current['localStartTime']->format('D d M h.i a');?>
                        <?php //print strftime('%a %e %b %I.%M %P', $this->current['localStartTime']->getTimestamp()); ?>
                    </time>
                    <ul class="direction-nav">
                        <?php if ($this->ahead > 0) : ?>
                            <li class="prev-match">
                                <a href="<?=$this->url('predict', array('ahead' => $this->ahead != 1 ? $this->ahead - 1 : null));?>"><?=$this->translate('Prev')?> <span><?=$this->translate('match')?></span></a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->ahead < $this->maxAhead + $this->liveMatches - 1) : ?>
                            <li class="next-match">
                                <a href="<?=$this->url('predict', array('ahead' => $this->ahead + 1));?>"><?=$this->translate('Next')?> <span><?=$this->translate('match')?></span></a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </header>
                <div class="make-prediction-content clearfix">
                    <?php if ($this->current['status'] == \Application\Model\Entities\Match::LIVE_STATUS) : ?>
                        <div>
                            <?=$this->translate('Match in progress');?>
                        </div>
                        <div>
                            <?=$this->translate('You predicted');?>
                        </div>
                        <div>
                            <?=$this->current['homeName']; ?> <?=$this->current['homeLogo'];?>
                            <?=$this->current['competitionName']?>
                            <?=$this->current['awayName']; ?> <?=$this->current['awayLogo'];?>
                        </div>
                        <?php if (!empty($this->current['prediction'])) : ?>
                            <div>
                                <table>
                                    <tr>
                                        <td>
                                            <?php foreach ($this->current['prediction']['homeScorers'] as $order => $scorer): ?>
                                                <?=$scorer['playerName'] ? $scorer['playerName'] : '---';?><br/>
                                            <?php endforeach; ?>
                                        </td>
                                        <td>
                                            <?=$this->current['prediction']['homeTeamScore'];?>
                                        </td>
                                        <td>
                                            &nbsp;
                                        </td>
                                        <td>
                                            <?=$this->current['prediction']['awayTeamScore'];?>
                                        </td>
                                        <td>
                                            <?php foreach ($this->current['prediction']['awayScorers'] as $order => $scorer): ?>
                                                <?=$scorer['playerName'] ? $scorer['playerName'] : '---';?><br/>
                                            <?php endforeach; ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($this->current['status'] == \Application\Model\Entities\Match::PRE_MATCH_STATUS) : ?>
                        <form id="make-prediction" method="POST" action="<?=$this->url('predict', array('ahead' => $this->ahead > 0 ? $this->ahead : null))?>">
                            <div class="home-team">
                                <fieldset>
                                    <label for="home-team-score">
                                        <figure>
                                            <img src="<?=$this->clubLogo($this->current['homeLogo'])?>" alt="<?=$this->current['homeName'];?>">
                                            <figcaption>
                                                <?=$this->current['homeName'];?>
                                            </figcaption>
                                        </figure>
                                    </label>
                                    <input type="text" class="required" maxlength="2" name="home-team-score" id="home-team-score" value="<?=$this->current['prediction']['homeTeamScore']?>">
                                </fieldset>
                                <section>
                                    <?php
                                        if (!empty($this->current['prediction']) && !empty($this->current['prediction']['homeScorers']))
                                            foreach ($this->current['prediction']['homeScorers'] as $order => $scorer)
                                                print $this->squadSelect('home-team-scorer-' . $order, $this->current['homeSquad'], $this->translate('Select scorer'), '', $scorer['playerId']);
                                    ?>
                                </section>
                            </div>

                            <div class="league-logo">
                                <img src="/img/league-logo.png" alt="">
                                <em><?=$this->translate('VS')?></em>
                                <span><?=$this->translate('Scorers')?></span>
                            </div>

                            <div class="away-team">
                                <fieldset>
                                    <label for="away-team-score">
                                        <figure>
                                            <img src="<?=$this->clubLogo($this->current['awayLogo'])?>" alt="<?=$this->current['awayName'];?>">
                                            <figcaption>
                                                <?=$this->current['awayName'];?>
                                            </figcaption>
                                        </figure>
                                    </label>
                                    <input type="text" class="required" maxlength="2" name="away-team-score" id="away-team-score" value="<?=$this->current['prediction']['awayTeamScore']?>">
                                </fieldset>
                                <section>
                                    <?php
                                    if (!empty($this->current['prediction']) && !empty($this->current['prediction']['awayScorers']))
                                        foreach ($this->current['prediction']['awayScorers'] as $order => $scorer)
                                            print $this->squadSelect('away-team-scorer-' . $order, $this->current['awaySquad'], $this->translate('Select scorer'), '', $scorer['playerId']);
                                    ?>
                                </section>
                            </div>

                            <div class="buttons-block">
                                <button type="submit">
                                    <?php if (empty($this->current['prediction'])) : ?>
                                        <?=$this->translate('Save prediction')?>
                                    <?php else: ?>
                                        <?=$this->translate('Edit your prediction')?>
                                    <?php endif; ?>
                                </button>
                            </div>
                            <input type="hidden" name="check_key" value="<?=$this->securityKey?>"/>
                        </form>
                        <aside class="competition-countdown" style="display: none">
                            <h4><?=$this->translate('Time left')?></h4>
                            <p>
                                <strong><?=$this->current['startTime']->getTimestamp();?></strong>
                                <?=$this->translate('days hours mins secs')?>
                            </p>
                        </aside>
                        <?php print $this->squadSelect('home-team-scorer', $this->current['homeSquad'], $this->translate('Select scorer'), 'style="display: none"'); ?>
                        <?php print $this->squadSelect('away-team-scorer', $this->current['awaySquad'], $this->translate('Select scorer'), 'style="display: none"'); ?>
                    <?php endif; ?>
                </div>
            </section>
            <section class="match-banner">
                <div class="clearfix">
                    <img src="/img/match-report.png" alt="">
                    <article>
                        <h1>Match report</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur lorum adipiscing elit. Donec tempor dui id quam dapibus commodo. Suspendisse nulla arcu.</p>
<!--                        <footer class="clearfix">-->
<!--                            <h3>Share this</h3>-->
<!--                            <ul class="social-links">-->
<!--                                <li><a href="">like</a></li>-->
<!--                                <li><a href="">tweet</a></li>-->
<!--                                <li><a href="">Pin it</a></li>-->
<!--                            </ul>-->
<!--                        </footer>-->
                    </article>
                </div>
            </section>
        <?php else: ?>
            <?= $this->renderMessages(); ?>
        <?php endif; ?>
    </div>

    <?php echo $this->partial('partials/right-column'); ?>

</div>

<?php if (!$this->getCurrentUser()->getIsActive()):?>
    <?php echo $this->partial('partials/setup-popup', array('form'=>$this->setUpForm));?>
<?php endif;?>

<script type="text/javascript">
    var liveMatchRedirect = '<?=$this->url('predict', array('ahead' => $this->ahead > 0 ? $this->ahead : null))?>';
    var savedHomeScore = <?=!empty($this->current['prediction']) ? $this->current['prediction']['homeTeamScore'] : -1 ?>;
    var savedAwayScore = <?=!empty($this->current['prediction']) ? $this->current['prediction']['awayTeamScore'] : -1 ?>;
    var pageUnloadCopy = "<?=$this->translate('You didn\'t save the prediction.')?>";
</script>
<script type="text/javascript" src="/js/vendor/jquery.countdown.js"></script>
<script type="text/javascript" src="/js/make-prediction.js"></script>