<?php
$title = 'Settings';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('admin-settings'));
        $form->prepare();
        echo $this->form()->openTag($form);
        $elements = $form->getElements();
        ?>
        <div class="form">
            <div class="row-fluid">
                <?php foreach ($elements as $element) :
                    $type = $element->getAttribute('type');
                    $hint = $element->getAttribute('hint');
                    if ($type != 'submit') : ?>
                        <div class="control-group form-horizontal">
                            <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                            <div class="controls">
                                <?=$this->formElement($element);?>
                                <?php if (!empty($hint)) : ?>
                                    <span class="help-inline"><?=$hint?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; endforeach; ?>
                <div class="form-actions">
                    <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                    <button type="button" class="btn" onclick="this.form.reset();">Cancel</button>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-colorpicker/css/colorpicker.css" />
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        $('.colorpicker-default').colorpicker({
            format: 'hex'
        });
    });
</script>
<!-- END JAVASCRIPTS -->