<?php
   $this->headTitle($this->title);
?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('admin-content-languages', $this->url_params));
echo $this->form()->openTag($form);
?>
<div class="row-fluid form-vertical">

    <div class="control-group">
        <label class="control-label"><?php echo $this->translate('Language Countries');?></label>

        <div class="controls">
            <?php echo $this->formSelect($form->get('countries'));?>
            <?php echo $this->formLabel($form->get('language_code'));?>
            <?php echo $this->formElement($form->get('language_code'));?>
            <?php echo $this->formLabel($form->get('display_name'));?>
            <?php echo $this->formElement($form->get('display_name'));?>
        </div>

    </div>
</div>
<div class="portlet box green">
    <div class="portlet-title">
        <h4><i class="icon-reorder"></i><?php echo $this->translate('Translations');?></h4>
        <div class="tools">
            <a class="collapse" href="javascript:;"></a>
        </div>
    </div>
    <div class="portlet-body" style="display:block;">
        <?php $strings = $this->form->get('strings')->getValue();?>
        <?php if (!empty($this->strings)):?>
            <table class="table table-striped table-bordered table-hover" id="language-table">
                <thead>
                <tr>
                    <th style="text-align: center;"><h3><strong><?php echo $form->get('display_name')->getValue();?></strong></h3></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->strings as $id=>$string):?>
                    <tr class="odd gradeX">
                        <td>
                            <label><strong><?php echo $this->escapeHtml($id);?></strong></label>
                            <?php
                            $value = ($this->url_params['action'] == 'edit') ? $string : '';
                            if (!empty($strings[$id])){
                                $value = $strings[$id];
                            }
                            ?>
                            <textarea rows="2" cols="10" style="position:relative;width:99%;"name="strings[<?php echo $id;?>]"><?php echo $value;?></textarea>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        <?php else:?>
            <p><?php echo $this->translate('Nothing to translate');?></p>
        <?php endif;?>
    </div>
</div>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag();?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery.fn.dataTableExt.oApi.fnGetHiddenNodes = function ( oSettings )
    {
        /* Note the use of a DataTables 'private' function thought the 'oApi' object */
        var anNodes = this.oApi._fnGetTrNodes( oSettings );
        var anDisplay = $('tbody tr', oSettings.nTable);

        /* Remove nodes which are being displayed */
        for ( var i=0 ; i<anDisplay.length ; i++ )
        {
            var iIndex = jQuery.inArray( anDisplay[i], anNodes );
            if ( iIndex != -1 )
            {
                anNodes.splice( iIndex, 1 );
            }
        }

        /* Fire back the array to the caller */
        return anNodes;
    };
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var language_table = $('#language-table');
        var oTable = language_table.dataTable({
            "aoColumns": [null],
            "bStateSave" : true,
            "iCookieDuration": 60 * 60 * 24 * 365 * 100,
            "fnStateLoadParams" : function(oSettings, oData){
                oData.oSearch.sSearch = '';
                oData.aaSorting = [];
            },
            "aLengthMenu": [[5, 10, 15, 25, 50, 100 , -1], [5, 10, 15, 25, 50, 100, "All"]],
            "iDisplayLength" : 10
        });
        jQuery('#language').submit(function(){
            jQuery(oTable.fnGetHiddenNodes()).find('textarea').appendTo(this).hide();
        });
    });
</script>
<!-- END JAVASCRIPTS -->