<?php
   $this->headTitle($this->title);
?>

<div class="row-fluid form-vertical">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$this->translate($this->title)?></h4>
            </div>
                <div class="portlet-body form">
                    <div class="control-group">
                        <label class="control-label"><?php echo $this->translate('Language Countries');?></label>
                        <?php
                            $form = $this->form;
                            $form->prepare();
                            $form->setAttribute('action', $this->url('admin-content-languages', $this->url_params));
                            echo $this->form()->openTag($form);
                        ?>
                        <div class="controls">
                            <?php echo $this->formSelect($form->get('countries'));?>
                            <?php echo $this->formLabel($form->get('language_code'));?>
                            <?php echo $this->formElement($form->get('language_code'));?>
                            <?php echo $this->formLabel($form->get('display_name'));?>
                            <?php echo $this->formElement($form->get('display_name'));?>
                            <label><?php echo $this->translate('Language Strings');?></label>
                            <?php $strings = $this->form->get('strings')->getValue();?>
                            <?php if (!empty($this->strings)):?>
                                <?php foreach($this->strings as $id=>$string):?>
                                    <label><?php echo $id;?></label>
                                    <?php
                                        $value = ($this->url_params['action'] == 'edit') ? $string : '';
                                        if (!empty($strings[$id])){
                                            $value = $strings[$id];
                                        }
                                    ?>
                                    <textarea rows="2" cols="50" name="strings[<?php echo $id;?>]"><?php echo $value;?></textarea>
                                <?php endforeach;?>
                            <?php endif;?>
                        </div>
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->form()->closeTag();?>
                    </div>
                </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>

<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->