<?php
$title = 'Languages';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$this->translate('Languages')?></h4>
                <div class="actions">
                    <a href="<?=$this->url('admin-content-languages', array('action' => 'add'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Add')?></a>
                </div>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->languages)) : ?>
                <table class="table table-striped table-bordered table-hover" id="seasons-table">
                    <thead>
                    <tr>
                        <th><?=$this->translate('Name')?></th>
                        <th><?=$this->translate('Code')?></th>
                        <th><?=$this->translate('Default')?></th>
                        <th style="width: 60px"></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->languages as $language) : ?>
                    <tr class="odd gradeX">
                        <td><?=$language['displayName']?></td>
                        <td><?=$language['languageCode']?></td>
                        <td><?=$language['isDefault'] ? 'Yes' : 'No'?></td>
                        <td>
                            <a href="<?=$this->url('admin-content-languages', array('action' => 'edit', 'language' => $language['id']))?>" class="btn mini blue">
                                <i class="icon-edit"></i>
                                <?=$this->translate('Edit')?>
                            </a>
                        </td>
                    </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <?=$this->translate('There is no languages created')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->