<?php
$title = $this->translate('Delete Account');
$this->headTitle($title);
?>
<div role="main">
    <div class="one-column message information delete-account">
        <h1><?php echo $title;?></h1>
        <article class="user-content">
            <form action="<?php echo $this->url('delete-account');?>" method="post" id="delete-account">
                <?php $errors = $this->renderMessages();?>
                <?php if (!empty($errors)):?>
                    <div class="form-errors">
                        <p><?php echo $errors;?></p>
                    </div>
                <?php endif;?>
                <p><?php echo $this->translate('Are you sure you want to delete your account?');?></p>
                <p class="note"><?php echo $this->translate('<strong>Note:</strong> all data associated with your account will be lost and non-recoverable.');?></p>
                <p class="buttons-block">
                    <button type="submit" class="pink" autocomplete="off"><?php echo $this->translate('Confirm and delete account');?></button>
                </p>
                <input type="hidden" value="<?php echo base64_encode($this->user->getId());?>" name="user_id"/>
            </form>
        </article>

    </div>
</div>