<?php
$title = $this->translate('Settings');
$this->headTitle($title);
?>
<div role="main" class="registration-section">
    <h1><?php echo $this->escapeHtml($title);?></h1>
<?php $errors = $this->renderMessages();?>
<?php if (!empty($errors)):?>
    <div class="form-errors">
        <p><?php echo $errors;?></p>
    </div>
<?php endif;?>
<?php if (!$this->user->getFacebookId()):?>
<aside class="connect-facebook clearfix">
    <div>
        <h2>Connect your account for a one click login</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla metus ligula, facilisis id scelerisque in, eleifend ut elit. Aenean a facilisis augue. </p>
    </div>
    <?php echo $this->renderFacebookButton($this->translate('Connect with Facebook'));?>
</aside>
<?php
    $this->passwordForm->prepare();
    $this->passwordForm->setAttribute('action', $this->url('user-settings'));
    echo $this->form()->openTag($this->passwordForm);
?>
<section>
    <div>
        <h2><?php echo $this->translate('Change your Password');?></h2>
    </div>
    <?php if ($this->passwordForm->getInputFilter()->getMessages()):?>
        <div class="form-errors">
            <?php
            echo $this->formElementerrors($this->passwordForm->get('password'));
            echo $this->formElementerrors($this->passwordForm->get('new_password'));
            echo $this->formElementerrors($this->passwordForm->get('confirm_new_password'));
            ?>
        </div>
    <?php endif;?>
    <div>
        <?php echo $this->formLabel($this->passwordForm->get('password')); ?>
        <?php  echo $this->formElement($this->passwordForm->get('password')); ?>
    </div>
    <div>
        <?php echo $this->formLabel($this->passwordForm->get('new_password')); ?>
        <?php  echo $this->formElement($this->passwordForm->get('new_password')); ?>
    </div>
    <div>
        <?php echo $this->formLabel($this->passwordForm->get('confirm_new_password')); ?>
        <?php  echo $this->formElement($this->passwordForm->get('confirm_new_password')); ?>
    </div>
</section>
<section class="buttons-block clearfix">
    <div>
        <button type="submit"><?php echo $this->translate('Save changes');?></button>
    </div>
</section>
<?php
    echo $this->formHidden($this->passwordForm->get('type'));
    echo $this->form()->closeTag();
?>
<?php
    $this->emailForm->prepare();
    $this->emailForm->setAttribute('action', $this->url('user-settings'));
    echo $this->form()->openTag($this->emailForm);
?>

<section>
    <div>
        <h2><?php echo $this->translate('Change your email addresses');?></h2>
    </div>
    <?php if ($this->emailForm->getInputFilter()->getMessages()):?>
    <div class="form-errors">
        <?php
        echo $this->formElementerrors($this->emailForm->get('email'));
        echo $this->formElementerrors($this->emailForm->get('confirm_email'));
        ?>
    </div>
    <?php endif;?>
    <div>
        <?php echo $this->formLabel($this->emailForm->get('email')); ?>
        <?php  echo $this->formElement($this->emailForm->get('email')); ?>
    </div>
    <div>
        <?php echo $this->formLabel($this->emailForm->get('confirm_email')); ?>
        <?php  echo $this->formElement($this->emailForm->get('confirm_email')); ?>
    </div>
</section>
<section class="buttons-block clearfix">
    <div>
        <button type="submit"><?php echo $this->translate('Save changes');?></button>
    </div>
</section>
<?php
    echo $this->formHidden($this->emailForm->get('type'));
    echo $this->form()->closeTag();
?>
<div class="settings-change-email">
<h3><?php echo $this->translate('Change your email addresses');?></h3>
    <?php
        $this->emailForm->prepare();
        $this->emailForm->setAttribute('action', $this->url('user-settings'));
        echo $this->formElementerrors($this->emailForm->get('email'));
        echo $this->formElementerrors($this->emailForm->get('confirm_email'));
        echo $this->form()->openTag($this->emailForm);
        echo $this->formLabel($this->emailForm->get('email'));
        echo $this->formElement($this->emailForm->get('email'));
        echo $this->formLabel($this->emailForm->get('confirm_email'));
        echo $this->formElement($this->emailForm->get('confirm_email'));
        echo $this->formHidden($this->emailForm->get('type'));
        echo $this->formSubmit($this->emailForm->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>
<div class="settings-change-display-name">
<h3><?php echo $this->translate('Change your display name');?></h3>
    <?php
    $this->displayNameForm->prepare();
    $this->displayNameForm->setAttribute('action', $this->url('user-settings'));
    echo $this->formElementerrors($this->displayNameForm->get('display_name'));
    echo $this->form()->openTag($this->displayNameForm);
    echo $this->formLabel($this->displayNameForm->get('display_name'));
    echo $this->formElement($this->displayNameForm->get('display_name'));
    echo $this->formHidden($this->displayNameForm->get('type'));
    echo $this->formSubmit($this->displayNameForm->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
<div class="settings-change-avatar">
<h3><?php echo $this->translate('Change your avatar');?></h3>
    <img src="<?php echo $this->user->getAvatar()->getSmallImagePath();?>" alt="<?php echo $this->translate('User avatar');?>"/>
    <?php
    $this->avatarForm->prepare();
    $this->avatarForm->setAttribute('action', $this->url('user-settings'));
    echo $this->formElementerrors($this->avatarForm->get('avatar'));
    echo $this->form()->openTag($this->avatarForm);
    echo $this->formLabel($this->avatarForm->get('avatar'));
    echo $this->formElement($this->avatarForm->get('avatar'));
    echo $this->formHidden($this->avatarForm->get('type'));
    echo $this->formSubmit($this->avatarForm->get('submit'));?>
    <?php echo $this->translate('Or choose from selection');?>
    <?php echo $this->renderDefaultAvatars();?>
   <?php echo $this->form()->closeTag();  ?>
</div>
<?php endif;?>
<?php if ($this->user->getFacebookId()):?>
    <img src="http://graph.facebook.com/<?php echo $this->user->getFacebookId();?>/picture?width=72&height=72" />
<?php endif;?>
<div class="settings-regional-settings">
    <h3><?php echo $this->translate('Regional Settings');?></h3>
    <div class="country">
        <?php echo $this->translate('Your country');?>
        <?php echo $this->user->getCountry()->getName();?>
        <p>
            <?php echo $this->translate('You cannot change your country in the middle of a league. We will prompt you to re-confirm your details at the start of the the league.');?>
        </p>
    </div>
    <div class="language">
        <?php
        $this->languageForm->prepare();
        $this->languageForm->setAttribute('action', $this->url('user-settings'));
        echo $this->formElementerrors($this->languageForm->get('language'));
        echo $this->form()->openTag($this->languageForm);
        echo $this->formLabel($this->languageForm->get('language'));
        echo $this->formElement($this->languageForm->get('language'));
        echo $this->formHidden($this->languageForm->get('type'));
        echo $this->formSubmit($this->languageForm->get('submit'));
        echo $this->form()->closeTag();
        ?>
    <div>
</div>
<div class="settings-email-settings">
    <h3><?php echo $this->translate('Email Settings');?></h3>
    <?php
    $this->emailSettingsForm->prepare();
    $this->emailSettingsForm->setAttribute('action', $this->url('user-settings'));
    echo $this->form()->openTag($this->emailSettingsForm);
    echo $this->formLabel($this->emailSettingsForm->get('term1'));
    echo $this->formElement($this->emailSettingsForm->get('term1'));
    echo $this->formLabel($this->emailSettingsForm->get('term2'));
    echo $this->formElement($this->emailSettingsForm->get('term2'));
    echo $this->formHidden($this->emailSettingsForm->get('type'));
    echo $this->formSubmit($this->emailSettingsForm->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
<div class="settings-public-profile">
    <h3><?php echo $this->translate('Profile Type');?></h3>
    <?php
    $this->publicProfileForm->prepare();
    $this->publicProfileForm->setAttribute('action', $this->url('user-settings'));
    echo $this->form()->openTag($this->publicProfileForm);
    echo $this->formLabel($this->publicProfileForm->get('is_public'));
    echo $this->formElement($this->publicProfileForm->get('is_public'));
    echo $this->formHidden($this->publicProfileForm->get('type'));
    echo $this->formSubmit($this->publicProfileForm->get('submit'));
    echo $this->form()->closeTag();
    ?>
</div>
<div class="delete-account">
    <a href="<?php echo $this->url('delete-account');?>"><?php echo $this->translate('Delete Account');?></a>
</div>
</div>
<script type="text/javascript">
    var turnOffCustomStylePoint = 767;

    //Password form
    var passwordOptions = {

        responsiveAt: turnOffCustomStylePoint,
        onFail: function(){},
        onSuccess: function(){},
        inputs: {
            'password': {
                filters: 'required max',
                data: { max: 15 }
            },
            'new_password': {
                filters: 'required pass max',
                data: { max: 15 }
            },
            'confirm_new_password': {
                filters: 'required max equalto',
                data: {
                    max: 15,
                    equalto : '#new-password'
                }
            }
        }
    };

    if ($(document).width() <  turnOffCustomStylePoint)
        registerOptions.disableCustom = 'select';

    $('#settings-change-password').idealforms(passwordOptions).data('idealforms');
</script>