<?php
$title = $this->translate('Players');
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$title;?></h4>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->players)) : ?>
                <div class="datatable-filter">
                    <label>
                        <select id="players-filter">
                             <option value="-1"><?php echo $this->translate('All');?></option>
                             <option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
                             <option value="0"><?php echo $this->translate('Inactive');?></option>
                        </select>
                        <?php echo $this->translate('filter by status');?>
                    </label>
                </div>
                <table class="table table-striped table-bordered table-hover" id="players-table">
                    <thead>
                    <tr>
                        <th><?=$this->translate('Name');?></th>
                        <th><?=$this->translate('Team');?></th>
                        <th><?=$this->translate('Position');?></th>
                        <th><?=$this->translate('Shirt Number');?></th>
                        <th><?=$this->translate('Avatar');?></th>
                        <th><?=$this->translate('Background Image');?></th>
                        <th><?=$this->translate('Status');?></th>
                        <th style="width: 60px"><?php echo $this->translate('Action');?></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->players as $player) : ?>
                    <tr class="odd gradeX <?php echo (empty($player['backgroundImagePath']) || empty($player['imagePath']) ? ' new-item' : '');?>">
                        <td><?=$player['displayName'];?></td>
                        <td><?=$player['team_name'];?></td>
                        <td><?=$player['position'];?></td>
                        <td><?=$player['shirtNumber'];?></td>
                        <td>
                            <?php if (!empty($player['imagePath'])):?>
                                <a href="<?=$player['imagePath'];?>" target="_blank"><?php echo $this->translate('Open');?></a>
                            <?php endif;?>
                        </td>
                        <td>
                            <?php if (!empty($player['backgroundImagePath'])):?>
                            <a href="<?=$player['backgroundImagePath'];?>" target="_blank"><?php echo $this->translate('Open');?></a>
                            <?php endif;?>
                        </td>
                        <td>
                           <?php
                                $statuses = array('active', 'inactive');

                            ?>
                            <?php echo $statuses[rand(0,1)];?>
                        </td>
                        <td>
                            <a href="<?=$this->url('admin-players', array('action' => 'edit', 'player' => $player['id']))?>" class="btn mini blue">
                                <i class="icon-edit"></i>
                                <?=$this->translate('Edit')?>
                            </a>
                        </td>
                    </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <?=$this->translate('There is no players')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">

    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            var status = jQuery('#players-filter').val();
            var value = aData[6];
            switch(status){
                case '1':{
                    if (value != 'active'){
                        return false;
                    }
                    break;
                }
                case '0':{
                    if (value != 'inactive'){
                        return false;
                    }
                    break;
                }
            }
            return true;
        }
    );
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        /* Custom filtering function which will filter data in column four between two values */


        var messages = {perPage: "_MENU_ " + "<?=$this->translate('players per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ clubs')?>"};
       var oTable = $('#players-table').dataTable({
            "aoColumns": [null, null,null, null, null,null,null,{bSortable: false}],
           // "aaSorting": aaSorting,
           // "bFilter": false,
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
        $('#players-filter').change(function(){
            oTable.fnDraw();
        });
    });
</script>
<!-- END JAVASCRIPTS -->