<?php
$this->headTitle($this->title);
?>
<div class="container-fluid">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('admin-clubs', $this->params));
    $elements = $form->getElements();
    echo $this->form()->openTag($form);
    $elements = $form->getElements();
    ?>
    <div class="form">
        <div class="row-fluid">
            <?php foreach($elements as $element):
            $type = $element->getAttribute('type');
            $hint = $element->getAttribute('hint');
            ?>
            <?php if ($element->getAttribute('name') != 'submit'):?>
                <div class="control-group form-horizontal">
                    <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                    <div class="controls">
                        <?php if ($type == 'text') : ?>
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium check-values" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?>data-changed="0" data-original_value="<?=$element->getValue();?>" value="<?=$element->getValue();?>"/>
                            </div>
                        <?php elseif($type == 'file'): $image = $element->getValue();?>
                            <div class="fileupload fileupload-<?=(!empty($image) ? 'exists' : 'new')?>" data-provides="fileupload">
                                <div class="input-append">
                                    <div class="uneditable-input">
                                        <i class="icon-file fileupload-exists"></i>
                                        <span class="fileupload-preview"><?=(!empty($image) ? '<input type="hidden" name="' . $element->getAttribute('name') . '[stored]" value="1"/><a target="_blank" href="' . $image . '">Open</a>' : '')?></span>
                                    </div>
                                        <span class="btn btn-file">
                                            <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                            <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                            <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                        </span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if (!empty($hint)) : ?>
                            <span class="help-inline"><?=$hint?></span>
                        <?php endif; ?>
                    </div>
                </div>
                <?php else:?>
                <div class="form-actions">
                    <a href="#deleteModal" role="button" class="btn blue update-club" data-blocked="<?php echo (!empty($this->isBlocked) ? 1 : 0);?>" data-toggle="modal">
                        <i class="icon-ok"></i> <?=$this->translate($element->getValue());?>
                    </a>
                    <?php if ($this->isBlocked):?>
                    <a href="<?php echo $this->url('admin-clubs', array('action'=> 'syncwithfeed', 'club'=>(!empty($this->params['club']) ? $this->params['club'] : null )))?>" role="button" class="btn blue">
                        <i class="icon-ok"></i> <?=$this->translate('Sync with feed');?>
                    </a>
                    <?php endif;?>
                    <button type="button" class="btn reset">Cancel</button>

                </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
     <div>
     <?php echo $this->form()->closeTag();?>
</div>
</div>
<?php if (!$this->isBlocked):?>
    <div id="deleteModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h3 id="myModalLabel3"><?php echo $this->translate('Please Confirm')?></h3>
        </div>
        <div class="modal-body">
            <p><?php echo $this->translate("If you'd like to change club name or short name you have to be aware that it will override the data feed permanently.");?></p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close');?></button>
            <button data-dismiss="modal" class="btn blue"
                    onclick="$('#club').submit();">
                <?php echo $this->translate('Confirm');?>
            </button>
        </div>
    </div>
<?php endif;?>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">

    jQuery(document).ready(function() {
        $('.update-club').click(function(e){
              if (!$(this).data('blocked')){
                  var changed = false;
                  $('.check-values').each(function(){
                        if ($(this).data('changed')){
                            changed = true;
                        }
                  });
                  if (changed){
                      return true;
                  }else{
                      $('#club').submit();
                      return false;
                  }
              }else{
                  $('#club').submit();
                  return false;
              }
        });

        $('.check-values').change(function(){
           var val = $(this).val();
           if (val != $(this).data('original_value')){
               $(this).data('changed', 1);
           }else{
               $(this).data('changed', 0);
           }
        });
        $('button.reset').click(function(e){
            e.preventDefault();
            this.form.reset();
        });
        App.init(); // initlayout and core plugins
    });
</script>
<!-- END JAVASCRIPTS -->