<?php
$title = 'Clubs';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><?=$this->translate('Clubs')?></h4>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->clubs)) : ?>
                <select id="club-emblem-filter">
                     <option value="-1"><?php echo $this->translate('All');?></option>
                     <option value="1"><?php echo $this->translate('New');?></option>
                </select>
                <table class="table table-striped table-bordered table-hover" id="clubs-table">
                    <thead>
                    <tr>
                        <th><?=$this->translate('Name')?></th>
                        <th><?=$this->translate('Short Name')?></th>
                        <th><?=$this->translate('Founded')?></th>
                        <th><?=$this->translate('Logo')?></th>
                        <th style="width: 60px"><?=$this->translate('Action')?></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->clubs as $club) : ?>
                    <tr class="odd gradeX <?php echo (empty($club['logoPath']) ? ' new-item' : '');?>">
                        <td><?=$club['displayName'];?></td>
                        <td><?=$club['shortName'];?></td>
                        <td><?=$club['founded'];?></td>
                        <td>
                            <?php if (!empty($club['logoPath'])):?>
                                <a href="<?=$club['logoPath'];?>" target="_blank"><?php echo $this->translate('Open');?></a>
                            <?php endif;?>
                        </td>
                        <td>
                            <a href="<?=$this->url('admin-clubs', array('action' => 'edit', 'club' => $club['id']))?>" class="btn mini blue">
                                <i class="icon-edit"></i>
                                <?=$this->translate('Edit')?>
                            </a>
                        </td>
                    </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <?=$this->translate('There is no clubs')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/css/custom.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">

    jQuery.fn.dataTableExt.afnFiltering.push(
        function( oSettings, aData, iDataIndex ) {
            var emblems = jQuery('#club-emblem-filter').val();
            //Display All
            if (emblems == "-1"){
                return true;
            }
            //Display New
            if (emblems == "1"){
                 var logo = aData[3];
                 if (logo != ''){
                     return false;
                 }
            }
            return true;
        }
    );
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        /* Custom filtering function which will filter data in column four between two values */


        var messages = {perPage: "_MENU_ " + "<?=$this->translate('clubs per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ clubs')?>"};
       var oTable = $('#clubs-table').dataTable({
            "aoColumns": [null, null, null, null, {bSortable: false}],
           // "aaSorting": aaSorting,
           // "bFilter": false,
            "oLanguage": {
                "sLengthMenu": messages.perPage,
                "oPaginate": {
                    "sPrevious": messages.prevLink,
                    "sNext": messages.nextLink
                },
                "sInfo": messages.showingLabel
            }
        });
        $('#club-emblem-filter').change(function(){
            oTable.fnDraw()
        });
    });
</script>
<!-- END JAVASCRIPTS -->