<?php
$title = $this->translate('Registration');
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<?php if(!empty($flashMessages)) : ?>
<ul>
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>

<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('registration', array('action' => 'index')));

echo $this->form()->openTag($form);
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('confirm_email'));
echo $this->formRow($form->get('password'));?>
<div class="password-meter">
    <div class="password-meter-message"> </div>
    <div class="password-meter-bg">
        <div class="password-meter-bar"></div>
    </div>
</div>
<?php echo $this->formRow($form->get('confirm_password'));
echo $this->formRow($form->get('country'));
echo $this->formRow($form->get('day'));
echo $this->formRow($form->get('month'));
echo $this->formRow($form->get('year'));
echo $this->formHidden($form->get('date_of_birth'));
echo $this->formRow($form->get('gender'));
echo $this->formRow($form->get('display_name'));
echo $this->formRow($form->get('avatar'));
?>
<?php //TODO set const for default images; ?>
<label>
    <input type="radio" value="1" <?php echo (is_null($this->default_avatar) || $this->default_avatar == '1') ? 'checked="checked"' : '';?> name="default_avatar"/>
    <img src="/img/avatar/small/user_default_1.jpg" alt="Default avatar #1">
</label>
<label>
    <input type="radio" value="2" <?php echo ($this->default_avatar == '2') ? 'checked="checked"' : '';?> name="default_avatar"/>
    <img src="/img/avatar/small/user_default_2.jpg" alt="Default avatar #2">
</label>
<label>
    <input type="radio" value="3" <?php echo ($this->default_avatar == '3') ? 'checked="checked"' : '';?> name="default_avatar"/>
    <img src="/img/avatar/small/user_default_3.jpg" alt="Default avatar #3">
</label>
<label>
    <input type="radio" value="4" <?php echo ($this->default_avatar == '4') ? 'checked="checked"' : '';?> name="default_avatar"/>
    <img src="/img/avatar/small/user_default_4.jpg" alt="Default avatar #4">
</label>

<?php

echo $this->formRow($form->get('term1'));
echo $this->formRow($form->get('term2'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();

?>
<?php echo $this->renderFacebookButton();?>
