<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9 ie8"> <![endif]-->
<!--[if IE 9]>         <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('Set Up') . ' - ' . $this->getAppCLub()->getDisplayName();?></title>
    <meta name="description" content="">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="/css/normalize.min.css">
    <link rel="stylesheet" href="/css/jquery.idealforms.min.css">

    <link rel="stylesheet" type="text/css" href="/css/styles.css">
    <script src="/js/vendor/less.js" type="text/javascript"></script>
    <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="css/ie.css">
    <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->


</head>
<body class="inner-page">
<div id="setup-dialog" class="dialog setup-mobile">
    <?php echo $this->partial('partials/setup-form', array('form'=>$this->form));?>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
<script src="/js/vendor/jquery.idealforms.min.js"></script>
<script src="/js/setup-dialog.js"></script>
</body>
</html>
