<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9 ie8"> <![endif]-->
<!--[if IE 9]>         <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('Set Up');?></title>
    <meta name="description" content="">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="/css/normalize.min.css">
    <link rel="stylesheet" href="/css/jquery.idealforms.min.css">

    <link rel="stylesheet/less" type="text/css" href="css/styles.less">
    <script src="/js/vendor/less.js" type="text/javascript"></script>
    <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="css/ie.css">
    <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->


</head>
<body class="inner-page">
<div id="setup-dialog" class="dialog setup-mobile">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('setup'));?>
    <?php echo $this->form()->openTag($form);?>
    <header>
        <p><?php echo $this->translate('Just one more thing');?></p>
    </header>
    <section>
        <h1><?php echo $this->translate('Are these details correct?');?></h1>
        <p><?php echo $this->translate('We need to know your region su we can make sure you are antered into the right league.');?></p>
        <p class="note"><?php echo $this->translate('Note: once confirmed, you will not be able to change these settings until next season');?></p>
        <?php $errors = $this->renderMessages();?>
        <?php if ($errors):?>
        <div class="form-errors">
            <?php if (!empty($errors)):?>
            <p><?php echo $errors;?></p>
            <?php endif;?>
        </div>
        <?php endif;?>
        <fieldset>
            <div>
                <?php echo $this->formLabel($form->get('region'));?>
                <?php echo $this->formSelect($form->get('region'));?>
            </div>
            <div>
                <div>
                    <?php echo $this->formLabel($form->get('language'));?>
                    <?php echo $this->formSelect($form->get('language'));?>
                </div>
            </div>
        </fieldset>
    </section>
    <footer>
        <button id="confirm" class="pink" type="submit"><?php echo $this->translate('Confirm and start playing');?></button>
        <?php echo $this->formHidden($form->get('csrf'));?>
    </footer>
    <?php echo $this->form()->closeTag();?>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
<script src="/js/vendor/jquery.idealforms.min.js"></script>
<script src="/js/setup-dialog.js"></script>
</body>
</html>
