<?php
$title = 'Default Skin';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="tabbable tabbable-custom boxless">
            <div class="tab-content">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('admin-content-default-skin'));
                $form->prepare();
                echo $this->form()->openTag($form);
                $elements = $form->getElements();
                ?>
                <div class="form">
                    <div class="row-fluid">
                        <?php
                        foreach ($elements as $element) :
                            $type = $element->getAttribute('type');
                            $hint = $element->getAttribute('hint');
                            $image = $element->getValue() != null && $element->getValue() ? $element->getValue() : false;
                            if ($type != 'submit') : ?>
                                <div class="control-group form-horizontal">
                                    <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                                    <div class="controls">
                                        <?php if ($type == 'file') : ?>
                                            <div class="fileupload fileupload-<?=(!empty($image) ? 'exists' : 'new')?>" data-provides="fileupload">
                                                <div class="input-append">
                                                    <div class="uneditable-input">
                                                        <i class="icon-file fileupload-exists"></i>
                                                        <span class="fileupload-preview">
                                                            <?php if(!empty($image)) : ?>
                                                                <input type="hidden" name="<?=$element->getAttribute('name')?>[stored]" value="1"/>
                                                                <a href="<?=$image?>" target="_blank">Open</a>
                                                            <?php endif; ?>
                                                        </span>
                                                    </div>
                                                    <span class="btn btn-file">
                                                        <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                                        <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                                        <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                                    </span>
                                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                        <?php if (!empty($hint)) : ?>
                                            <span class="help-inline"><?=$hint?></span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; endforeach; ?>
                        <?php echo $this->renderLanguageFieldsets($this->form->getFieldsets(), false);?>
                        <div class="form-actions">
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                            <button type="button" class="btn reset"><?php echo $this->translate('Reset');?></button>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-colorpicker/css/colorpicker.css" />
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        $('.m-wrap').colorpicker({
            format: 'hex'
        });
        $('button.reset').click(function(e){
            e.preventDefault();
            this.form.reset();
        });
    });
</script>