<?php
$title = 'Footer Images';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="tabbable tabbable-custom boxless">
            <ul class="nav nav-tabs">
                <?php foreach ($this->regions as $i => $region) : ?>
                <li <?= ($region['id'] == $this->activeRegion->getId() ? ' class="active"' : '')?>>
                    <a href="<?=$this->url('admin-content-footer-images', array('region' => $region['id']))?>"><?=$region['displayName']?></a>
                </li>
                <?php endforeach; ?>
            </ul>
            <div class="tab-content">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('admin-content-footer-images', array('region' => $this->activeRegion->getId())));
                $form->prepare();
                echo $this->form()->openTag($form);
                $elements = $form->getElements();
                ?>
                <div class="form">
                <div class="row-fluid">
                    <?php
                    foreach ($elements as $element) :
                        $type = $element->getAttribute('type');
                        $hint = $element->getAttribute('hint');
                        if ($type != 'submit') : ?>
                            <div class="control-group form-horizontal">
                                <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                                <div class="controls">
                                    <?php if ($type == 'file') : ?>
                                    <div class="fileupload fileupload-new" data-provides="fileupload">
                                        <div class="input-append">
                                            <div class="uneditable-input">
                                                <i class="icon-file fileupload-exists"></i>
                                                <span class="fileupload-preview">
                                                </span>
                                            </div>
                                            <span class="btn btn-file">
                                                <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                                <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                                <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                            </span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                    <?php if (!empty($hint)) : ?>
                                        <span class="help-inline"><?=$hint?></span>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif; endforeach; ?>
                        <div class="form-actions">
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <h4><i class="icon-user"></i><?=$this->translate('Footer Images')?></h4>
                            </div>
                            <div class="portlet-body">
                                <?php if (!empty($this->footerImages)) : ?>
                                <table class="table table-striped table-bordered table-hover" id="seasons-table">
                                    <thead>
                                    <tr>
                                        <th><?=$this->translate('Image')?></th>
                                        <th style="width: 150px"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->footerImages as $image) : ?>
                                    <tr class="odd gradeX">
                                        <td>
                                            <img src="<?=$image['footerImage']?>" alt=""/>
                                        </td>
                                        <td>
                                            <a href="#deleteModal<?=$image['id']?>" role="button" class="btn btn-warning mini red" data-toggle="modal">
                                                <i class="icon-trash"></i>
                                                <?=$this->translate('Delete')?>
                                            </a>
                                            <div id="deleteModal<?=$image['id']?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h3 id="myModalLabel3">Please Confirm</h3>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to delete this footer image?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                                    <button data-dismiss="modal" class="btn blue"
                                                        onclick="window.location.href = '<?=$this->url('admin-content-footer-images', array('action' => 'deleteFooterImage', 'image' => $image['id'], 'region' => $this->activeRegion->getId()))?>';">Confirm</button>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php else: ?>
                                <?=$this->translate('There is no footer images added')?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        TableManaged.init();
    });
</script>
<!-- END JAVASCRIPTS -->