<?php
$title = 'Footer Socials';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="tabbable tabbable-custom boxless">
            <ul class="nav nav-tabs">
                <?php foreach ($this->languages as $i => $language) : ?>
                <li <?= ($language['id'] == $this->activeLanguage->getId() ? ' class="active"' : '')?>>
                    <a href="<?=$this->url('admin-content-footer-socials', array('language' => $language['id']))?>"><?=$language['displayName']?></a>
                </li>
                <?php endforeach; ?>
            </ul>
            <div class="tab-content">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="portlet box grey">
                            <div class="portlet-title">
                                <h4><?=$this->translate('Footer Socials')?></h4>
                                <div class="actions">
                                    <a href="<?=$this->url('admin-content-footer-socials', array('language' => $this->activeLanguage->getId(),'action' => 'addFooterSocial'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Add')?></a>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <?php if (!empty($this->footerSocials)) : ?>
                                <table class="table table-striped table-bordered table-hover" id="seasons-table">
                                    <thead>
                                    <tr>
                                        <th style="width: 50px"><?=$this->translate('Order')?></th>
                                        <th><?=$this->translate('URL')?></th>
                                        <th><?=$this->translate('Copy')?></th>
                                        <th><?=$this->translate('Icon')?></th>
                                        <th style="width: 150px"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->footerSocials as $social) : ?>
                                    <tr class="odd gradeX">
                                        <td><?=$social['order']?></td>
                                        <td><?=$social['url']?></td>
                                        <td><?=$social['copy']?></td>
                                        <td>
                                            <img src="<?=$social['icon']?>" alt=""/>
                                        </td>
                                        <td>
                                            <a href="<?=$this->url('admin-content-footer-socials', array('action' => 'editFooterSocial', 'social' => $social['order'], 'language' => $this->activeLanguage->getId()))?>" class="btn mini blue">
                                                <i class="icon-edit"></i>
                                                <?=$this->translate('Edit')?>
                                            </a>
                                            <a href="#deleteModal<?=$social['order']?>" role="button" class="btn btn-warning mini red" data-toggle="modal">
                                                <i class="icon-trash"></i>
                                                <?=$this->translate('Delete')?>
                                            </a>
                                            <div id="deleteModal<?=$social['order']?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                    <h3 id="myModalLabel3">Please Confirm</h3>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to delete this footer social?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                                                    <button data-dismiss="modal" class="btn blue"
                                                            onclick="window.location.href = '<?=$this->url('admin-content-footer-socials', array('action' => 'deleteFooterSocial', 'social' => $social['order'], 'language' => $this->activeLanguage->getId()))?>';">Confirm</button>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php else: ?>
                                    <?=$this->translate('There is no footer socials added')?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        TableManaged.init();
    });
</script>
<!-- END JAVASCRIPTS -->