<?php
$title = 'Landing';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <div class="tabbable tabbable-custom boxless">
            <ul class="nav nav-tabs">
            <?php foreach ($this->regions as $i => $region) : ?>
                <li <?= ($region['id'] == $this->activeRegion->getId() ? ' class="active"' : '')?>>
                    <a href="<?=$this->url('admin-content-landing', array('region' => $region['id']))?>"><?=$region['displayName']?></a>
                </li>
            <?php endforeach; ?>
            </ul>
            <div class="tab-content">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('admin-content-landing', array('region' => $this->activeRegion->getId())));
                $form->prepare();
                echo $this->form()->openTag($form);
                $elements = $form->getElements();
                ?>
                <div class="form">
                    <div class="row-fluid">
                    <?php
                        foreach ($elements as $element) :
                        $type = $element->getAttribute('type');
                        $hint = $element->getAttribute('hint');
                        if ($type != 'submit') : ?>
                        <div class="control-group form-horizontal">
                            <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                            <div class="controls">
                                <?php if ($type == 'text') : ?>
                                    <div class="input-prepend">
                                        <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$type?>" name="<?=$element->getName()?>" value="<?=$element->getValue()?>"/>
                                    </div>
                                <?php elseif($type == 'file'): $image = $element->getValue() != null && $element->getValue() instanceof \Application\Model\Entities\ContentImage ? $element->getValue() : false;?>
                                    <div class="fileupload fileupload-<?=(!$image ? 'exists' : 'new')?>" data-provides="fileupload">
                                        <div class="input-append">
                                            <div class="uneditable-input">
                                                <i class="icon-file fileupload-exists"></i>
                                                <span class="fileupload-preview">
                                                    <?php if(!empty($image)) : ?>
                                                        <input type="hidden" name="<?=$element->getAttribute('name')?>[stored]" value="1"/>
                                                        <a href="<?=$image->getWidth1280()?>" target="_blank">1280</a>
                                                        <a href="<?=$image->getWidth1024()?>" target="_blank">1024</a>
                                                        <a href="<?=$image->getWidth600()?>" target="_blank">600</a>
                                                        <a href="<?=$image->getWidth480()?>" target="_blank">480</a>
                                                    <?php endif; ?>
                                                </span>
                                            </div>
                                            <span class="btn btn-file">
                                                <span class="fileupload-new"><?=$this->translate('Select file')?></span>
                                                <span class="fileupload-exists"><?=$this->translate('Change')?></span>
                                                <input type="file" value="" class="default" name="<?=$element->getAttribute('name')?>"/>
                                            </span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?=$this->translate('Remove')?></a>
                                        </div>
                                        <?php if (!empty($hint)) : ?>
                                            <span class="help-inline"><?=$hint?></span>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php endif; endforeach; ?>
                        <div class="form-actions">
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> <?=$this->translate($elements['submit']->getValue())?></button>
                            <button type="button" class="btn" onclick="this.form.reset();">Cancel</button>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box grey">
            <div class="portlet-title">
                <h4><i class="icon-user"></i><?=$this->translate('Gameplay Blocks')?></h4>
                <div class="actions">
                    <?php if (count($this->gameplayBlocks) < $this->maxBlocks): ?>
                        <a href="<?=$this->url('admin-content-landing', array('region' => $this->activeRegion->getId(),'action' => 'addBlock'))?>" class="btn green"><i class="icon-plus"></i> <?=$this->translate('Add')?></a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="portlet-body">
                <?php if (!empty($this->gameplayBlocks)) : ?>
                    <table class="table table-striped table-bordered table-hover" id="seasons-table">
                        <thead>
                        <tr>
                            <th><?=$this->translate('Order')?></th>
                            <th><?=$this->translate('Heading')?></th>
                            <th><?=$this->translate('Description')?></th>
                            <th style="width: 150px"><?=$this->translate('Foreground Image')?></th>
                            <th style="width: 150px"></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->gameplayBlocks as $block) : ?>
                                <tr class="odd gradeX">
                                    <td><?=$block['order']?></td>
                                    <td><?=$block['heading']?></td>
                                    <td><?=$block['description']?></td>
                                    <td>
                                        <a href="<?=$block['foregroundImage']['width1280']?>" target="_blank">1280</a>
                                        <a href="<?=$block['foregroundImage']['width1024']?>" target="_blank">1024</a>
                                        <a href="<?=$block['foregroundImage']['width600']?>" target="_blank">600</a>
                                        <a href="<?=$block['foregroundImage']['width480']?>" target="_blank">480</a>
                                    </td>
                                    <td>
                                        <a href="<?=$this->url('admin-content-landing', array('action' => 'editBlock', 'block' => $block['order'], 'region' => $this->activeRegion->getId()))?>" class="btn mini blue">
                                            <i class="icon-edit"></i>
                                            <?=$this->translate('Edit')?>
                                        </a>
                                        <a href="<?=$this->url('admin-content-landing', array('action' => 'deleteBlock', 'block' => $block['order'], 'region' => $this->activeRegion->getId()))?>" class="btn mini red">
                                            <i class="icon-trash"></i>
                                            <?=$this->translate('Delete')?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <?=$this->translate('There is no blocks created')?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('users per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ users')?>"};
        TableManaged.init(messages);
    });
</script>
<!-- END JAVASCRIPTS -->