<?php
$title = 'Tracking Code';
$this->headTitle($title);
?>
<div class="row-fluid form-vertical landing">
    <div class="span12">
        <form action="<?=$this->url('admin-content-tracking-code'); ?>" method="post" class="form-vertical">
            <div class="form">
                <div class="row-fluid">
                    <div class="control-group form-horizontal">
                        <div class="controls">
                            <div class="input-prepend">
                                <textarea class="" name="tracking-code" rows="10" style="width: 500px;"><?=$this->trackingCode;?></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>
                        <button type="button" class="btn" onclick="this.form.reset();">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
    });
</script>