<div id="passwordModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h3 id="myModalLabel3"><?php echo $this->translate('Change Password')?></h3>
    </div>
    <div class="modal-body">
        <p><?php echo $this->translate('You logged in for the first time. Now you can change your temporary password.');?></p>
        <div class="container-fluid">
            <?php
            $passwordForm = $this->passwordForm;
            $passwordForm->prepare();
            $passwordForm->setAttribute('action', $this->url('admin-account'));
            $elements = $passwordForm->getElements();
            echo $this->form()->openTag($passwordForm);
            $elements = $passwordForm->getElements();
            ?>
            <div class="form">
                <div class="row-fluid">
                    <?php foreach($elements as $element):?>
                        <?php
                        $type = $element->getAttribute('type');
                        $hint = $element->getAttribute('hint');
                        ?>
                        <?php if ($element->getAttribute('name') != 'submit'):?>
                            <?php if ($type == 'password'):?>
                                <div class="control-group form-horizontal">
                                    <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?> value="<?=$element->getValue();?>"/>
                                        </div>
                                        <?php if (!empty($hint)) : ?>
                                            <span class="help-inline"><?=$hint?></span>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php elseif ($type == 'hidden'):?>
                                <?php echo $this->formHidden($passwordForm->get('type'));?>
                            <?php endif;?>
                        <?php endif;?>
                    <?php endforeach;?>
                </div>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>

    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close');?></button>
        <button data-dismiss="modal" class="btn blue"
                onclick="$('#account-password').submit();">
            <?php echo $this->translate('Change');?>
        </button>
    </div>
</div>
<a href="#passwordModal" role="button"  class="display-change-password" data-toggle="modal" style="display:none;"></a>
<script text="type\javascript">
    jQuery(document).ready(function(){
        jQuery('.display-change-password').click();
    });
</script>