<?php
$pages = $this->container->getPages();
foreach ($pages as $page)
    if ($page->getRoute() == 'admin-home') {
        $pages = $page;
        break;
    }
$first = true;
?>
<ul>
    <li>
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        <div class="sidebar-toggler hidden-phone"></div>
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    </li>
<?php foreach ($pages as $page) : ?>
    <?php
        $classes = array();
        if ($first) {
            $classes [] = 'start';
            $first = false;
        }
        if ($page->isActive(true))
            $classes [] = 'active';
        $props = $page->getCustomProperties();
        $showSubMenu = array_key_exists('sub-menu', $props) ? $props['sub-menu'] : false;
        $exclude = array_key_exists('exclude-from-menu', $props) ? $props['exclude-from-menu'] : false;
        if ($exclude) continue;
    ?>
    <li<?=empty($classes) ? '' : (' class="' . implode(" ", $classes) . '"')?>>
        <a href="<?=$page->getHref()?>">
            <i class="<?=$page->getLabel()?>"></i>
            <span class="title">
                <?= $this->translate($page->getTitle()) ?>
            </span>
            <?php if ($page->isActive(true)) : ?>
                <span class="selected"></span>
            <?php endif;?>
            <?php if ($showSubMenu) : ?>
                <span class="arrow "></span>
            <?php endif;?>
        </a>
        <?php if ($showSubMenu) : ?>
            <ul class="sub-menu">
                <?php foreach($page as $subPage):
                    $use = $subPage->useRouteMatch();
                    $subPage->setUseRouteMatch(false);
                    ?>
                    <li <?=$subPage->isActive(true) ? 'class="active"' : ''?>>
                        <a href="<?=$subPage->getHref()?>">
                            <?php if ($subPage->getLabel() != null): ?>
                                <i class="<?=$subPage->getLabel()?>"></i>
                            <?php endif; ?>
                            <?=$this->translate($subPage->getTitle())?>
                        </a>
                    </li>
                <?php
                    $subPage->setUseRouteMatch($use);
                    endforeach; ?>
            </ul>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
