<?php
$title = 'Dashboard';
$this->headTitle($title);
?>
<div id="dashboard">
    <!-- BEGIN DASHBOARD STATS -->
    <div class="row-fluid">
        <div class="span4 responsive" data-tablet="span6" data-desktop="span4">
            <div class="dashboard-stat blue">
                <div class="visual">
                    <i class="icon-user"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->registeredUsersNumber?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Registered Users')?>
                    </div>
                </div>
                <a class="more" href="<?=$this->url('admin-users')?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        <div class="span4 responsive" data-tablet="span6" data-desktop="span4">
            <div class="dashboard-stat green">
                <div class="visual">
                    <i class="icon-user"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->activeUsersNumber?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Active Users')?>
                    </div>
                </div>
                <a class="more" href="<?=$this->url('admin-users')?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        <div class="span4 responsive" data-tablet="span6 fix-offset" data-desktop="span4">
            <div class="dashboard-stat red">
                <div class="visual">
                    <i class="icon-user"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->inactiveUsersNumber?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Inactive Users')?>
                    </div>
                </div>
                <a class="more" href="<?=$this->url('admin-users')?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        <div class="span4 responsive" data-tablet="span6" data-desktop="span4 fix-offset">
            <div class="dashboard-stat black">
                <div class="visual short">
                    <i class="icon-bar-chart"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->avgNumberOfPredictions?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Average Number Of Predictions')?>
                    </div>
                </div>
                <a class="more" href="<?=$this->url('admin-fixtures')?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        <div class="span4 responsive" data-tablet="span6 fix-offset" data-desktop="span4">
            <div class="dashboard-stat green">
                <div class="visual">
                    <i class="m-icon-big-swapright m-icon-white"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->nextMatchPredictions?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Next Match Predictions')?>
                    </div>
                </div>
                <?php
                $nextMatchLink = $this->nextMatchId != -1 ? $this->url('admin-fixtures', array('action' => 'edit', 'fixture' => $this->nextMatchId)) : '#';
                ?>
                <a class="more" href="<?=$nextMatchLink?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
        <div class="span4 responsive" data-tablet="span6" data-desktop="span4">
            <div class="dashboard-stat yellow">
                <div class="visual">
                    <i class="m-icon-big-swapleft m-icon-white"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=$this->prevMatchPredictions?>
                    </div>
                    <div class="desc">
                        <?=$this->translate('Previous Match Predictions')?>
                    </div>
                </div>
                <?php
                $prevMatchLink = $this->prevMatchId != -1 ? $this->url('admin-fixtures', array('action' => 'edit', 'fixture' => $this->prevMatchId)) : '#';
                ?>
                <a class="more" href="<?=$prevMatchLink?>">
                    <?=$this->translate('View more')?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    </div>
    <!-- END DASHBOARD STATS -->
    <div class="clearfix"></div>
    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey">
                <div class="portlet-title">
                    <h4><i class="icon-user"></i><?=$this->translate('Registered users in past 7 days')?></h4>
                </div>
                <div class="portlet-body">
                    <?php if (!empty($this->usersRegisteredInPast7Days)) : ?>
                        <table class="table table-striped table-bordered table-hover" id="users-table">
                            <thead>
                                <tr>
                                    <th><?=$this->translate('Name')?></th>
                                    <th class="hidden-480"><?=$this->translate('Email')?></th>
                                    <th><?=$this->translate('Gender')?></th>
                                    <th><?=$this->translate('Facebook')?></th>
                                    <th class="hidden-480"><?=$this->translate('Joined')?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->usersRegisteredInPast7Days as $user) : ?>
                                    <tr class="odd gradeX">
                                        <td><?=$user['displayName']?></td>
                                        <td class="hidden-480"><a href="mailto:<?=$user['email']?>"><?=$user['email']?></a></td>
                                        <td>
                                            <div class="glyphicons no-js <?=strtolower($user['gender']) == 'male' ? 'user' : 'girl'?>"><i></i></div>
                                        </td>
                                        <td>
                                            <?=empty($user['facebookId']) ? 'NO' : 'YES'?>
                                        </td>
                                        <td class="hidden-480">
                                            <?=$user['date']->format("j F H:i")?>
                                        </td>
                                    </tr>
                                <?php endforeach ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <?=$this->translate('No users registered in past 7 days')?>
                    <?php endif; ?>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

</div>
<!-- BEGIN PAGE LEVEL STYLES -->
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/glyphicons/css/glyphicons.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.css" />
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/plugins/data-tables/DT_bootstrap.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
<script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/table-managed.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init(); // initlayout and core plugins
        var messages = {perPage: "_MENU_ " + "<?=$this->translate('users per page')?>", nextLink: "<?=$this->translate('Next')?>",
            prevLink: "<?=$this->translate('Previous')?>", showingLabel: "<?=$this->translate('Showing _START_ to _END_ of _TOTAL_ users')?>"};
        TableManaged.init(messages);
    });
</script>
<!-- END JAVASCRIPTS -->