<?php
$this->headTitle($this->title);
?>
<div class="container-fluid">
    <?php
    $personalInfoForm = $this->personalInfoForm;
    $personalInfoForm->prepare();
    $personalInfoForm->setAttribute('action', $this->url('admin-account'));
    $elements = $personalInfoForm->getElements();
    echo $this->form()->openTag($personalInfoForm);
    $elements = $personalInfoForm->getElements();
    ?>
    <div class="form">
        <h3><?php echo $this->translate('Personal Info');?></h3>
        <div class="row-fluid">
            <?php foreach($elements as $element):?>
                <?php
                    $type = $element->getAttribute('type');
                    $hint = $element->getAttribute('hint');
                ?>
                    <?php if ($element->getAttribute('name') != 'submit'):?>
                        <?php if ($type == 'text'):?>
                            <div class="control-group form-horizontal">
                                <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?> value="<?=$element->getValue();?>"/>
                                    </div>
                                    <?php if (!empty($hint)) : ?>
                                        <span class="help-inline"><?=$hint?></span>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php elseif ($type == 'hidden'):?>
                            <?php echo $this->formHidden($personalInfoForm->get('type'));?>
                        <?php endif;?>
                        <?php else:?>
                            <div class="form-actions">
                                <button type="submit" class="btn blue"><?=$this->translate($element->getValue());?></button>
                                <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                            </div>
                        <?php endif;?>
            <?php endforeach;?>
        </div>
   </div>
    <?php echo $this->form()->closeTag();?>
</div>
<div class="container-fluid">
    <?php
    $passwordForm = $this->passwordForm;
    $passwordForm->prepare();
    $passwordForm->setAttribute('action', $this->url('admin-account'));
    $elements = $passwordForm->getElements();
    echo $this->form()->openTag($passwordForm);
    $elements = $passwordForm->getElements();
    ?>
    <div class="form">
        <h3><?php echo $this->translate('Password');?></h3>
        <div class="row-fluid">
            <?php foreach($elements as $element):?>
            <?php
            $type = $element->getAttribute('type');
            $hint = $element->getAttribute('hint');
            ?>
            <?php if ($element->getAttribute('name') != 'submit'):?>
                <?php if ($type == 'password'):?>
                    <div class="control-group form-horizontal">
                        <label class="control-label"><?=$this->translate($element->getLabel())?></label>
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-tag"></i></span><input class="m-wrap medium" type="<?=$element->getAttribute('type');?>" name="<?=$element->getAttribute('name');?>" <?php echo ($element->getAttribute('maxlength') ? 'maxlength="'.$element->getAttribute('maxlength'). '"' : '');?> value="<?=$element->getValue();?>"/>
                            </div>
                            <?php if (!empty($hint)) : ?>
                            <span class="help-inline"><?=$hint?></span>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php elseif ($type == 'hidden'):?>
                    <?php echo $this->formHidden($passwordForm->get('type'));?>
                <?php endif;?>
                <?php else:?>
                    <div class="form-actions">
                        <button type="submit" class="btn blue"><?=$this->translate($element->getValue());?></button>
                        <button type="button" class="btn reset"><?php echo $this->translate('Cancel');?></button>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
    </div>
    <?php echo $this->form()->closeTag();?>
</div>

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="<?=$this->getConstant('admin_assets_path_prefix')?>assets/scripts/app.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script type="text/javascript">

        jQuery(document).ready(function() {
            $('button.reset').click(function(e){
                e.preventDefault();
                this.form.reset();
            });
            App.init(); // initlayout and core plugins
        });
    </script>
    <!-- END JAVASCRIPTS -->