<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9 ie8"> <![endif]-->
<!--[if IE 9]>         <html class="no-js ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('Score Predictor') . ' - ' . $this->getConstant('club_name');?> </title>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . $this->getConstant('favicon_path') . "?" . rand(0, 1)))?>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="/css/normalize.min.css">

    <link rel="stylesheet" href="/css/styles.css">

    <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="/css/ie.css">
    <script src="/js/vendor/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->
</head>
<body class="home-page" style="background: <?=$this->settingsHelper()->getBackgroundColor()?>;">
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<div id="wrapper">
    <header role="banner">
        <div  class="banner">
            <?php echo $this->renderLogotype();?>
            <div data-alt="FCBARCELONA Score Predictor Banner" data-picture="">
                <div data-src="<?=$this->content['heroBackgroundImage']['width480']?>"></div>
                <div data-media="(min-width: 480px)" data-src="<?=$this->content['heroBackgroundImage']['width480']?>"></div>
                <div data-media="(min-width: 600px)" data-src="<?=$this->content['heroBackgroundImage']['width600']?>"></div>
                <div data-media="(min-width: 768px)" data-src="<?=$this->content['heroBackgroundImage']['width1024']?>"></div>
                <div data-media="(min-width: 1025px)" data-src="<?=$this->content['heroBackgroundImage']['width1280']?>"></div>
                <noscript><img src="<?=$this->content['heroBackgroundImage']['width1024']?>" alt="FCBARCELONA Score Predictor Banner" /></noscript>
                <!--[if (lt IE 9) & (!IEMobile)]>
                <div data-src="<?=$this->content['heroBackgroundImage']['width1280']?>"></div>
                <![endif]-->
            </div>
            <figure>
                <div class="banner-image-top">
                    <div data-alt="FCBARCELONA Score Predictor Banner" data-picture="">
                        <div data-src="<?=$this->content['heroForegroundImage']['width480']?>"></div>
                        <div data-media="(min-width: 480px)" data-src="<?=$this->content['heroForegroundImage']['width480']?>"></div>
                        <div data-media="(min-width: 600px)" data-src="<?=$this->content['heroForegroundImage']['width600']?>"></div>
                        <div data-media="(min-width: 768px)" data-src="<?=$this->content['heroForegroundImage']['width1024']?>"></div>
                        <div data-media="(min-width: 1025px)" data-src="<?=$this->content['heroForegroundImage']['width1280']?>"></div>
                        <noscript><img src="<?=$this->content['heroForegroundImage']['width1024']?>" alt="FCBARCELONA Score Predictor Banner" /></noscript>
                        <!--[if (lt IE 9) & (!IEMobile)]>
                        <div data-src="<?=$this->content['heroForegroundImage']['width1280']?>"></div>
                        <![endif]-->
                    </div>
                </div>

                <figcaption>
                    <?=$this->content['headlineCopy']?>
                    <a href="<?=$this->url("registration")?>" class="cta"><?=$this->content['registerButtonCopy']?></a>
                </figcaption>
            </figure>
<!--            <aside class="find-out-more">-->
<!--                <span>--><?//=$this->translate('Find out more')?><!--</span>-->
<!--            </aside>-->
        </div>

        <div class="login-area clearfix">
            <p>
                <span><?=$this->translate('Already a member?')?></span>
                <?php  echo $this->renderFacebookButton($this->translate('Login with Facebook'));?>
            </p>
            <details open="open" class="popup">
                <summary class="login-popup-button"><span><?php echo $this->translate('Regular Login');?></span></summary>
                <div class="login-form popup-content">
                    <form action="<?php echo $this->url('login');?>" method="post" novalidate="true">
                        <p class="field">
                            <label for="email"><?php echo $this->translate('Email');?></label>
                            <input id="email" name="email" required="required" type="text">
                        </p>
                        <p class="field">
                            <label for="password"><?php echo $this->translate('Password');?></label>
                            <input id="password" name="password" required="required" type="password">
                        </p>
                        <p class="keeplogin">
                            <input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping">
                            <label for="loginkeeping"><?php echo $this->translate('Remember me');?></label>
                        </p>
                        <p class="signin-button">
                            <input type="submit" value="<?php echo $this->translate('Sign in');?>">
                        </p>
                        <p>
                            <a href="<?php echo $this->url('forgot');?>"><?php echo $this->translate('Forgotten password');?></a>
                        </p>
                        <p> <?php echo $this->translate('Not a member?');?>
                            <a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register');?></a>
                        </p>
                    </form>
                    <button class="close popup-close"><?php echo $this->translate('Close');?></button>
                </div>
            </details>
        </div>

    </header>
    <div role="main">
        <?php foreach ($this->blocks as $block) : ?>
        <article class="article-image article-image-<?=$block['order'] % 2 == 1 ? 'right' : 'left'?> clearfix user-content">
            <div>
                <h2><?=$block['heading']?></h2>
                <p><?=$block['description']?></p>
            </div>
            <figure>
                <div data-alt="<?=$block['heading']?>" data-picture="">
                    <div data-src="<?=$block['foregroundImage']['width480']?>"></div>
                    <div data-media="(min-width: 480px)" data-src="<?=$block['foregroundImage']['width480']?>"></div>
                    <div data-media="(min-width: 600px)" data-src="<?=$block['foregroundImage']['width600']?>"></div>
                    <div data-media="(min-width: 768px)" data-src="<?=$block['foregroundImage']['width1024']?>"></div>
                    <div data-media="(min-width: 1025px)" data-src="<?=$block['foregroundImage']['width1280']?>"></div>
                    <noscript><img src="<?=$block['foregroundImage']['width1024']?>" alt="<?=$block['heading']?>" /></noscript>
                    <!--[if (lt IE 9) & (!IEMobile)]>
                    <div data-src="<?=$block['foregroundImage']['width1280']?>"></div>
                    <![endif]-->
                </div>
            </figure>
        </article>
        <?php endforeach; ?>
        <aside class="ready-try">
            <p><?=$this->translate('Ready to try?');?> <a href="<?=$this->url("registration")?>" class="cta"><?=$this->content['registerButtonCopy']?></a></p>
        </aside>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>

    <script src="/js/jquery.cookie.js"></script>
    <script src="js/login-popup.js"></script>
    <script src="js/vendor/picturefill.js"></script>
    <script src="js/main.js"></script>

    <?php echo $this->partial('partials/footer');?>

</div>
</body>
</html>
